//! Biological natural biomes, recommended scenery, and natural color palettes
//! for all 106 Forgum mascots.
//!
//! Single authoritative source of truth shared across `forgum-platform`,
//! `forgum-engine`, and `forgum-tui`.

/// Canonical biological biome, recommended scenery, and natural coloration metadata.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MascotBiomeInfo {
    pub name: &'static str,
    pub category: &'static str,
    pub biome_name: &'static str,
    pub environment: &'static str,
    pub road: &'static str,
    pub mountain: &'static str,
    pub natural_palette: [&'static str; 5],
    pub natural_rgb: [(u8, u8, u8); 5],
    pub description: &'static str,
    pub movement_lore: &'static str,
}

/// Static registry of all 106 mascots.
pub static ALL_MASCOTS: [MascotBiomeInfo; 106] = [
    MascotBiomeInfo {
        name: "default",
        category: "Farm & Domestic",
        biome_name: "Pasture & Rolling Meadows",
        environment: "pasture",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#ffffff", "#1a1a1a", "#2c2c2c", "#ffb6c1", "#000000"],
        natural_rgb: [(255, 255, 255), (26, 26, 26), (44, 44, 44), (255, 182, 193), (0, 0, 0)],
        description: "Classic domestic dairy Holstein cow with iconic black and white markings and pink udder.",
        movement_lore: "Peaceful 4-phase walking gait across sunlit pastures with procedural chewing rhythm.",
    },
    MascotBiomeInfo {
        name: "cat",
        category: "Farm & Domestic",
        biome_name: "Homestead Garden & Porch",
        environment: "pasture",
        road: "cobblestone",
        mountain: "hills",
        natural_palette: ["#d35400", "#795548", "#ffffff", "#ffb6c1", "#212121"],
        natural_rgb: [(211, 84, 0), (121, 85, 72), (255, 255, 255), (255, 182, 193), (33, 33, 33)],
        description: "Calico farm feline with warm ginger, chocolate brown, crisp white bib, and pink nose.",
        movement_lore: "Stealthy low-slung stalking prowl with delicate paw placements and tail balance flickers.",
    },
    MascotBiomeInfo {
        name: "cat2",
        category: "Farm & Domestic",
        biome_name: "Urban Cobblestone Patio",
        environment: "city",
        road: "cobblestone",
        mountain: "skyline",
        natural_palette: ["#546e7a", "#78909c", "#cfd8dc", "#ffb6c1", "#4caf50"],
        natural_rgb: [(84, 110, 122), (120, 144, 156), (207, 216, 220), (255, 182, 193), (76, 175, 80)],
        description: "Russian Blue / Silver Tabby with luminous jade-green eyes and shimmering silver coat.",
        movement_lore: "Graceful athletic rooftop traversal and curious harmonic head tilts.",
    },
    MascotBiomeInfo {
        name: "catfence",
        category: "Farm & Domestic",
        biome_name: "Rustic Paddock Fence",
        environment: "pasture",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#795548", "#d35400", "#ffffff", "#ffb6c1", "#212121"],
        natural_rgb: [(121, 85, 72), (211, 84, 0), (255, 255, 255), (255, 182, 193), (33, 33, 33)],
        description: "Tabby cat perched curiously along weathered cedar farm fence rails.",
        movement_lore: "Delicate tightrope balance along wooden rails with periodic tail counter-sways.",
    },
    MascotBiomeInfo {
        name: "charlie",
        category: "Farm & Domestic",
        biome_name: "Sunny Country Paddock",
        environment: "pasture",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#6d4c41", "#ffffff", "#d7ccc8", "#ffb6c1", "#3e2723"],
        natural_rgb: [(109, 76, 65), (255, 255, 255), (215, 204, 200), (255, 182, 193), (62, 39, 35)],
        description: "Domestic chestnut steer with a distinctive white star blaze and gentle disposition.",
        movement_lore: "Heavy deliberate bovine amble with expressive head bobbing.",
    },
    MascotBiomeInfo {
        name: "corgi",
        category: "Farm & Domestic",
        biome_name: "Royal Palace Grounds",
        environment: "pasture",
        road: "cobblestone",
        mountain: "castle",
        natural_palette: ["#d35400", "#ffffff", "#e59866", "#ffb6c1", "#212121"],
        natural_rgb: [(211, 84, 0), (255, 255, 255), (229, 152, 102), (255, 182, 193), (33, 33, 33)],
        description: "Pembroke Welsh Corgi with golden-red foxy coat, crisp white ruff, and bubbly spirit.",
        movement_lore: "Enthusiastic short-legged trot with joyful rhythmic rear-waddle.",
    },
    MascotBiomeInfo {
        name: "bunny",
        category: "Farm & Domestic",
        biome_name: "Clover Meadow & Warrens",
        environment: "pasture",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#ffffff", "#fdfefe", "#f7f9f9", "#ffb6c1", "#ffc0cb"],
        natural_rgb: [(255, 255, 255), (253, 254, 254), (247, 249, 249), (255, 182, 193), (255, 192, 203)],
        description: "Pure snowy white meadow bunny with delicate soft pink inner ears and twitching nose.",
        movement_lore: "Nimble double-hop bounding gait interspersed with alert ear-swiveling pauses.",
    },
    MascotBiomeInfo {
        name: "doge",
        category: "Farm & Domestic",
        biome_name: "Zen Garden & Temple Steps",
        environment: "pasture",
        road: "cobblestone",
        mountain: "garden",
        natural_palette: ["#e59866", "#d35400", "#fdfefe", "#edbb99", "#2c3e50"],
        natural_rgb: [(229, 152, 102), (211, 84, 0), (253, 254, 254), (237, 187, 153), (44, 62, 80)],
        description: "Shiba Inu with iconic golden-tan sesame coat, pristine white urajiro, and soulful eyes.",
        movement_lore: "Proud spirited strut with curled-tail balance and quizzical side-head tilts.",
    },
    MascotBiomeInfo {
        name: "fat-cow",
        category: "Farm & Domestic",
        biome_name: "Lush Clover Pasture",
        environment: "pasture",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#ffffff", "#212121", "#e0e0e0", "#ffb6c1", "#424242"],
        natural_rgb: [(255, 255, 255), (33, 33, 33), (224, 224, 224), (255, 182, 193), (66, 66, 66)],
        description: "Plump prize-winning farm cow contentedly grazing on sweet springtime clover.",
        movement_lore: "Slow ponderous heavy-cadence waddle with rhythmic tail swishes against flies.",
    },
    MascotBiomeInfo {
        name: "goat",
        category: "Farm & Domestic",
        biome_name: "Rocky Highland Escarpment",
        environment: "pasture",
        road: "cobblestone",
        mountain: "peaks",
        natural_palette: ["#d7ccc8", "#8d6e63", "#ffffff", "#ffcdd2", "#ffb300"],
        natural_rgb: [(215, 204, 200), (141, 110, 99), (255, 255, 255), (255, 205, 210), (255, 179, 0)],
        description: "Sure-footed alpine goat with stony fleece, agile cleft hooves, and amber slit pupils.",
        movement_lore: "High-stepping agile leap and bound across steep rocky terrain.",
    },
    MascotBiomeInfo {
        name: "goat2",
        category: "Farm & Domestic",
        biome_name: "Mountain Crag Sanctuary",
        environment: "pasture",
        road: "cobblestone",
        mountain: "peaks",
        natural_palette: ["#8d6e63", "#5d4037", "#d7ccc8", "#ffcdd2", "#212121"],
        natural_rgb: [(141, 110, 99), (93, 64, 55), (215, 204, 200), (255, 205, 210), (33, 33, 33)],
        description: "Weathered wild mountain billy goat with swept-back ridged horns and chin beard.",
        movement_lore: "Sturdy calculated climbing strides navigating sheer cliffside promontories.",
    },
    MascotBiomeInfo {
        name: "hippie",
        category: "Farm & Domestic",
        biome_name: "Woodstock Wildflower Field",
        environment: "pasture",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#ff007f", "#00e5ff", "#ffff00", "#76ff03", "#d500f9"],
        natural_rgb: [(255, 0, 127), (0, 229, 255), (255, 255, 0), (118, 255, 3), (213, 0, 249)],
        description: "Peace-loving bohemian musician draped in dazzling rainbow tie-dye velvet vest.",
        movement_lore: "Harmonic rhythmic acoustic sway radiating good vibrations across the valley.",
    },
    MascotBiomeInfo {
        name: "kitty",
        category: "Farm & Domestic",
        biome_name: "Sunlit Parlor Rug",
        environment: "city",
        road: "sidewalk",
        mountain: "skyline",
        natural_palette: ["#e67e22", "#fef3c7", "#ffffff", "#ff8a80", "#f59e0b"],
        natural_rgb: [(230, 126, 34), (254, 243, 199), (255, 255, 255), (255, 138, 128), (245, 158, 11)],
        description: "Spirited ginger domestic kitten with playful bright eyes and soft cream belly.",
        movement_lore: "High-energy bouncing pounce with animated tail flicks and inquisitive whisker twitches.",
    },
    MascotBiomeInfo {
        name: "kitten",
        category: "Farm & Domestic",
        biome_name: "Cozy Homestead Barn",
        environment: "pasture",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#d35400", "#795548", "#ffffff", "#ffb6c1", "#212121"],
        natural_rgb: [(211, 84, 0), (121, 85, 72), (255, 255, 255), (255, 182, 193), (33, 33, 33)],
        description: "Inquisitive young calico kitten exploring haystack corners and wooden rafters.",
        movement_lore: "Light-footed curious scurrying with tiny paws and upright curiosity antenna tail.",
    },
    MascotBiomeInfo {
        name: "meow",
        category: "Farm & Domestic",
        biome_name: "Moonlit Slate Rooftops",
        environment: "city",
        road: "roof",
        mountain: "skyline",
        natural_palette: ["#1e1e1e", "#5c4033", "#ffffff", "#f8bbd0", "#0288d1"],
        natural_rgb: [(30, 30, 30), (92, 64, 51), (255, 255, 255), (248, 187, 208), (2, 136, 209)],
        description: "Sleek tuxedo feline with midnight coat, pristine white paws, and piercing blue gaze.",
        movement_lore: "Silent shadow-stepping glide along ceramic roof crests with fluid serpentine spine.",
    },
    MascotBiomeInfo {
        name: "hamster",
        category: "Farm & Domestic",
        biome_name: "Golden Grain Burrow",
        environment: "pasture",
        road: "cobblestone",
        mountain: "hills",
        natural_palette: ["#d4a373", "#faedcd", "#e76f51", "#ffb6c1", "#3e2723"],
        natural_rgb: [(212, 163, 115), (250, 237, 205), (231, 111, 81), (255, 182, 193), (62, 39, 35)],
        description: "Chubby Syrian hamster with golden-brown fur, cream underbelly, and stuffed seed pouches.",
        movement_lore: "Frenetic rapid-step scurry with adorable nose-twitching sniffing intervals.",
    },
    MascotBiomeInfo {
        name: "mule",
        category: "Farm & Domestic",
        biome_name: "Canyon Pack Trail",
        environment: "pasture",
        road: "dirt",
        mountain: "peaks",
        natural_palette: ["#5c4033", "#795548", "#8d6e63", "#d7ccc8", "#3e2723"],
        natural_rgb: [(92, 64, 51), (121, 85, 72), (141, 110, 99), (215, 204, 200), (62, 39, 35)],
        description: "Dependable pack mule with rich chestnut-brown coat, pale muzzle ring, and long ears.",
        movement_lore: "Steadfast rhythmic endurance pack march unyielding across rough mountain trails.",
    },
    MascotBiomeInfo {
        name: "pig",
        category: "Farm & Domestic",
        biome_name: "Mud Wallow & Orchard",
        environment: "pasture",
        road: "mud",
        mountain: "hills",
        natural_palette: ["#ffb6c1", "#ff80ab", "#f8bbd0", "#ff4081", "#c2185b"],
        natural_rgb: [(255, 182, 193), (255, 128, 171), (248, 187, 208), (255, 64, 129), (194, 24, 91)],
        description: "Cheerful rosy pink domestic pig with curly corkscrew tail and disk snout.",
        movement_lore: "Bubbly trot and snout-rooting through fertile soil and cooling mud baths.",
    },
    MascotBiomeInfo {
        name: "ram",
        category: "Farm & Domestic",
        biome_name: "High Alpine Windswept Ridge",
        environment: "pasture",
        road: "cobblestone",
        mountain: "peaks",
        natural_palette: ["#f5f5f5", "#9e9e9e", "#e0e0e0", "#757575", "#212121"],
        natural_rgb: [(245, 245, 245), (158, 158, 158), (224, 224, 224), (117, 117, 117), (33, 33, 33)],
        description: "Majestic bighorn ram with dense snowy fleece and formidable curved ridged horns.",
        movement_lore: "Powerful defiant strides pacing the mountain precipice with dominant horn displays.",
    },
    MascotBiomeInfo {
        name: "rooster",
        category: "Farm & Domestic",
        biome_name: "Dawn Farmyard Perch",
        environment: "pasture",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#d32f2f", "#1a237e", "#e65100", "#fbc02d", "#ffb300"],
        natural_rgb: [(211, 47, 47), (26, 35, 126), (230, 81, 0), (251, 192, 45), (255, 179, 0)],
        description: "Proud barnyard cockerel with fiery crimson comb, iridescent midnight tail, and gold hackles.",
        movement_lore: "Strutting parade march puffing out chest plumage before greeting the morning sun.",
    },
    MascotBiomeInfo {
        name: "sheep",
        category: "Farm & Domestic",
        biome_name: "Rolling Green Downs",
        environment: "pasture",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#ffffff", "#f5f5f5", "#3e2723", "#ffb6c1", "#9e9e9e"],
        natural_rgb: [(255, 255, 255), (245, 245, 245), (62, 39, 35), (255, 182, 193), (158, 158, 158)],
        description: "Fluffy woolly sheep grazing serenely on dew-covered clover and wild ryegrass.",
        movement_lore: "Gentle synchronized flock amble moving like rolling white clouds across green pastures.",
    },
    MascotBiomeInfo {
        name: "turkey",
        category: "Farm & Domestic",
        biome_name: "Autumn Oak Woodlands",
        environment: "forest",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#5d4037", "#c62828", "#0288d1", "#f57f17", "#212121"],
        natural_rgb: [(93, 64, 55), (198, 40, 40), (2, 136, 209), (245, 127, 23), (33, 33, 33)],
        description: "Wild woodland turkey with shimmering bronze plumage, crimson wattle, and sky-blue head.",
        movement_lore: "Stately fan-tailed strut displaying iridescent plumage through forest clearings.",
    },
    MascotBiomeInfo {
        name: "armadillo",
        category: "Wild & Safari",
        biome_name: "Arid Scrubland & Burrows",
        environment: "savanna",
        road: "savanna",
        mountain: "plateau",
        natural_palette: ["#8d6e63", "#d7ccc8", "#bcaaa4", "#5d4037", "#3e2723"],
        natural_rgb: [(141, 110, 99), (215, 204, 200), (188, 170, 164), (93, 64, 55), (62, 39, 35)],
        description: "Nine-banded armadillo with leathery protective carapace and formidable digging claws.",
        movement_lore: "Low ground-sniffing trot ready to curl into an impenetrable armored sphere.",
    },
    MascotBiomeInfo {
        name: "bearface",
        category: "Wild & Safari",
        biome_name: "Old-Growth Pine Woods",
        environment: "forest",
        road: "dirt",
        mountain: "peaks",
        natural_palette: ["#4e342e", "#8d6e63", "#d7ccc8", "#212121", "#ffb300"],
        natural_rgb: [(78, 52, 46), (141, 110, 99), (215, 204, 200), (33, 33, 33), (255, 179, 0)],
        description: "Grizzly bear with deep umber fur, cinnamon snout ruff, and watchful honey-amber eyes.",
        movement_lore: "Heavy lumbering apex stroll with colossal shoulder mass sway.",
    },
    MascotBiomeInfo {
        name: "elephant",
        category: "Wild & Safari",
        biome_name: "African Veldt & Waterhole",
        environment: "savanna",
        road: "savanna",
        mountain: "plateau",
        natural_palette: ["#78909c", "#455a64", "#cfd8dc", "#fffde7", "#263238"],
        natural_rgb: [(120, 144, 156), (69, 90, 100), (207, 216, 220), (255, 253, 231), (38, 50, 56)],
        description: "Majestic African matriarch elephant with weathered wrinkled hide and gleaming ivory tusks.",
        movement_lore: "Silent dignified march cushioned by elastic foot pads with rhythmic trunk sways.",
    },
    MascotBiomeInfo {
        name: "elephant2",
        category: "Wild & Safari",
        biome_name: "Savanna Baobab Glade",
        environment: "savanna",
        road: "savanna",
        mountain: "plateau",
        natural_palette: ["#607d8b", "#37474f", "#b0bec5", "#fffde7", "#212121"],
        natural_rgb: [(96, 125, 139), (55, 71, 79), (176, 190, 197), (255, 253, 231), (33, 33, 33)],
        description: "Bull elephant proudly trumpeting across the acacia canopy under the midday sun.",
        movement_lore: "Commanding ground-shaking stride surveying expansive African horizons.",
    },
    MascotBiomeInfo {
        name: "elephant-in-snake",
        category: "Wild & Safari",
        biome_name: "Sahara Desert Erg",
        environment: "savanna",
        road: "savanna",
        mountain: "plateau",
        natural_palette: ["#558b2f", "#78909c", "#2e7d32", "#cfd8dc", "#ffd600"],
        natural_rgb: [(85, 139, 47), (120, 144, 156), (46, 125, 50), (207, 216, 220), (255, 214, 0)],
        description: "The Little Prince's philosophical mystery: a giant boa constrictor digesting an elephant.",
        movement_lore: "Hypnotic undulating serpentine crawl harboring a massive interior secret.",
    },
    MascotBiomeInfo {
        name: "fox",
        category: "Wild & Safari",
        biome_name: "Sun-Dappled Woodland Edge",
        environment: "forest",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#d35400", "#ffffff", "#212121", "#e67e22", "#f39c12"],
        natural_rgb: [(211, 84, 0), (255, 255, 255), (33, 33, 33), (230, 126, 34), (243, 156, 18)],
        description: "Red fox with fiery auburn pelt, pure snow-white chest and tail brush, and black socks.",
        movement_lore: "Nimble silent bounding leap pouncing onto woodland moss.",
    },
    MascotBiomeInfo {
        name: "hedgehog",
        category: "Wild & Safari",
        biome_name: "Woodland Leaf Litter & Hedgerow",
        environment: "forest",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#5c4033", "#8d6e63", "#d7ccc8", "#212121", "#a1887f"],
        natural_rgb: [(92, 64, 51), (141, 110, 99), (215, 204, 200), (33, 33, 33), (161, 136, 127)],
        description: "European hedgehog covered in thousands of sharp banded quills and soft furry underbelly.",
        movement_lore: "Busy shuffling trot rustling through autumn oak leaves.",
    },
    MascotBiomeInfo {
        name: "koala",
        category: "Wild & Safari",
        biome_name: "Eucalyptus Forest Canopy",
        environment: "forest",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#9e9e9e", "#f5f5f5", "#212121", "#558b2f", "#424242"],
        natural_rgb: [(158, 158, 158), (245, 245, 245), (33, 33, 33), (85, 139, 47), (66, 66, 66)],
        description: "Australian koala with dense silver-grey fleece, fluffy white ear tufts, and black nose.",
        movement_lore: "Slow deliberate branch-hugging climb chewing aromatic eucalyptus gum leaves.",
    },
    MascotBiomeInfo {
        name: "luke-koala",
        category: "Wild & Safari",
        biome_name: "Jedi Temple Eucalyptus Grove",
        environment: "forest",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#9e9e9e", "#00e5ff", "#f5f5f5", "#d7ccc8", "#212121"],
        natural_rgb: [(158, 158, 158), (0, 229, 255), (245, 245, 245), (215, 204, 200), (33, 33, 33)],
        description: "Force-sensitive koala armed with glowing cyan lightsaber maintaining peace in the trees.",
        movement_lore: "Meditative branch hover channeling the living Force through the forest.",
    },
    MascotBiomeInfo {
        name: "moofasa",
        category: "Wild & Safari",
        biome_name: "Serengeti Pride Rock",
        environment: "savanna",
        road: "savanna",
        mountain: "plateau",
        natural_palette: ["#d4a373", "#5c4033", "#faedcd", "#1a1a1a", "#ffb300"],
        natural_rgb: [(212, 163, 115), (92, 64, 51), (250, 237, 205), (26, 26, 26), (255, 179, 0)],
        description: "Regal golden lion monarch with voluminous dark mane commanding the golden savanna.",
        movement_lore: "Regal predatory stride across Pride Rock surveying the circle of life.",
    },
    MascotBiomeInfo {
        name: "panther",
        category: "Wild & Safari",
        biome_name: "Moonlit Tropical Rainforest",
        environment: "forest",
        road: "dirt",
        mountain: "peaks",
        natural_palette: ["#18181b", "#27272a", "#76ff03", "#3f3f46", "#ffffff"],
        natural_rgb: [(24, 24, 27), (39, 39, 42), (118, 255, 3), (63, 63, 70), (255, 255, 255)],
        description: "Melanistic black leopard with glossy obsidian coat and piercing fluorescent green eyes.",
        movement_lore: "Ghostly soundless muscular glide slipping like liquid night through tangled roots.",
    },
    MascotBiomeInfo {
        name: "rhino",
        category: "Wild & Safari",
        biome_name: "African Bushveld Scrub",
        environment: "savanna",
        road: "savanna",
        mountain: "plateau",
        natural_palette: ["#78909c", "#546e7a", "#cfd8dc", "#8d6e63", "#263238"],
        natural_rgb: [(120, 144, 156), (84, 110, 122), (207, 216, 220), (141, 110, 99), (38, 50, 56)],
        description: "White rhinoceros with thick plate-like armored hide and prehistoric keratin horn.",
        movement_lore: "Heavy bulldozer charge carving through dense savanna acacia thornbush.",
    },
    MascotBiomeInfo {
        name: "sloth",
        category: "Wild & Safari",
        biome_name: "Amazonian Cloud Forest",
        environment: "forest",
        road: "dirt",
        mountain: "peaks",
        natural_palette: ["#6d6854", "#e0d7c6", "#3e2723", "#8d6e63", "#2e7d32"],
        natural_rgb: [(109, 104, 84), (224, 215, 198), (62, 39, 35), (141, 110, 99), (46, 125, 50)],
        description: "Three-toed sloth covered in symbiotic green algae hanging inverted from high branches.",
        movement_lore: "Ultra-slow harmonic pendulum suspension celebrating the joy of unhurried life.",
    },
    MascotBiomeInfo {
        name: "telebears",
        category: "Wild & Safari",
        biome_name: "Broadcast Antenna Peak",
        environment: "cyber",
        road: "grid",
        mountain: "skyline",
        natural_palette: ["#3b82f6", "#60a5fa", "#ffffff", "#ffd54f", "#1d4ed8"],
        natural_rgb: [(59, 130, 246), (96, 165, 250), (255, 255, 255), (255, 213, 79), (29, 78, 216)],
        description: "High-tech broadcast bear transmitting telemetry packets across microwave relay stations.",
        movement_lore: "Synchronized digital step pulsing with RF signal wavefronts.",
    },
    MascotBiomeInfo {
        name: "tiger",
        category: "Wild & Safari",
        biome_name: "Sundarbans Mangrove Wilderness",
        environment: "savanna",
        road: "savanna",
        mountain: "peaks",
        natural_palette: ["#e65100", "#212121", "#fff8e1", "#ff8a80", "#ff9800"],
        natural_rgb: [(230, 81, 0), (33, 33, 33), (255, 248, 225), (255, 138, 128), (255, 152, 0)],
        description: "Bengal tiger with incandescent fiery orange coat, bold onyx stripes, and cream bib.",
        movement_lore: "Fluid rhythmic prowl with lethal coiled muscle spring ready at every stride.",
    },
    MascotBiomeInfo {
        name: "wolf",
        category: "Wild & Safari",
        biome_name: "Boreal Taiga Wilderness",
        environment: "forest",
        road: "dirt",
        mountain: "peaks",
        natural_palette: ["#78909c", "#37474f", "#eceff1", "#ffb300", "#263238"],
        natural_rgb: [(120, 144, 156), (55, 71, 79), (236, 239, 241), (255, 179, 0), (38, 50, 56)],
        description: "Timber wolf with silver-grey guard hairs, slate shadow saddle, and piercing amber stare.",
        movement_lore: "Enduring long-distance lope keeping rhythmic pace with the pack under the northern stars.",
    },
    MascotBiomeInfo {
        name: "bud-frogs",
        category: "Oceanic & Amphibian",
        biome_name: "Lily Pad Pond & Marshland",
        environment: "swamp",
        road: "mud",
        mountain: "hills",
        natural_palette: ["#2e7d32", "#4caf50", "#fbc02d", "#5d4037", "#ffd600"],
        natural_rgb: [(46, 125, 50), (76, 175, 80), (251, 192, 45), (93, 64, 55), (255, 214, 0)],
        description: "Tree frogs perched on dewy floating lily pads in singing chorus.",
        movement_lore: "Elastic spring-loaded frog leaps punctuated by throat sac vocalization pulses.",
    },
    MascotBiomeInfo {
        name: "docker-whale",
        category: "Oceanic & Amphibian",
        biome_name: "High Seas Container Terminal",
        environment: "ocean",
        road: "seabed",
        mountain: "seamount",
        natural_palette: ["#0288d1", "#29b6f6", "#ffffff", "#01579b", "#4fc3f7"],
        natural_rgb: [(2, 136, 209), (41, 182, 246), (255, 255, 255), (1, 87, 155), (79, 195, 247)],
        description: "Beloved container mascot whale ferrying reliable application containers across the ocean.",
        movement_lore: "Steady buoyant maritime cruise effortlessly carrying modular freight above the waves.",
    },
    MascotBiomeInfo {
        name: "dolphin",
        category: "Oceanic & Amphibian",
        biome_name: "Sunlit Coastal Waves",
        environment: "ocean",
        road: "seabed",
        mountain: "seamount",
        natural_palette: ["#546e7a", "#78909c", "#eceff1", "#0288d1", "#263238"],
        natural_rgb: [(84, 110, 122), (120, 144, 156), (236, 239, 241), (2, 136, 209), (38, 50, 56)],
        description: "Bottlenose dolphin with two-tone oceanic steel-blue skin and pristine white belly.",
        movement_lore: "Aerodynamic porpoising leap surfing the bow waves with acrobatic barrel rolls.",
    },
    MascotBiomeInfo {
        name: "duck",
        category: "Oceanic & Amphibian",
        biome_name: "Reed-Bordered Freshwater Pond",
        environment: "swamp",
        road: "mud",
        mountain: "hills",
        natural_palette: ["#1b5e20", "#795548", "#b0bec5", "#fbc02d", "#ff6f00"],
        natural_rgb: [(27, 94, 32), (121, 85, 72), (176, 190, 197), (251, 192, 45), (255, 111, 0)],
        description: "Wild mallard drake with iridescent bottle-green head, chestnut breast, and bright yellow bill.",
        movement_lore: "Cheerful paddle-stroke glide across calm waters dipping head for aquatic greens.",
    },
    MascotBiomeInfo {
        name: "ebi_furai",
        category: "Oceanic & Amphibian",
        biome_name: "Tokyo Seaside Bistro",
        environment: "city",
        road: "sidewalk",
        mountain: "skyline",
        natural_palette: ["#d97706", "#b45309", "#ffffff", "#ef4444", "#fef3c7"],
        natural_rgb: [(217, 119, 6), (180, 83, 9), (255, 255, 255), (239, 68, 68), (254, 243, 199)],
        description: "Crispy golden-brown deep-fried tiger prawn with crunchy panko coating and ruby tail.",
        movement_lore: "Crispy sizzling hop straight out of the hot sesame oil tempura wok.",
    },
    MascotBiomeInfo {
        name: "happy-whale",
        category: "Oceanic & Amphibian",
        biome_name: "Tropical Lagoon Sanctuary",
        environment: "ocean",
        road: "seabed",
        mountain: "seamount",
        natural_palette: ["#039be5", "#4fc3f7", "#e1f5fe", "#ffffff", "#0277bd"],
        natural_rgb: [(3, 155, 229), (79, 195, 247), (225, 245, 254), (255, 255, 255), (2, 119, 189)],
        description: "Playful jovial humpback whale singing oceanic symphonies and breaching into rainbows.",
        movement_lore: "Joyful rolling breach with massive tail fluke slap showering ocean spray.",
    },
    MascotBiomeInfo {
        name: "jellyfish",
        category: "Oceanic & Amphibian",
        biome_name: "Bioluminescent Pelagic Drift",
        environment: "ocean",
        road: "seabed",
        mountain: "seamount",
        natural_palette: ["#ba68c8", "#ce93d8", "#80d8ff", "#e1f5fe", "#e040fb"],
        natural_rgb: [(186, 104, 200), (206, 147, 216), (128, 216, 255), (225, 245, 254), (224, 64, 251)],
        description: "Translucent moon jellyfish pulsating with ethereal lilac and aqua bioluminescence.",
        movement_lore: "Hypnotic radial bell contraction drifting peacefully along deep marine currents.",
    },
    MascotBiomeInfo {
        name: "octopus",
        category: "Oceanic & Amphibian",
        biome_name: "Coral Reef Maze & Grotto",
        environment: "ocean",
        road: "seabed",
        mountain: "seamount",
        natural_palette: ["#ad1457", "#e1bee7", "#c2185b", "#ffd54f", "#4a148c"],
        natural_rgb: [(173, 20, 87), (225, 190, 231), (194, 24, 91), (255, 213, 79), (74, 20, 140)],
        description: "Intelligent coral octopus shifting chromatic camouflage with dexterous suction arms.",
        movement_lore: "Sinusoidal multi-arm crawl exploring crevices and jet-propelling across coral walls.",
    },
    MascotBiomeInfo {
        name: "pufferfish",
        category: "Oceanic & Amphibian",
        biome_name: "Sunlit Barrier Reef Lagoon",
        environment: "ocean",
        road: "seabed",
        mountain: "seamount",
        natural_palette: ["#fbc02d", "#5d4037", "#fff9c4", "#2e7d32", "#ffeb3b"],
        natural_rgb: [(251, 192, 45), (93, 64, 55), (255, 249, 196), (46, 125, 50), (255, 235, 59)],
        description: "Spiny porcupinefish armed with protective sharp quills and swollen buoyant body.",
        movement_lore: "Careful pectoral fin flutter ready to inflate into a prickly defensive sphere.",
    },
    MascotBiomeInfo {
        name: "seahorse",
        category: "Oceanic & Amphibian",
        biome_name: "Undulating Seagrass Meadow",
        environment: "ocean",
        road: "seabed",
        mountain: "seamount",
        natural_palette: ["#ff8f00", "#f06292", "#ffa000", "#ffd54f", "#e65100"],
        natural_rgb: [(255, 143, 0), (240, 98, 146), (255, 160, 0), (255, 213, 79), (230, 81, 0)],
        description: "Slender seahorse with crowned coronet and prehensile tail anchored to marine eelgrass.",
        movement_lore: "Upright vertical flutter powered by miniature transparent dorsal fin oscillations.",
    },
    MascotBiomeInfo {
        name: "squid",
        category: "Oceanic & Amphibian",
        biome_name: "Midnight Bathypelagic Abyss",
        environment: "ocean",
        road: "seabed",
        mountain: "seamount",
        natural_palette: ["#b71c1c", "#ff80ab", "#0284c7", "#ffd54f", "#311b92"],
        natural_rgb: [(183, 28, 28), (255, 128, 171), (2, 132, 199), (255, 213, 79), (49, 27, 146)],
        description: "Giant squid roaming total oceanic darkness with huge dinner-plate eyes and hunting tentacles.",
        movement_lore: "Swift backward jet-propulsion leaving glowing clouds of bioluminescent pseudomorph ink.",
    },
    MascotBiomeInfo {
        name: "turtle",
        category: "Oceanic & Amphibian",
        biome_name: "Pacific Coral Atoll",
        environment: "ocean",
        road: "seabed",
        mountain: "seamount",
        natural_palette: ["#33691e", "#fbc02d", "#558b2f", "#fff9c4", "#2e7d32"],
        natural_rgb: [(51, 105, 30), (251, 192, 45), (85, 139, 47), (255, 249, 196), (46, 125, 50)],
        description: "Ancient green sea turtle with mosaic olive scutes gliding through crystal warm waters.",
        movement_lore: "Majestic underwater wing-stroke flight migrating across vast ocean basins.",
    },
    MascotBiomeInfo {
        name: "walrus",
        category: "Oceanic & Amphibian",
        biome_name: "Arctic Pack Ice & Floes",
        environment: "arctic",
        road: "ice",
        mountain: "iceberg",
        natural_palette: ["#6d4c41", "#fffde7", "#8d6e63", "#a1887f", "#3e2723"],
        natural_rgb: [(109, 76, 65), (255, 253, 231), (141, 110, 99), (161, 136, 127), (62, 39, 35)],
        description: "Pacific walrus with thick cinnamon blubber, bristly whisker pads, and long ivory tusks.",
        movement_lore: "Heaving front flipper haul hauling massive blubbery frame onto floating ice floes.",
    },
    MascotBiomeInfo {
        name: "whale",
        category: "Oceanic & Amphibian",
        biome_name: "Abyssal Pelagic Trench",
        environment: "ocean",
        road: "seabed",
        mountain: "seamount",
        natural_palette: ["#1565c0", "#0d47a1", "#b0bec5", "#ffffff", "#002171"],
        natural_rgb: [(21, 101, 192), (13, 71, 161), (176, 190, 197), (255, 255, 255), (0, 33, 113)],
        description: "Colossal blue whale, the largest creature on Earth, singing low-frequency ocean pulses.",
        movement_lore: "Grand panoramic glide sweeping open baleen plates through dense swarms of krill.",
    },
    MascotBiomeInfo {
        name: "atat",
        category: "Fantasy & Sci-Fi",
        biome_name: "Frozen Hoth Ice Plains",
        environment: "arctic",
        road: "ice",
        mountain: "iceberg",
        natural_palette: ["#90a4ae", "#546e7a", "#cfd8dc", "#ff1744", "#263238"],
        natural_rgb: [(144, 164, 174), (84, 110, 122), (207, 216, 220), (255, 23, 68), (38, 50, 56)],
        description: "All Terrain Armored Transport towering over snowdrifts with heavy chin laser turrets.",
        movement_lore: "Relentless mechanical stomping strides shaking the permafrost with every step.",
    },
    MascotBiomeInfo {
        name: "cthulhu-mini",
        category: "Fantasy & Sci-Fi",
        biome_name: "Sunken City of R'lyeh",
        environment: "ocean",
        road: "seabed",
        mountain: "seamount",
        natural_palette: ["#1b5e20", "#6a1b9a", "#ffd600", "#004d40", "#311b92"],
        natural_rgb: [(27, 94, 32), (106, 27, 154), (255, 214, 0), (0, 77, 64), (49, 27, 146)],
        description: "Chibi slumbering Great Old One with writhing face tentacles and eldritch leathery wings.",
        movement_lore: "Unfathomable non-Euclidean cosmic drift that bends the sanity of mortal onlookers.",
    },
    MascotBiomeInfo {
        name: "daemon",
        category: "Fantasy & Sci-Fi",
        biome_name: "Nether Flame Caldera",
        environment: "inferno",
        road: "magma",
        mountain: "volcano",
        natural_palette: ["#d32f2f", "#212121", "#ffffff", "#ffd600", "#b71c1c"],
        natural_rgb: [(211, 47, 47), (33, 33, 33), (255, 255, 255), (255, 214, 0), (183, 28, 28)],
        description: "BSD Daemon Beastie bearing legendary pitchfork and cheerful mischievous demon horns.",
        movement_lore: "Nimble fiery hovering hop keeping POSIX network pipes running at maximum speed.",
    },
    MascotBiomeInfo {
        name: "dragon",
        category: "Fantasy & Sci-Fi",
        biome_name: "Volcanic Magma Chamber",
        environment: "inferno",
        road: "magma",
        mountain: "volcano",
        natural_palette: ["#b71c1c", "#ff6f00", "#212121", "#ffd600", "#7f0000"],
        natural_rgb: [(183, 28, 28), (255, 111, 0), (33, 33, 33), (255, 214, 0), (127, 0, 0)],
        description: "Ancient European fire drake with impenetrable ruby scales and smoldering belly furnaces.",
        movement_lore: "Tremendous rhythmic thoracic expansion breathing searing columns of incinerating flame.",
    },
    MascotBiomeInfo {
        name: "dragon-and-cow",
        category: "Fantasy & Sci-Fi",
        biome_name: "Smoldering Wyrm Lair",
        environment: "inferno",
        road: "magma",
        mountain: "volcano",
        natural_palette: ["#c62828", "#ff8f00", "#ffffff", "#ff1744", "#212121"],
        natural_rgb: [(198, 40, 40), (255, 143, 0), (255, 255, 255), (255, 23, 68), (33, 33, 33)],
        description: "Legendary hybrid encounter: an ancient fire dragon conferring with an unbothered bovine.",
        movement_lore: "Duet of rhythmic dragon flame breathing countered by calm cow chewing.",
    },
    MascotBiomeInfo {
        name: "ghost",
        category: "Fantasy & Sci-Fi",
        biome_name: "Haunted Victorian Graveyard",
        environment: "graveyard",
        road: "crypt",
        mountain: "gothic",
        natural_palette: ["#e0f7fa", "#80deea", "#b2ebf2", "#00e5ff", "#004d40"],
        natural_rgb: [(224, 247, 250), (128, 222, 234), (178, 235, 242), (0, 229, 255), (0, 77, 64)],
        description: "Spooky translucent spectral apparition floating weightlessly above ancient mossy headstones.",
        movement_lore: "Ethereal vertical bobbing and wispy horizontal drift through solid obstacles.",
    },
    MascotBiomeInfo {
        name: "ghostbusters",
        category: "Fantasy & Sci-Fi",
        biome_name: "Paranormal New York Street",
        environment: "city",
        road: "sidewalk",
        mountain: "skyline",
        natural_palette: ["#e53935", "#ffffff", "#212121", "#ffd600", "#00e5ff"],
        natural_rgb: [(229, 57, 53), (255, 255, 255), (33, 33, 33), (255, 214, 0), (0, 229, 255)],
        description: "Iconic no-ghost caution insignia warning paranormal entities across Manhattan.",
        movement_lore: "Urgent siren pulse and particle-beam oscillation capturing rogue ectoplasm.",
    },
    MascotBiomeInfo {
        name: "glados",
        category: "Fantasy & Sci-Fi",
        biome_name: "Aperture Science Enrichment Center",
        environment: "cyber",
        road: "grid",
        mountain: "skyline",
        natural_palette: ["#f5f5f5", "#212121", "#ffab00", "#00b0ff", "#ff1744"],
        natural_rgb: [(245, 245, 245), (33, 33, 33), (255, 171, 0), (0, 176, 255), (255, 23, 68)],
        description: "Aperture Science Genetic Lifeform and Disk Operating System observing human testing.",
        movement_lore: "Mechanical ceiling-mounted pendulum sway focusing optical amber sensor on the subject.",
    },
    MascotBiomeInfo {
        name: "mech-and-cow",
        category: "Fantasy & Sci-Fi",
        biome_name: "Orbital Mecha Hangar",
        environment: "cyber",
        road: "grid",
        mountain: "skyline",
        natural_palette: ["#0284c7", "#e0f2fe", "#ffffff", "#f59e0b", "#0369a1"],
        natural_rgb: [(2, 132, 199), (224, 242, 254), (255, 255, 255), (245, 158, 11), (3, 105, 161)],
        description: "Heavy bipedal robotic combat exoskeleton piloted by a decorated bovine commander.",
        movement_lore: "Hydraulic reinforced servo steps with roaring attitude-thruster micro-burns.",
    },
    MascotBiomeInfo {
        name: "minotaur",
        category: "Fantasy & Sci-Fi",
        biome_name: "Underground Knossos Labyrinth",
        environment: "inferno",
        road: "magma",
        mountain: "volcano",
        natural_palette: ["#4e342e", "#e0e0e0", "#b71c1c", "#ffd700", "#212121"],
        natural_rgb: [(78, 52, 46), (224, 224, 224), (183, 28, 28), (255, 215, 0), (33, 33, 33)],
        description: "Fearsome bull-headed monster haunting labyrinth corridors with brass septum ring.",
        movement_lore: "Thundering aggressive patrol echoing through dark stone subterranean passages.",
    },
    MascotBiomeInfo {
        name: "mooghidjirah",
        category: "Fantasy & Sci-Fi",
        biome_name: "Cosmic Kaiju Nebula",
        environment: "inferno",
        road: "magma",
        mountain: "volcano",
        natural_palette: ["#ffd700", "#c62828", "#ff6f00", "#ad1457", "#212121"],
        natural_rgb: [(255, 215, 0), (198, 40, 40), (255, 111, 0), (173, 20, 87), (33, 33, 33)],
        description: "Three-headed Golden King Kaiju dragon raining lightning upon scorched planetary terrain.",
        movement_lore: "Triple-headed undulating serpentine thrash generating hurricane-force sonic gale winds.",
    },
    MascotBiomeInfo {
        name: "moojira",
        category: "Fantasy & Sci-Fi",
        biome_name: "Atomic Trench & Seafront",
        environment: "inferno",
        road: "magma",
        mountain: "volcano",
        natural_palette: ["#1b5e20", "#00e5ff", "#2e7d32", "#ff1744", "#212121"],
        natural_rgb: [(27, 94, 32), (0, 229, 255), (46, 125, 50), (255, 23, 68), (33, 33, 33)],
        description: "King of the Monsters bovine irradiated by atomic energy charging cyan dorsal spine spikes.",
        movement_lore: "Colossal tectonic march radiating nuclear heat and devastating atomic breath.",
    },
    MascotBiomeInfo {
        name: "pterodactyl",
        category: "Fantasy & Sci-Fi",
        biome_name: "Prehistoric Caldera Crags",
        environment: "jurassic",
        road: "tracks",
        mountain: "volcano",
        natural_palette: ["#b23b23", "#8d6e63", "#d7ccc8", "#ffb300", "#4e342e"],
        natural_rgb: [(178, 59, 35), (141, 110, 99), (215, 204, 200), (255, 179, 0), (78, 52, 46)],
        description: "Prehistoric pterosaur soaring on wide terracotta wing membranes over primeval cycads.",
        movement_lore: "Majestic updraft thermal banking glide with sharp predatory talons poised.",
    },
    MascotBiomeInfo {
        name: "sauron",
        category: "Fantasy & Sci-Fi",
        biome_name: "Mount Doom Barad-dûr Spire",
        environment: "inferno",
        road: "magma",
        mountain: "volcano",
        natural_palette: ["#1a1a1a", "#ff1744", "#ff6d00", "#424242", "#ffea00"],
        natural_rgb: [(26, 26, 26), (255, 23, 68), (255, 109, 0), (66, 66, 66), (255, 234, 0)],
        description: "The Dark Lord of Mordor manifesting as the Great Lidless Eye rimmed in incandescent fire.",
        movement_lore: "Ominous pulsing focal glare sweeping across volcanic ash plains seeking the One Ring.",
    },
    MascotBiomeInfo {
        name: "stegosaurus",
        category: "Fantasy & Sci-Fi",
        biome_name: "Jurassic Primeval Rainforest",
        environment: "jurassic",
        road: "tracks",
        mountain: "volcano",
        natural_palette: ["#2e7d32", "#d84315", "#558b2f", "#8d6e63", "#ffb300"],
        natural_rgb: [(46, 125, 50), (216, 67, 21), (85, 139, 47), (141, 110, 99), (255, 179, 0)],
        description: "Armored herbivore with dual rows of vascular thermoregulatory back plates and tail spikes.",
        movement_lore: "Heavy quadrupedal stride swinging spiked thagomizer in defensive sweeping arcs.",
    },
    MascotBiomeInfo {
        name: "unipony",
        category: "Fantasy & Sci-Fi",
        biome_name: "Enchanted Fairyland Glade",
        environment: "pasture",
        road: "cobblestone",
        mountain: "castle",
        natural_palette: ["#ffffff", "#38bdf8", "#e879f9", "#ffd700", "#ff80ab"],
        natural_rgb: [(255, 255, 255), (56, 189, 248), (232, 121, 249), (255, 215, 0), (255, 128, 171)],
        description: "Magical winged alicorn with spiral pearl horn, pastel mane, and sparkling stardust hooves.",
        movement_lore: "Weightless graceful canter sprinkling glitter trails and sparkling rainbow magic.",
    },
    MascotBiomeInfo {
        name: "vader",
        category: "Fantasy & Sci-Fi",
        biome_name: "Death Star Overlook & Trench",
        environment: "space",
        road: "grid",
        mountain: "skyline",
        natural_palette: ["#121212", "#212121", "#d50000", "#2979ff", "#757575"],
        natural_rgb: [(18, 18, 18), (33, 33, 33), (213, 0, 0), (41, 121, 255), (117, 117, 117)],
        description: "Sith Lord Darth Vader in obsidian battle armor with crimson lightsaber glow and respirator.",
        movement_lore: "Slow intimidating march backed by the mechanical hiss of synthetic respiratory chambers.",
    },
    MascotBiomeInfo {
        name: "wizard",
        category: "Fantasy & Sci-Fi",
        biome_name: "Arcane Spire Observatory",
        environment: "throne",
        road: "checkerboard",
        mountain: "castle",
        natural_palette: ["#1a237e", "#aa00ff", "#e0e0e0", "#ffd700", "#00e5ff"],
        natural_rgb: [(26, 35, 126), (170, 0, 255), (224, 224, 224), (255, 215, 0), (0, 229, 255)],
        description: "Ancient archmage clad in midnight indigo robe with silver beard channeling raw arcane ether.",
        movement_lore: "Harmonic arcane levitation charging runic glyphs and mystic lightning pulses.",
    },
    MascotBiomeInfo {
        name: "yoda",
        category: "Fantasy & Sci-Fi",
        biome_name: "Dagobah Foggy Bayou",
        environment: "swamp",
        road: "mud",
        mountain: "hills",
        natural_palette: ["#558b2f", "#d7ccc8", "#bcaaa4", "#8bc34a", "#33691e"],
        natural_rgb: [(85, 139, 47), (215, 204, 200), (188, 170, 164), (139, 195, 74), (51, 105, 30)],
        description: "Grand Master of the Jedi Order meditating in mossy swamp hut among twisted cypress roots.",
        movement_lore: "Slow walking-cane shuffle interchanged with weightless Force-assisted meditation floats.",
    },
    MascotBiomeInfo {
        name: "beavis.zen",
        category: "Pop Culture & Fun",
        biome_name: "Suburban Living Room Couch",
        environment: "city",
        road: "sidewalk",
        mountain: "skyline",
        natural_palette: ["#fbc02d", "#1976d2", "#ffcc80", "#e53935", "#37474f"],
        natural_rgb: [(251, 192, 45), (25, 118, 210), (255, 204, 128), (229, 57, 53), (55, 71, 79)],
        description: "Blond 90s rocker in iconic Metallica blue shirt rocking out to heavy metal guitar solos.",
        movement_lore: "Spastic energetic headbanging frenzy punctuated by comedic hand gestures.",
    },
    MascotBiomeInfo {
        name: "bill-the-cat",
        category: "Pop Culture & Fun",
        biome_name: "Back-Alley Dumpster Sanctuary",
        environment: "city",
        road: "sidewalk",
        mountain: "skyline",
        natural_palette: ["#e67e22", "#f39c12", "#ff80ab", "#ffeb3b", "#d32f2f"],
        natural_rgb: [(230, 126, 34), (243, 156, 18), (255, 128, 171), (255, 235, 59), (211, 47, 47)],
        description: "Beloved scruffy mangy ginger cat with mismatched googly eyes and iconic tongue hang.",
        movement_lore: "Unpredictable twitchy hitch-step with comical eye-rolling and gasping expressions.",
    },
    MascotBiomeInfo {
        name: "charizardvice",
        category: "Pop Culture & Fun",
        biome_name: "Volcanic Battle Stadium",
        environment: "inferno",
        road: "magma",
        mountain: "volcano",
        natural_palette: ["#ff6f00", "#fff8e1", "#00b0ff", "#2e7d32", "#ff1744"],
        natural_rgb: [(255, 111, 0), (255, 248, 225), (0, 176, 255), (46, 125, 50), (255, 23, 68)],
        description: "Iconic flame-tailed fire dragon roaring with blazing tail ember and turquoise wing membranes.",
        movement_lore: "Intense battle-ready breath pulse unleashing soaring plumes of blue and gold fire.",
    },
    MascotBiomeInfo {
        name: "fat-banana",
        category: "Pop Culture & Fun",
        biome_name: "Tropical Fruit Canopy",
        environment: "pasture",
        road: "dirt",
        mountain: "garden",
        natural_palette: ["#ffd600", "#ffea00", "#5d4037", "#64dd17", "#fff9c4"],
        natural_rgb: [(255, 214, 0), (255, 234, 0), (93, 64, 55), (100, 221, 23), (255, 249, 196)],
        description: "Plump sun-ripened Cavendish banana with sweet sugar freckles and fresh green stem.",
        movement_lore: "Joyful rhythmic dancing wiggle swaying to irresistible calypso island rhythms.",
    },
    MascotBiomeInfo {
        name: "flaming-sheep",
        category: "Pop Culture & Fun",
        biome_name: "Volcanic Ash Grazing Hill",
        environment: "inferno",
        road: "magma",
        mountain: "volcano",
        natural_palette: ["#ff5722", "#ff9800", "#ffeb3b", "#3e2723", "#b71c1c"],
        natural_rgb: [(255, 87, 34), (255, 152, 0), (255, 235, 59), (62, 39, 35), (183, 28, 28)],
        description: "Combustible sheep burning with glorious incandescent flame wool yet grazing peacefully.",
        movement_lore: "Blazing fast galloping sprint leaving a glowing trail of burning embers.",
    },
    MascotBiomeInfo {
        name: "golden-eagle",
        category: "Pop Culture & Fun",
        biome_name: "High Mountain Thermal Updraft",
        environment: "pasture",
        road: "dirt",
        mountain: "peaks",
        natural_palette: ["#3e2723", "#ffb300", "#4e342e", "#fbc02d", "#212121"],
        natural_rgb: [(62, 39, 35), (255, 179, 0), (78, 52, 46), (251, 192, 45), (33, 33, 33)],
        description: "Majestic raptor soaring with dark brown wing plumage, golden crown, and keen yellow talons.",
        movement_lore: "Effortless wide-span soaring glide circling alpine crests with laser-focus vision.",
    },
    MascotBiomeInfo {
        name: "hellokitty",
        category: "Pop Culture & Fun",
        biome_name: "Pastel Shibuya Plaza",
        environment: "city",
        road: "sidewalk",
        mountain: "skyline",
        natural_palette: ["#ffffff", "#d50000", "#ffd600", "#1a1a1a", "#f8bbd0"],
        natural_rgb: [(255, 255, 255), (213, 0, 0), (255, 214, 0), (26, 26, 26), (248, 187, 208)],
        description: "Universal icon of kindness and friendship with pure white fur and trademark crimson bow.",
        movement_lore: "Delicate sweet rhythmic parade step spreading cheer across the bustling boulevard.",
    },
    MascotBiomeInfo {
        name: "hypno",
        category: "Pop Culture & Fun",
        biome_name: "Kaleidoscopic Dimension",
        environment: "cyber",
        road: "grid",
        mountain: "crater",
        natural_palette: ["#000000", "#ffffff", "#e040fb", "#00e5ff", "#76ff03"],
        natural_rgb: [(0, 0, 0), (255, 255, 255), (224, 64, 251), (0, 229, 255), (118, 255, 3)],
        description: "Mesmerizing mind-altering concentric swirl altering perception through psychic resonance.",
        movement_lore: "Continuous rotational vortex spiral mesmerizing the viewer into deep relaxation.",
    },
    MascotBiomeInfo {
        name: "kiss",
        category: "Pop Culture & Fun",
        biome_name: "Rock Arena World Tour Stage",
        environment: "city",
        road: "sidewalk",
        mountain: "skyline",
        natural_palette: ["#ffffff", "#000000", "#d50000", "#424242", "#757575"],
        natural_rgb: [(255, 255, 255), (0, 0, 0), (213, 0, 0), (66, 66, 66), (117, 117, 117)],
        description: "Glam rock demon icon with stark white face paint, star eye design, and tongue extension.",
        movement_lore: "Theatrical arena stomping stride with fire-breathing bass guitar riffs.",
    },
    MascotBiomeInfo {
        name: "mona-lisa",
        category: "Pop Culture & Fun",
        biome_name: "Renaissance Louvre Gallery",
        environment: "throne",
        road: "checkerboard",
        mountain: "castle",
        natural_palette: ["#4a3b32", "#e8d5c4", "#6b5b45", "#ffd700", "#1f1b18"],
        natural_rgb: [(74, 59, 50), (232, 213, 196), (107, 91, 69), (255, 215, 0), (31, 27, 24)],
        description: "Da Vinci's immortal Renaissance masterpiece with subtle sfumato shading and enigmatic smile.",
        movement_lore: "Poised immortal stillness with soft thoracic breathing that follows you across the room.",
    },
    MascotBiomeInfo {
        name: "nyan",
        category: "Pop Culture & Fun",
        biome_name: "Cosmic Rainbow Void",
        environment: "space",
        road: "grid",
        mountain: "crater",
        natural_palette: ["#e6aa68", "#ff69b4", "#90a4ae", "#ff1493", "#00e5ff"],
        natural_rgb: [(230, 170, 104), (255, 105, 180), (144, 164, 174), (255, 20, 147), (0, 229, 255)],
        description: "Interstellar pop-tart feline rocketing through cosmos leaving an eternal rainbow ribbon.",
        movement_lore: "Supersonic warp dash looping through constellations to upbeat chiptune cadence.",
    },
    MascotBiomeInfo {
        name: "radioactive-kitty",
        category: "Pop Culture & Fun",
        biome_name: "Chernobyl Glowing Reactor Core",
        environment: "cyber",
        road: "grid",
        mountain: "crater",
        natural_palette: ["#76ff03", "#212121", "#c6ff00", "#00e676", "#ffff00"],
        natural_rgb: [(118, 255, 3), (33, 33, 33), (198, 255, 0), (0, 230, 118), (255, 255, 0)],
        description: "Mutant feline glowing with radioactive chartreuse luminescence and trefoil hazard stripes.",
        movement_lore: "Twitchy glitch-step flickering between reality states with electric ion arcs.",
    },
    MascotBiomeInfo {
        name: "ren",
        category: "Pop Culture & Fun",
        biome_name: "Hollywood Boulevard Alley",
        environment: "city",
        road: "sidewalk",
        mountain: "skyline",
        natural_palette: ["#d7ccc8", "#ffab91", "#d50000", "#ff8a80", "#3e2723"],
        natural_rgb: [(215, 204, 200), (255, 171, 145), (213, 0, 0), (255, 138, 128), (62, 39, 35)],
        description: "High-strung asthmatic Chihuahua trembling with nervous energy and bloodshot bulging eyes.",
        movement_lore: "Frantic trembling vibration and sudden explosive exasperated pacing.",
    },
    MascotBiomeInfo {
        name: "snoopy",
        category: "Pop Culture & Fun",
        biome_name: "Suburban Red Doghouse Lawn",
        environment: "city",
        road: "sidewalk",
        mountain: "skyline",
        natural_palette: ["#ffffff", "#1a1a1a", "#d32f2f", "#424242", "#e0e0e0"],
        natural_rgb: [(255, 255, 255), (26, 26, 26), (211, 47, 47), (66, 66, 66), (224, 224, 224)],
        description: "Beloved beagle with jet-black ears, cherry-red collar, and boundless imaginative dreams.",
        movement_lore: "Exuberant high-stepping happy dance celebrating friendships and fresh supper bowls.",
    },
    MascotBiomeInfo {
        name: "stimpy",
        category: "Pop Culture & Fun",
        biome_name: "Cartoon Kitchen Floor",
        environment: "city",
        road: "sidewalk",
        mountain: "skyline",
        natural_palette: ["#e64a19", "#fff3e0", "#1976d2", "#fbe9e7", "#ffb300"],
        natural_rgb: [(230, 74, 25), (255, 243, 224), (25, 118, 210), (251, 233, 231), (255, 179, 0)],
        description: "Good-natured rotund Manx cat with warm orange coat and prominent bulbous blue nose.",
        movement_lore: "Joyful bouncy waddle humming cheerful nonsensical tunes with blissful optimism.",
    },
    MascotBiomeInfo {
        name: "tux",
        category: "Pop Culture & Fun",
        biome_name: "Antarctic Pack Ice & Open Leads",
        environment: "arctic",
        road: "ice",
        mountain: "iceberg",
        natural_palette: ["#1e1e1e", "#ffffff", "#ffa000", "#ffb300", "#212121"],
        natural_rgb: [(30, 30, 30), (255, 255, 255), (255, 160, 0), (255, 179, 0), (33, 33, 33)],
        description: "Official Linux penguin mascot with glossy black coat, snow-white belly, and golden webbed feet.",
        movement_lore: "Endearing charismatic waddle sliding on belly across slick polar ice fields.",
    },
    MascotBiomeInfo {
        name: "vulpix",
        category: "Pop Culture & Fun",
        biome_name: "Autumn Maple Forest Clearing",
        environment: "forest",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#d35400", "#ff9800", "#ffffff", "#e65100", "#5d4037"],
        natural_rgb: [(211, 84, 0), (255, 152, 0), (255, 255, 255), (230, 81, 0), (93, 64, 55)],
        description: "Fox Pokemon with six gorgeous curled amber tails and warm auburn winter coat.",
        movement_lore: "Nimble graceful trot fanning out flame-warmed tails in mesmerizing patterns.",
    },
    MascotBiomeInfo {
        name: "apt",
        category: "Abstract & Quirky",
        biome_name: "Debian Mainframe Data Center",
        environment: "cyber",
        road: "grid",
        mountain: "skyline",
        natural_palette: ["#e11d48", "#ffffff", "#be123c", "#212121", "#60a5fa"],
        natural_rgb: [(225, 29, 72), (255, 255, 255), (190, 18, 60), (33, 33, 33), (96, 165, 250)],
        description: "Debian Advanced Package Tool swirl representing stable Free Software distribution.",
        movement_lore: "Reliable algorithmic packet verification processing byte streams with clockwork precision.",
    },
    MascotBiomeInfo {
        name: "bees",
        category: "Abstract & Quirky",
        biome_name: "Sunlit Meadow Hive & Wildflowers",
        environment: "hive",
        road: "dirt",
        mountain: "garden",
        natural_palette: ["#ffb300", "#212121", "#b0bec5", "#ffe082", "#ffd54f"],
        natural_rgb: [(255, 179, 0), (33, 33, 33), (176, 190, 197), (255, 224, 130), (255, 213, 79)],
        description: "Busy honeybee colony with golden-amber and velvet black warning stripes collecting nectar.",
        movement_lore: "Fast figure-eight waggle dance communicating sweet flower locations to the hive.",
    },
    MascotBiomeInfo {
        name: "claw-arm",
        category: "Abstract & Quirky",
        biome_name: "Automated Industrial Foundry",
        environment: "cyber",
        road: "grid",
        mountain: "skyline",
        natural_palette: ["#90a4ae", "#37474f", "#ff9800", "#00e5ff", "#212121"],
        natural_rgb: [(144, 164, 174), (55, 71, 79), (255, 152, 0), (0, 229, 255), (33, 33, 33)],
        description: "Precision multi-axis cybernetic manipulator arm with chrome plating and warning strobe.",
        movement_lore: "Articulated multi-axis robotic extension calibrating micrometric grip tension.",
    },
    MascotBiomeInfo {
        name: "cower",
        category: "Abstract & Quirky",
        biome_name: "Highland Meadow Storm",
        environment: "pasture",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#8d6e63", "#ffffff", "#bcaaa4", "#3e2723", "#ffb6c1"],
        natural_rgb: [(141, 110, 99), (255, 255, 255), (188, 170, 164), (62, 39, 35), (255, 182, 193)],
        description: "Gentle young jersey calf trembling slightly under thunderclaps in the mountain meadow.",
        movement_lore: "Subtle cautious stepping seeking shelter beside friendly herd elders.",
    },
    MascotBiomeInfo {
        name: "cowfee",
        category: "Abstract & Quirky",
        biome_name: "Artisan Italian Espresso Bar",
        environment: "city",
        road: "sidewalk",
        mountain: "skyline",
        natural_palette: ["#3e2723", "#fff8e1", "#d4a373", "#6d4c41", "#ffb6c1"],
        natural_rgb: [(62, 39, 35), (255, 248, 225), (212, 163, 115), (109, 76, 65), (255, 182, 193)],
        description: "Barista cow serving rich double-shot espresso layered with steamed microfoam crema.",
        movement_lore: "Smooth rhythmic barista routine steaming milk and drawing delicate rosetta latte art.",
    },
    MascotBiomeInfo {
        name: "eyes",
        category: "Abstract & Quirky",
        biome_name: "Astral Observation Zenith",
        environment: "space",
        road: "grid",
        mountain: "crater",
        natural_palette: ["#ffffff", "#0288d1", "#000000", "#76ff03", "#9c27b0"],
        natural_rgb: [(255, 255, 255), (2, 136, 209), (0, 0, 0), (118, 255, 3), (156, 39, 176)],
        description: "Omniscient cosmic gaze witnessing the dance of distant galaxies across space-time.",
        movement_lore: "Synchronized panoramic eye dilation tracking stellar movements across the void.",
    },
    MascotBiomeInfo {
        name: "fence",
        category: "Abstract & Quirky",
        biome_name: "Ranch Boundary Paddock",
        environment: "pasture",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#795548", "#8d6e63", "#558b2f", "#3e2723", "#a1887f"],
        natural_rgb: [(121, 85, 72), (141, 110, 99), (85, 139, 47), (62, 39, 35), (161, 136, 127)],
        description: "Sturdy split-rail timber farm fence standing guard over open grazing ranges.",
        movement_lore: "Subtle harmonic swaying resisting seasonal prairie prairie winds.",
    },
    MascotBiomeInfo {
        name: "hiya",
        category: "Abstract & Quirky",
        biome_name: "Sunny Village Green",
        environment: "pasture",
        road: "dirt",
        mountain: "garden",
        natural_palette: ["#ffeb3b", "#ffffff", "#ff4081", "#e91e63", "#ff9800"],
        natural_rgb: [(255, 235, 59), (255, 255, 255), (255, 64, 129), (233, 30, 99), (255, 152, 0)],
        description: "Infectiously happy friendly face radiating warm welcoming greetings to all travelers.",
        movement_lore: "Enthusiastic rhythmic hand-waving and radiant smiling greeting pulses.",
    },
    MascotBiomeInfo {
        name: "jesus",
        category: "Abstract & Quirky",
        biome_name: "Sacred Mount Olive Overlook",
        environment: "throne",
        road: "cobblestone",
        mountain: "peaks",
        natural_palette: ["#fff8e1", "#b71c1c", "#ffd600", "#8d6e63", "#f5f5f5"],
        natural_rgb: [(255, 248, 225), (183, 28, 28), (255, 214, 0), (141, 110, 99), (245, 245, 245)],
        description: "Sacred shepherd icon clad in linen robe and scarlet mantle bearing divine golden halo.",
        movement_lore: "Peaceful blessing glide walking across waters and tranquil mountain paths.",
    },
    MascotBiomeInfo {
        name: "kosh",
        category: "Abstract & Quirky",
        biome_name: "Vorlon Sanctuary Chamber",
        environment: "space",
        road: "grid",
        mountain: "crater",
        natural_palette: ["#00897b", "#26a69a", "#ffd54f", "#004d40", "#80cbc4"],
        natural_rgb: [(0, 137, 123), (38, 166, 154), (255, 213, 79), (0, 77, 64), (128, 203, 196)],
        description: "Ambassador Kosh of the mysterious First Ones enclosed in bio-armored encounter suit.",
        movement_lore: "Majestic ponderous glide with bioluminescent suit petals pulsing cryptic messages.",
    },
    MascotBiomeInfo {
        name: "mutilated",
        category: "Abstract & Quirky",
        biome_name: "Nocturnal Crop Circle Field",
        environment: "space",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#76ff03", "#78909c", "#ff1744", "#212121", "#ffffff"],
        natural_rgb: [(118, 255, 3), (120, 144, 156), (255, 23, 68), (33, 33, 33), (255, 255, 255)],
        description: "Mysterious nighttime flying saucer encounter beaming pasture animals into the night sky.",
        movement_lore: "Vertical tractor-beam anti-gravity levitation with rotating saucer light rings.",
    },
    MascotBiomeInfo {
        name: "queen",
        category: "Abstract & Quirky",
        biome_name: "Imperial Throne Room Cathedral",
        environment: "throne",
        road: "checkerboard",
        mountain: "castle",
        natural_palette: ["#ffd700", "#880e4f", "#ffffff", "#1565c0", "#c62828"],
        natural_rgb: [(255, 215, 0), (136, 14, 79), (255, 255, 255), (21, 101, 192), (198, 40, 40)],
        description: "Reigning sovereign in ermine-trimmed royal crimson mantle and jewel-encrusted golden crown.",
        movement_lore: "Stately regal court procession with dignified royal waves and imperial poise.",
    },
    MascotBiomeInfo {
        name: "skeleton",
        category: "Abstract & Quirky",
        biome_name: "Ancient Crypt Mausoleum",
        environment: "graveyard",
        road: "crypt",
        mountain: "gothic",
        natural_palette: ["#f5f5f5", "#e0e0e0", "#212121", "#d7ccc8", "#9e9e9e"],
        natural_rgb: [(245, 245, 245), (224, 224, 224), (33, 33, 33), (215, 204, 200), (158, 158, 158)],
        description: "Clean articulated calcium skeleton dancing merrily under the midnight harvest moon.",
        movement_lore: "Clicky rhythmic bone-clattering tap dance echoing through ancient catacombs.",
    },
    MascotBiomeInfo {
        name: "small",
        category: "Abstract & Quirky",
        biome_name: "Spring Nursery Pasture",
        environment: "pasture",
        road: "dirt",
        mountain: "hills",
        natural_palette: ["#ffffff", "#262626", "#ffb6c1", "#424242", "#e0e0e0"],
        natural_rgb: [(255, 255, 255), (38, 38, 38), (255, 182, 193), (66, 66, 66), (224, 224, 224)],
        description: "Adorable miniature newborn calf taking its very first steps in the warming morning sun.",
        movement_lore: "Wobbly endearing baby steps discovering balance on four tiny hooves.",
    },
    MascotBiomeInfo {
        name: "supermilker",
        category: "Abstract & Quirky",
        biome_name: "Automated Cyber Dairy Parlor",
        environment: "cyber",
        road: "grid",
        mountain: "skyline",
        natural_palette: ["#90a4ae", "#0284c7", "#38bdf8", "#ffb6c1", "#ffffff"],
        natural_rgb: [(144, 164, 174), (2, 132, 199), (56, 189, 248), (255, 182, 193), (255, 255, 255)],
        description: "High-efficiency automated robotic milker optimizing dairy flow with gentle vacuum pulses.",
        movement_lore: "Precision cyclic pumping rhythm synchronizing with telemetry sensors.",
    },
    MascotBiomeInfo {
        name: "surgery",
        category: "Abstract & Quirky",
        biome_name: "Sterile Operating Theater",
        environment: "city",
        road: "sidewalk",
        mountain: "skyline",
        natural_palette: ["#cfd8dc", "#0284c7", "#ffffff", "#ef4444", "#263238"],
        natural_rgb: [(207, 216, 220), (2, 132, 199), (255, 255, 255), (239, 68, 68), (38, 50, 56)],
        description: "Advanced surgical suite with sterile titanium instruments and vital monitoring telemetry.",
        movement_lore: "Methodical precision micro-adjustments maintaining steady robotic surgical accuracy.",
    },
    MascotBiomeInfo {
        name: "three-eyes",
        category: "Abstract & Quirky",
        biome_name: "Toxic Wasteland Marsh",
        environment: "swamp",
        road: "mud",
        mountain: "crater",
        natural_palette: ["#2e7d32", "#76ff03", "#00e676", "#ffb6c1", "#1b5e20"],
        natural_rgb: [(46, 125, 50), (118, 255, 3), (0, 230, 118), (255, 182, 193), (27, 94, 32)],
        description: "Mutated triclops bovine thriving in glowing mossy bogs with an extra supernatural eye.",
        movement_lore: "Careful three-eyed stereoscopic scanning surveying 270 degrees of surrounding marsh.",
    },
    MascotBiomeInfo {
        name: "viper",
        category: "Abstract & Quirky",
        biome_name: "Mangrove Serpent Mire",
        environment: "swamp",
        road: "mud",
        mountain: "plateau",
        natural_palette: ["#2e7d32", "#84cc16", "#d84315", "#ffd600", "#1b5e20"],
        natural_rgb: [(46, 125, 50), (132, 204, 22), (216, 67, 21), (255, 214, 0), (27, 94, 32)],
        description: "Venomous pit viper with vivid diamond scales and coiled spring striking speed.",
        movement_lore: "Silent undulating lateral serpentine glide tasting the warm air with forked tongue.",
    },
];

/// Retrieve the comprehensive biological biome profile for any mascot.
pub fn get_mascot_biome(animal: &str) -> &'static MascotBiomeInfo {
    let clean = animal
        .strip_suffix(".cow")
        .unwrap_or(animal)
        .to_ascii_lowercase();
    for mascot in &ALL_MASCOTS {
        if mascot.name == clean {
            return mascot;
        }
    }
    // Aliases and fallbacks
    match clean.as_str() {
        "cow" | "cowsay" => &ALL_MASCOTS[0],
        "rabbit" => get_mascot_biome("bunny"),
        "beavis" => get_mascot_biome("beavis.zen"),
        "nyancat" | "nyan-cat" | "nyan_cat" => get_mascot_biome("nyan"),
        "shiba" | "shibu" | "shiba-inu" => get_mascot_biome("doge"),
        "kitten" | "kittens" => get_mascot_biome("cat"),
        _ => &ALL_MASCOTS[0], // Default cow
    }
}

/// Retrieve the recommended scenery triad (Environment, Road, Mountain) for any mascot.
pub fn get_recommended_scenery(animal: &str) -> (&'static str, &'static str, &'static str) {
    let info = get_mascot_biome(animal);
    (info.environment, info.road, info.mountain)
}

/// Retrieve the authentic natural hex palette (5 colors) for any mascot.
pub fn get_natural_hex_palette(animal: &str) -> &'static [&'static str] {
    &get_mascot_biome(animal).natural_palette
}

/// Retrieve the authentic natural RGB palette (5 colors) for any mascot.
pub fn get_natural_rgb_palette(animal: &str) -> &'static [(u8, u8, u8)] {
    &get_mascot_biome(animal).natural_rgb
}

/// Retrieve the full slice of all 106 mascots.
pub fn get_all_mascots() -> &'static [MascotBiomeInfo] {
    &ALL_MASCOTS
}
