//! Embedded built-in cow art catalog for Forgum.
//!
//! Provides compile-time embedded .cow ASCII templates for all 132 mascots.
//! Ensures 100% resilient mascot rendering across any deployment target (standalone binaries,
//! containers, minimal chroots, and clean installations) without requiring external files on disk.

/// Retrieve the compile-time embedded .cow template for a given mascot name, if available.
pub fn get_embedded_cow(name: &str) -> Option<&'static str> {
    let clean = name.trim().to_ascii_lowercase();
    let sanitized = clean.trim_end_matches(".cow");
    let resolved = match sanitized {
        "cow" | "cowsay" | "the-cow" => "default",
        "kittens" => "kitten",
        "nyan-cat" | "nyancat" | "nyan_cat" => "nyan",
        other => other,
    };
    match resolved {
        "apt" => Some(include_str!("../../../data/Cows/apt.cow")),
        "armadillo" => Some(include_str!("../../../data/Cows/armadillo.cow")),
        "atat" => Some(include_str!("../../../data/Cows/atat.cow")),
        "bearface" => Some(include_str!("../../../data/Cows/bearface.cow")),
        "beavis.zen" => Some(include_str!("../../../data/Cows/beavis.zen.cow")),
        "bees" => Some(include_str!("../../../data/Cows/bees.cow")),
        "bill-the-cat" => Some(include_str!("../../../data/Cows/bill-the-cat.cow")),
        "bud-frogs" => Some(include_str!("../../../data/Cows/bud-frogs.cow")),
        "bunny" => Some(include_str!("../../../data/Cows/bunny.cow")),
        "cat" => Some(include_str!("../../../data/Cows/cat.cow")),
        "cat2" => Some(include_str!("../../../data/Cows/cat2.cow")),
        "catfence" => Some(include_str!("../../../data/Cows/catfence.cow")),
        "charizardvice" => Some(include_str!("../../../data/Cows/charizardvice.cow")),
        "charlie" => Some(include_str!("../../../data/Cows/charlie.cow")),
        "claw-arm" => Some(include_str!("../../../data/Cows/claw-arm.cow")),
        "corgi" => Some(include_str!("../../../data/Cows/corgi.cow")),
        "cower" => Some(include_str!("../../../data/Cows/cower.cow")),
        "cowfee" => Some(include_str!("../../../data/Cows/cowfee.cow")),
        "cthulhu-mini" => Some(include_str!("../../../data/Cows/cthulhu-mini.cow")),
        "daemon" => Some(include_str!("../../../data/Cows/daemon.cow")),
        "default" => Some(include_str!("../../../data/Cows/default.cow")),
        "docker-whale" => Some(include_str!("../../../data/Cows/docker-whale.cow")),
        "doge" => Some(include_str!("../../../data/Cows/doge.cow")),
        "dolphin" => Some(include_str!("../../../data/Cows/dolphin.cow")),
        "dragon-and-cow" => Some(include_str!("../../../data/Cows/dragon-and-cow.cow")),
        "dragon" => Some(include_str!("../../../data/Cows/dragon.cow")),
        "duck" => Some(include_str!("../../../data/Cows/duck.cow")),
        "ebi_furai" => Some(include_str!("../../../data/Cows/ebi_furai.cow")),
        "elephant-in-snake" => Some(include_str!("../../../data/Cows/elephant-in-snake.cow")),
        "elephant" => Some(include_str!("../../../data/Cows/elephant.cow")),
        "elephant2" => Some(include_str!("../../../data/Cows/elephant2.cow")),
        "eyes" => Some(include_str!("../../../data/Cows/eyes.cow")),
        "fat-banana" => Some(include_str!("../../../data/Cows/fat-banana.cow")),
        "fat-cow" => Some(include_str!("../../../data/Cows/fat-cow.cow")),
        "fence" => Some(include_str!("../../../data/Cows/fence.cow")),
        "flaming-sheep" => Some(include_str!("../../../data/Cows/flaming-sheep.cow")),
        "fox" => Some(include_str!("../../../data/Cows/fox.cow")),
        "ghost" => Some(include_str!("../../../data/Cows/ghost.cow")),
        "ghostbusters" => Some(include_str!("../../../data/Cows/ghostbusters.cow")),
        "glados" => Some(include_str!("../../../data/Cows/glados.cow")),
        "goat" => Some(include_str!("../../../data/Cows/goat.cow")),
        "goat2" => Some(include_str!("../../../data/Cows/goat2.cow")),
        "golden-eagle" => Some(include_str!("../../../data/Cows/golden-eagle.cow")),
        "hamster" => Some(include_str!("../../../data/Cows/hamster.cow")),
        "happy-whale" => Some(include_str!("../../../data/Cows/happy-whale.cow")),
        "hedgehog" => Some(include_str!("../../../data/Cows/hedgehog.cow")),
        "hellokitty" => Some(include_str!("../../../data/Cows/hellokitty.cow")),
        "hippie" => Some(include_str!("../../../data/Cows/hippie.cow")),
        "hiya" => Some(include_str!("../../../data/Cows/hiya.cow")),
        "hypno" => Some(include_str!("../../../data/Cows/hypno.cow")),
        "jellyfish" => Some(include_str!("../../../data/Cows/jellyfish.cow")),
        "jesus" => Some(include_str!("../../../data/Cows/jesus.cow")),
        "king" => Some(include_str!("../../../data/Cows/king.cow")),
        "kiss" => Some(include_str!("../../../data/Cows/kiss.cow")),
        "kitten" => Some(include_str!("../../../data/Cows/kitten.cow")),
        "kitty" => Some(include_str!("../../../data/Cows/kitty.cow")),
        "knight" => Some(include_str!("../../../data/Cows/knight.cow")),
        "koala" => Some(include_str!("../../../data/Cows/koala.cow")),
        "kosh" => Some(include_str!("../../../data/Cows/kosh.cow")),
        "lamb" => Some(include_str!("../../../data/Cows/lamb.cow")),
        "lamb2" => Some(include_str!("../../../data/Cows/lamb2.cow")),
        "lobster" => Some(include_str!("../../../data/Cows/lobster.cow")),
        "lollerskates" => Some(include_str!("../../../data/Cows/lollerskates.cow")),
        "luke-koala" => Some(include_str!("../../../data/Cows/luke-koala.cow")),
        "mech-and-cow" => Some(include_str!("../../../data/Cows/mech-and-cow.cow")),
        "meow" => Some(include_str!("../../../data/Cows/meow.cow")),
        "minotaur" => Some(include_str!("../../../data/Cows/minotaur.cow")),
        "mona-lisa" => Some(include_str!("../../../data/Cows/mona-lisa.cow")),
        "moofasa" => Some(include_str!("../../../data/Cows/moofasa.cow")),
        "mooghidjirah" => Some(include_str!("../../../data/Cows/mooghidjirah.cow")),
        "moojira" => Some(include_str!("../../../data/Cows/moojira.cow")),
        "moose" => Some(include_str!("../../../data/Cows/moose.cow")),
        "mule" => Some(include_str!("../../../data/Cows/mule.cow")),
        "mutilated" => Some(include_str!("../../../data/Cows/mutilated.cow")),
        "nyan" => Some(include_str!("../../../data/Cows/nyan.cow")),
        "octopus" => Some(include_str!("../../../data/Cows/octopus.cow")),
        "owl" => Some(include_str!("../../../data/Cows/owl.cow")),
        "panther" => Some(include_str!("../../../data/Cows/panther.cow")),
        "pawn" => Some(include_str!("../../../data/Cows/pawn.cow")),
        "periodic-table" => Some(include_str!("../../../data/Cows/periodic-table.cow")),
        "personality-sphere" => Some(include_str!("../../../data/Cows/personality-sphere.cow")),
        "pig" => Some(include_str!("../../../data/Cows/pig.cow")),
        "pterodactyl" => Some(include_str!("../../../data/Cows/pterodactyl.cow")),
        "pufferfish" => Some(include_str!("../../../data/Cows/pufferfish.cow")),
        "queen" => Some(include_str!("../../../data/Cows/queen.cow")),
        "radioactive-kitty" => Some(include_str!("../../../data/Cows/radioactive-kitty.cow")),
        "ram" => Some(include_str!("../../../data/Cows/ram.cow")),
        "ren" => Some(include_str!("../../../data/Cows/ren.cow")),
        "rhino" => Some(include_str!("../../../data/Cows/rhino.cow")),
        "rook" => Some(include_str!("../../../data/Cows/rook.cow")),
        "rooster" => Some(include_str!("../../../data/Cows/rooster.cow")),
        "satanic" => Some(include_str!("../../../data/Cows/satanic.cow")),
        "sauron" => Some(include_str!("../../../data/Cows/sauron.cow")),
        "seahorse-big" => Some(include_str!("../../../data/Cows/seahorse-big.cow")),
        "seahorse" => Some(include_str!("../../../data/Cows/seahorse.cow")),
        "sheep" => Some(include_str!("../../../data/Cows/sheep.cow")),
        "shikato" => Some(include_str!("../../../data/Cows/shikato.cow")),
        "shrug" => Some(include_str!("../../../data/Cows/shrug.cow")),
        "skeleton" => Some(include_str!("../../../data/Cows/skeleton.cow")),
        "sloth" => Some(include_str!("../../../data/Cows/sloth.cow")),
        "small" => Some(include_str!("../../../data/Cows/small.cow")),
        "smiling-octopus" => Some(include_str!("../../../data/Cows/smiling-octopus.cow")),
        "snoopy" => Some(include_str!("../../../data/Cows/snoopy.cow")),
        "snoopyhouse" => Some(include_str!("../../../data/Cows/snoopyhouse.cow")),
        "snoopysleep" => Some(include_str!("../../../data/Cows/snoopysleep.cow")),
        "spidercow" => Some(include_str!("../../../data/Cows/spidercow.cow")),
        "squid" => Some(include_str!("../../../data/Cows/squid.cow")),
        "squirrel" => Some(include_str!("../../../data/Cows/squirrel.cow")),
        "stegosaurus" => Some(include_str!("../../../data/Cows/stegosaurus.cow")),
        "stimpy" => Some(include_str!("../../../data/Cows/stimpy.cow")),
        "supermilker" => Some(include_str!("../../../data/Cows/supermilker.cow")),
        "surgery" => Some(include_str!("../../../data/Cows/surgery.cow")),
        "telebears" => Some(include_str!("../../../data/Cows/telebears.cow")),
        "three-eyes" => Some(include_str!("../../../data/Cows/three-eyes.cow")),
        "tiger" => Some(include_str!("../../../data/Cows/tiger.cow")),
        "tortoise" => Some(include_str!("../../../data/Cows/tortoise.cow")),
        "turkey" => Some(include_str!("../../../data/Cows/turkey.cow")),
        "turtle" => Some(include_str!("../../../data/Cows/turtle.cow")),
        "tux-big" => Some(include_str!("../../../data/Cows/tux-big.cow")),
        "tux" => Some(include_str!("../../../data/Cows/tux.cow")),
        "tweety-bird" => Some(include_str!("../../../data/Cows/tweety-bird.cow")),
        "unipony" => Some(include_str!("../../../data/Cows/unipony.cow")),
        "vader" => Some(include_str!("../../../data/Cows/vader.cow")),
        "viper" => Some(include_str!("../../../data/Cows/viper.cow")),
        "vulpix" => Some(include_str!("../../../data/Cows/vulpix.cow")),
        "walrus" => Some(include_str!("../../../data/Cows/walrus.cow")),
        "weeping-angel" => Some(include_str!("../../../data/Cows/weeping-angel.cow")),
        "whale" => Some(include_str!("../../../data/Cows/whale.cow")),
        "wizard" => Some(include_str!("../../../data/Cows/wizard.cow")),
        "wolf" => Some(include_str!("../../../data/Cows/wolf.cow")),
        "world" => Some(include_str!("../../../data/Cows/world.cow")),
        "yoda" => Some(include_str!("../../../data/Cows/yoda.cow")),
        _ => None,
    }
}

/// List of all 132 built-in embedded mascot names.
pub const EMBEDDED_COW_NAMES: &[&str] = &[
    "apt",
    "armadillo",
    "atat",
    "bearface",
    "beavis.zen",
    "bees",
    "bill-the-cat",
    "bud-frogs",
    "bunny",
    "cat",
    "cat2",
    "catfence",
    "charizardvice",
    "charlie",
    "claw-arm",
    "corgi",
    "cower",
    "cowfee",
    "cthulhu-mini",
    "daemon",
    "default",
    "docker-whale",
    "doge",
    "dolphin",
    "dragon-and-cow",
    "dragon",
    "duck",
    "ebi_furai",
    "elephant-in-snake",
    "elephant",
    "elephant2",
    "eyes",
    "fat-banana",
    "fat-cow",
    "fence",
    "flaming-sheep",
    "fox",
    "ghost",
    "ghostbusters",
    "glados",
    "goat",
    "goat2",
    "golden-eagle",
    "hamster",
    "happy-whale",
    "hedgehog",
    "hellokitty",
    "hippie",
    "hiya",
    "hypno",
    "jellyfish",
    "jesus",
    "king",
    "kiss",
    "kitten",
    "kitty",
    "knight",
    "koala",
    "kosh",
    "lamb",
    "lamb2",
    "lobster",
    "lollerskates",
    "luke-koala",
    "mech-and-cow",
    "meow",
    "minotaur",
    "mona-lisa",
    "moofasa",
    "mooghidjirah",
    "moojira",
    "moose",
    "mule",
    "mutilated",
    "nyan",
    "octopus",
    "owl",
    "panther",
    "pawn",
    "periodic-table",
    "personality-sphere",
    "pig",
    "pterodactyl",
    "pufferfish",
    "queen",
    "radioactive-kitty",
    "ram",
    "ren",
    "rhino",
    "rook",
    "rooster",
    "satanic",
    "sauron",
    "seahorse-big",
    "seahorse",
    "sheep",
    "shikato",
    "shrug",
    "skeleton",
    "sloth",
    "small",
    "smiling-octopus",
    "snoopy",
    "snoopyhouse",
    "snoopysleep",
    "spidercow",
    "squid",
    "squirrel",
    "stegosaurus",
    "stimpy",
    "supermilker",
    "surgery",
    "telebears",
    "three-eyes",
    "tiger",
    "tortoise",
    "turkey",
    "turtle",
    "tux-big",
    "tux",
    "tweety-bird",
    "unipony",
    "vader",
    "viper",
    "vulpix",
    "walrus",
    "weeping-angel",
    "whale",
    "wizard",
    "wolf",
    "world",
    "yoda",
];

/// Return slice of all embedded mascot names.
pub fn all_embedded_cow_names() -> &'static [&'static str] {
    EMBEDDED_COW_NAMES
}

/// Total count of compile-time embedded mascots.
pub fn embedded_cow_count() -> usize {
    EMBEDDED_COW_NAMES.len()
}
