//! Shell completion generation, installation, and multi-shell auto-suggestion support.
//!
//! Provides rich completions with parameter value candidates and descriptive tooltips
//! compatible with `zsh-autosuggestions`, `fzf-tab`, `fish`, `pwsh`, `powershell.exe`,
//! `elvish`, `nushell`, and `carapace` specifications.

use std::io;
use std::path::{Path, PathBuf};

use clap_complete::{generate, shells};

use crate::init::Shell;

/// Result of installing shell completions.
#[derive(Debug, Clone)]
pub struct CompletionInstallResult {
    pub shell: Shell,
    pub script_path: Option<PathBuf>,
    pub rc_path: Option<PathBuf>,
    pub script_written: bool,
    pub rc_updated: bool,
    pub message: String,
}

/// Generate completions and write to stdout (used by CLI or test suites).
pub fn generate_completions(shell: Shell, cmd: &mut clap::Command) -> io::Result<()> {
    let script = generate_completion_script(shell, cmd);
    print!("{script}");
    Ok(())
}

/// Install shell completions to the shell's standard configuration directory
/// and idempotently attach source lines to the shell profile / rc file.
pub fn install_completions(
    shell: Shell,
    cmd: &mut clap::Command,
) -> io::Result<CompletionInstallResult> {
    let script = generate_completion_script(shell, cmd);
    let script_path = shell.completions_script_path();
    let rc_path = shell.shell_rc_path();

    let mut script_written = false;
    let mut rc_updated = false;

    if let Some(ref sp) = script_path {
        script_written = forgum_platform::write_file_if_changed(sp, &script)?;
    }

    if let (Some(ref sp), Some(ref rc)) = (&script_path, &rc_path) {
        if let Some(source_cmd) = shell.shell_source_command(sp) {
            let begin_marker = "# >>> forgum completions >>>";
            let end_marker = "# <<< forgum completions <<<";
            let block = format!(
                "{begin_marker}\n# Generated by forgum completions — do not edit by hand\n{source_cmd}\n{end_marker}\n"
            );
            let current_rc = std::fs::read_to_string(rc).unwrap_or_default();
            let new_rc = forgum_platform::update_delimited_block(
                &current_rc,
                begin_marker,
                end_marker,
                &block,
            );
            rc_updated = forgum_platform::write_file_if_changed(rc, &new_rc)?;
        }
    }

    let message = format_install_message(
        shell,
        script_path.as_deref(),
        rc_path.as_deref(),
        script_written,
        rc_updated,
    );

    Ok(CompletionInstallResult {
        shell,
        script_path,
        rc_path,
        script_written,
        rc_updated,
        message,
    })
}

fn format_install_message(
    shell: Shell,
    script_path: Option<&Path>,
    rc_path: Option<&Path>,
    script_written: bool,
    rc_updated: bool,
) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "\x1b[1;32m✓\x1b[0m Forgum completions configured for \x1b[1m{}\x1b[0m\n",
        shell
    ));

    if let Some(sp) = script_path {
        let status = if script_written {
            "installed"
        } else {
            "up to date"
        };
        out.push_str(&format!(
            "  \x1b[36m•\x1b[0m Script ({}): {}\n",
            status,
            sp.display()
        ));
    }

    if let Some(rc) = rc_path {
        let status = if rc_updated {
            "updated"
        } else {
            "already configured"
        };
        out.push_str(&format!(
            "  \x1b[36m•\x1b[0m Profile ({}): {}\n",
            status,
            rc.display()
        ));
        out.push_str(&format!("\n\x1b[90mTo activate immediately in your current session:\x1b[0m\n  \x1b[1msource {}\x1b[0m\n", rc.display()));
    } else if shell == Shell::Carapace {
        out.push_str("  \x1b[36m•\x1b[0m Carapace spec registered. Completions will appear across all Carapace-managed shells.\n");
    }

    out
}

/// Generate completion script string for the target shell.
pub fn generate_completion_script(shell: Shell, cmd: &mut clap::Command) -> String {
    match shell {
        Shell::Bash => generate_bash_completions(cmd),
        Shell::Zsh => generate_zsh_completions(cmd),
        Shell::Fish => generate_fish_completions(),
        Shell::Pwsh | Shell::PowerShell => generate_powershell_completions(),
        Shell::Elvish => generate_elvish_completions(cmd),
        Shell::Nushell => generate_nushell_completions(),
        Shell::Carapace => generate_carapace_spec(),
        Shell::Xonsh => generate_xonsh_completions(),
        Shell::Tcsh => generate_tcsh_completions(),
        Shell::Ksh => generate_ksh_completions(cmd),
        Shell::Ion => generate_ion_completions(),
        Shell::Oil => generate_oil_completions(cmd),
        Shell::Yash => generate_yash_completions(),
        Shell::Cmd => String::new(),
    }
}

fn generate_bash_completions(cmd: &mut clap::Command) -> String {
    let mut buf = Vec::new();
    generate(shells::Bash, cmd, "forgum", &mut buf);
    let mut script = String::from_utf8_lossy(&buf).into_owned();

    // Enrich with discrete value completion lists for bash
    let enrichment = r#"
# Forgum dynamic value completion helpers for bash
_forgum_effects="walk breathe float fly talk sway pulse glitch particles dissolve"
_forgum_mountains="hills peaks volcano iceberg skyline seamount plateau crater gothic castle garden none"
_forgum_roads="dirt cobblestone magma ice seabed sidewalk roof grid crypt savanna mud tracks checkerboard none"
_forgum_environments="pasture inferno ocean arctic city forest savanna swamp space cyber graveyard jurassic hive throne none"
_forgum_colors="animal rainbow solid none"
_forgum_animals="default dragon tux cat ghost elephant bunny corgi fox octopus random"

_forgum_custom_complete() {
    local prev="${COMP_WORDS[COMP_CWORD-1]}"
    local cur="${COMP_WORDS[COMP_CWORD]}"
    case "$prev" in
        --effect|-e)
            COMPREPLY=( $(compgen -W "$_forgum_effects" -- "$cur") )
            return 0
            ;;
        --mountain)
            COMPREPLY=( $(compgen -W "$_forgum_mountains" -- "$cur") )
            return 0
            ;;
        --road)
            COMPREPLY=( $(compgen -W "$_forgum_roads" -- "$cur") )
            return 0
            ;;
        --environment)
            COMPREPLY=( $(compgen -W "$_forgum_environments" -- "$cur") )
            return 0
            ;;
        --color-mode)
            COMPREPLY=( $(compgen -W "$_forgum_colors" -- "$cur") )
            return 0
            ;;
        --cow|--animal|-a)
            COMPREPLY=( $(compgen -W "$_forgum_animals" -- "$cur") )
            return 0
            ;;
    esac
    return 1
}
"#;
    script.push_str(enrichment);
    script
}

fn generate_zsh_completions(cmd: &mut clap::Command) -> String {
    let mut buf = Vec::new();
    generate(shells::Zsh, cmd, "forgum", &mut buf);
    let mut script = String::from_utf8_lossy(&buf).into_owned();

    // Add zsh-autosuggestions / fzf-tab value candidate descriptions
    let zsh_extra = r#"
# ── forgum value completions for zsh & fzf-tab ──
_forgum_effects=(
    'walk:Natural bovine walking animation'
    'breathe:Gentle breathing idle animation'
    'float:Drifting levitation animation'
    'fly:Flying creature animation'
    'talk:Conversational speech animation'
    'sway:Swaying pendulum animation'
    'pulse:Pulsing scale animation'
    'glitch:Digital cyberpunk glitch animation'
    'particles:Ambient particle emitter animation'
    'dissolve:Dissolve and materialize animation'
)
_forgum_mountains=(
    'hills:Rolling verdant hills'
    'peaks:Jagged alpine mountain peaks'
    'volcano:Active smoldering volcano'
    'iceberg:Frozen glacier ridges'
    'skyline:Urban skyscraper silhouette'
    'seamount:Underwater tectonic ridges'
    'plateau:Desert mesa and canyon ridges'
    'crater:Impact rim and astral ridge'
    'gothic:Spire and cathedral silhouette'
    'castle:Fortress ramparts and battlements'
    'garden:Terraced hedge and floral ridge'
    'none:Disable mountain horizon'
)
_forgum_roads=(
    'dirt:Winding countryside trail'
    'cobblestone:Medieval stone pavement'
    'magma:Cracked volcanic basalt'
    'ice:Packed snow and crystalline ice'
    'seabed:Ripple sands and deep coral'
    'sidewalk:Paved urban asphalt'
    'roof:Ceramic roof shingles and tiles'
    'grid:Neon vector cyber grid'
    'crypt:Dark catacomb flagstones'
    'savanna:Sun-baked arid trail'
    'mud:Squishy wet soil'
    'tracks:Parallel steel railroad ties'
    'checkerboard:High-contrast dual tiles'
    'none:Disable ground layer'
)
_forgum_environments=(
    'pasture:Peaceful open meadows'
    'inferno:Blazing magma chambers'
    'ocean:Deep sea aquatic realm'
    'arctic:Frozen tundra and blizzard'
    'city:Bustling metropolitan skyline'
    'forest:Ancient whispering woodlands'
    'savanna:Sun-drenched golden plains'
    'swamp:Murky bayou and mist'
    'space:Deep cosmos and stellar void'
    'cyber:Neon digital matrix'
    'graveyard:Foggy gothic cemetery'
    'jurassic:Prehistoric primeval wilds'
    'hive:Organic bio-mechanical hive'
    'throne:Imperial gothic sanctuary'
    'none:Disable particle effects'
)
"#;
    script.push_str(zsh_extra);
    script
}

fn generate_fish_completions() -> String {
    r#"# forgum fish completion script with auto-suggestions
function __fish_forgum_no_subcommand
    set -l cmd (commandline -poc)
    test (count $cmd) -eq 1
end

complete -c forgum -f

# Subcommands
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'render' -d 'Render mascot animation (default)'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'think' -d 'Render in cowthink mode'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'fortune' -d 'Print a random fortune'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'options' -d 'Display available options in structured tables'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'completions' -d 'Install shell completions and attach to profile'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'init' -d 'Generate shell integration hook'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'tui' -d 'Launch interactive terminal UI'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'status' -d 'Print engine status'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'doctor' -d 'Diagnose configuration and capabilities'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'checkhealth' -d 'Run comprehensive system health check'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'config' -d 'View or edit configuration'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'logs' -d 'View, stream, or clear engine logs'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'herd' -d 'Fleet manager for background daemons'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'theme' -d 'Manage mascot theme'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'demo' -d 'Run showcase demo'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'showcase' -d 'Run 60-second demo reel'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'say' -d 'Run command and display output in speech bubble'

# Rich option value completions with descriptions
complete -c forgum -l effect -s e -d 'Animation effect' -x -a 'walk	"Natural bovine walking animation" breathe	"Gentle idle breathing animation" float	"Drifting levitation animation" fly	"Flying creature animation" talk	"Conversational jaw animation" sway	"Swaying pendulum animation" pulse	"Pulsing scale animation" glitch	"Digital cyberpunk glitch animation" particles	"Ambient particle emitter animation" dissolve	"Dissolve and materialize animation"'
complete -c forgum -l cow -l animal -s c -s a -d 'Animal mascot name' -x -a 'default	"Standard bovine mascot" dragon	"Fire-breathing dragon" tux	"Linux penguin mascot" cat	"Playful feline mascot" ghost	"Spooky floating phantom" elephant	"Gentle giant" bunny	"Cute rabbit mascot" corgi	"Playful corgi" fox	"Clever woodland fox" random	"Pick random mascot"'
complete -c forgum -l mountain -d 'Mountain/horizon style' -x -a 'hills	"Rolling verdant hills" peaks	"Jagged alpine peaks" volcano	"Active smoldering volcano" iceberg	"Frozen glacier ridges" skyline	"Urban skyscraper silhouette" seamount	"Underwater tectonic ridges" plateau	"Desert mesa and canyon ridges" crater	"Impact rim and astral ridge" gothic	"Spire and cathedral silhouette" castle	"Fortress ramparts" garden	"Terraced hedge and floral ridge" none	"Disable mountain horizon"'
complete -c forgum -l road -d 'Road/ground style' -x -a 'dirt	"Countryside dirt trail" cobblestone	"Medieval stone pavement" magma	"Cracked volcanic basalt" ice	"Packed crystalline ice" seabed	"Ripple sands and deep coral" sidewalk	"Paved urban asphalt" roof	"Ceramic roof shingles" grid	"Neon vector cyber grid" crypt	"Dark catacomb flagstones" savanna	"Sun-baked arid trail" mud	"Squishy wet soil" tracks	"Railroad ties" checkerboard	"High-contrast dual tiles" none	"Disable ground layer"'
complete -c forgum -l environment -d 'Environment particle effect' -x -a 'pasture	"Open meadows" inferno	"Blazing magma" ocean	"Aquatic realm" arctic	"Frozen tundra" city	"Metropolitan skyline" forest	"Ancient woodlands" savanna	"Golden plains" swamp	"Murky bayou" space	"Cosmos void" cyber	"Digital matrix" graveyard	"Gothic cemetery" jurassic	"Primeval wilds" hive	"Bio hive" throne	"Gothic sanctuary" none	"Disable particles"'
complete -c forgum -l color-mode -d 'Color rendering mode' -x -a 'animal	"Creature archetype colors" rainbow	"Dynamic oscillating spectrum" solid	"Single pure hue" none	"Monochrome terminal default"'
complete -c forgum -l text -s t -d 'Text inside the speech bubble'
complete -c forgum -l think -s T -d 'Render as thought bubble instead of speech bubble'
complete -c forgum -l background -s b -d 'Render above prompt as non-blocking overlay'
complete -c forgum -l banner -s B -d 'Render inline as animated banner above prompt'
complete -c forgum -l duration -s d -d 'Duration in seconds (0 = infinite)'
complete -c forgum -l fps -d 'Target frames per second'
complete -c forgum -l thought-interval -d 'Interval in seconds for rotating fortunes'
complete -c forgum -l split-scroll -d 'Lock scroll margins below animation'
complete -c forgum -l eyes -d 'Custom eyes (e.g. oo, $$, @@)'
complete -c forgum -l tongue -d 'Custom tongue (e.g. U)'
"#.to_string()
}

fn generate_powershell_completions() -> String {
    r#"# forgum PowerShell completion script with argument completer & tooltips
Register-ArgumentCompleter -Native -CommandName 'forgum' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $elements = $commandAst.CommandElements
    $prevWord = if ($elements.Count -ge 2) { $elements[-2].Extent.Text } else { '' }

    $effects = @{
        'walk' = 'Natural bovine walking animation'
        'breathe' = 'Gentle breathing idle animation'
        'float' = 'Drifting levitation animation'
        'fly' = 'Flying creature animation'
        'talk' = 'Conversational speech animation'
        'sway' = 'Swaying pendulum animation'
        'pulse' = 'Pulsing scale animation'
        'glitch' = 'Digital cyberpunk glitch animation'
        'particles' = 'Ambient particle emitter animation'
        'dissolve' = 'Dissolve and materialize animation'
    }

    $mountains = @{
        'hills' = 'Rolling verdant hills'
        'peaks' = 'Jagged alpine mountain peaks'
        'volcano' = 'Active smoldering volcano'
        'iceberg' = 'Frozen glacier ridges'
        'skyline' = 'Urban skyscraper silhouette'
        'seamount' = 'Underwater tectonic ridges'
        'plateau' = 'Desert mesa and canyon ridges'
        'crater' = 'Impact rim and astral ridge'
        'gothic' = 'Spire and cathedral silhouette'
        'castle' = 'Fortress ramparts and battlements'
        'garden' = 'Terraced hedge and floral ridge'
        'none' = 'Disable mountain horizon'
    }

    $roads = @{
        'dirt' = 'Countryside dirt trail'
        'cobblestone' = 'Medieval stone pavement'
        'magma' = 'Cracked volcanic basalt'
        'ice' = 'Packed snow and crystalline ice'
        'seabed' = 'Ripple sands and deep coral'
        'sidewalk' = 'Paved urban asphalt'
        'roof' = 'Ceramic roof shingles'
        'grid' = 'Neon vector cyber grid'
        'crypt' = 'Dark catacomb flagstones'
        'savanna' = 'Sun-baked arid trail'
        'mud' = 'Squishy wet soil'
        'tracks' = 'Parallel steel railroad ties'
        'checkerboard' = 'High-contrast dual tiles'
        'none' = 'Disable ground layer'
    }

    $environments = @{
        'pasture' = 'Peaceful open meadows'
        'inferno' = 'Blazing magma chambers'
        'ocean' = 'Deep sea aquatic realm'
        'arctic' = 'Frozen tundra and blizzard'
        'city' = 'Bustling metropolitan skyline'
        'forest' = 'Ancient whispering woodlands'
        'savanna' = 'Sun-drenched golden plains'
        'swamp' = 'Murky bayou and mist'
        'space' = 'Deep cosmos and stellar void'
        'cyber' = 'Neon digital matrix'
        'graveyard' = 'Foggy gothic cemetery'
        'jurassic' = 'Prehistoric primeval wilds'
        'hive' = 'Organic bio-mechanical hive'
        'throne' = 'Imperial gothic sanctuary'
        'none' = 'Disable particle effects'
    }

    $colors = @{
        'animal' = 'Archetype creature colors'
        'rainbow' = 'Dynamic oscillating spectrum'
        'solid' = 'Single pure hue'
        'none' = 'Monochrome terminal default'
    }

    $animals = @{
        'default' = 'Standard bovine mascot'
        'dragon' = 'Fire-breathing dragon'
        'tux' = 'Linux penguin mascot'
        'cat' = 'Playful feline mascot'
        'ghost' = 'Spooky floating phantom'
        'elephant' = 'Gentle giant'
        'bunny' = 'Cute rabbit mascot'
        'corgi' = 'Playful corgi'
        'fox' = 'Clever woodland fox'
        'random' = 'Pick random mascot'
    }

    $targetMap = $null
    switch ($prevWord) {
        { $_ -in '--effect', '-e' } { $targetMap = $effects }
        '--mountain' { $targetMap = $mountains }
        '--road' { $targetMap = $roads }
        '--environment' { $targetMap = $environments }
        '--color-mode' { $targetMap = $colors }
        { $_ -in '--cow', '--animal', '-a' } { $targetMap = $animals }
    }

    if ($targetMap) {
        $targetMap.GetEnumerator() | Where-Object { $_.Key -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_.Key, $_.Key, 'ParameterValue', $_.Value)
        }
        return
    }

    $flags = @(
        '--cow', '--animal', '--effect', '--mountain', '--road', '--environment',
        '--color-mode', '--text', '--think', '--background', '--banner',
        '--duration', '--fps', '--thought-interval', '--split-scroll',
        '--eyes', '--tongue', '--palette'
    )
    $subcommands = @(
        'render', 'think', 'fortune', 'options', 'completions', 'init', 'tui',
        'status', 'doctor', 'checkhealth', 'config', 'logs', 'herd', 'theme',
        'demo', 'showcase', 'say'
    )

    if ($wordToComplete -like '-*') {
        $flags | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
        }
    } else {
        $subcommands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'Command', $_)
        }
    }
}
"#.to_string()
}

fn generate_elvish_completions(cmd: &mut clap::Command) -> String {
    let mut buf = Vec::new();
    generate(shells::Elvish, cmd, "forgum", &mut buf);
    String::from_utf8_lossy(&buf).into_owned()
}

fn generate_nushell_completions() -> String {
    r#"# forgum nushell completion definitions
export extern "forgum" [
    --cow(-c): string@"nu_forgum_animals"              # Animal mascot name
    --animal(-a): string@"nu_forgum_animals"           # Animal mascot name
    --effect(-e): string@"nu_forgum_effects"           # Animation effect
    --mountain: string@"nu_forgum_mountains"           # Mountain/horizon style
    --road: string@"nu_forgum_roads"                   # Road/ground style
    --environment: string@"nu_forgum_environments"     # Environment particle effect
    --color-mode: string@"nu_forgum_colors"            # Color mode
    --text(-t): string                                 # Text inside speech bubble
    --think(-T)                                        # Render in cowthink mode
    --background(-b)                                   # Non-blocking overlay above prompt
    --banner(-B)                                       # Inline banner above prompt
    --duration(-d): int                                # Duration in seconds
    --fps: int                                         # Target FPS
    --thought-interval: int                            # Seconds between thought rotations
    --split-scroll                                     # Lock scroll margins below animation
]

def "nu_forgum_effects" [] {
    [
        { value: "walk", description: "Natural bovine walking animation" },
        { value: "breathe", description: "Gentle breathing idle animation" },
        { value: "float", description: "Drifting levitation animation" },
        { value: "fly", description: "Flying creature animation" },
        { value: "talk", description: "Conversational speech animation" },
        { value: "sway", description: "Swaying pendulum animation" },
        { value: "pulse", description: "Pulsing scale animation" },
        { value: "glitch", description: "Digital cyberpunk glitch animation" },
        { value: "particles", description: "Ambient particle emitter animation" },
        { value: "dissolve", description: "Dissolve and materialize animation" }
    ]
}

def "nu_forgum_mountains" [] {
    [
        { value: "hills", description: "Rolling verdant hills" },
        { value: "peaks", description: "Jagged alpine mountain peaks" },
        { value: "volcano", description: "Active smoldering volcano" },
        { value: "iceberg", description: "Frozen glacier ridges" },
        { value: "skyline", description: "Urban skyscraper silhouette" },
        { value: "seamount", description: "Underwater tectonic ridges" },
        { value: "plateau", description: "Desert mesa and canyon ridges" },
        { value: "crater", description: "Impact rim and astral ridge" },
        { value: "gothic", description: "Spire and cathedral silhouette" },
        { value: "castle", description: "Fortress ramparts and battlements" },
        { value: "garden", description: "Terraced hedge and floral ridge" },
        { value: "none", description: "Disable mountain horizon" }
    ]
}

def "nu_forgum_roads" [] {
    [
        { value: "dirt", description: "Countryside dirt trail" },
        { value: "cobblestone", description: "Medieval stone pavement" },
        { value: "magma", description: "Cracked volcanic basalt" },
        { value: "ice", description: "Packed crystalline ice" },
        { value: "seabed", description: "Ripple sands and deep coral" },
        { value: "sidewalk", description: "Paved urban asphalt" },
        { value: "roof", description: "Ceramic roof shingles" },
        { value: "grid", description: "Neon vector cyber grid" },
        { value: "crypt", description: "Dark catacomb flagstones" },
        { value: "savanna", description: "Sun-baked arid trail" },
        { value: "mud", description: "Squishy wet soil" },
        { value: "tracks", description: "Railroad ties" },
        { value: "checkerboard", description: "High-contrast dual tiles" },
        { value: "none", description: "Disable ground layer" }
    ]
}

def "nu_forgum_environments" [] {
    [
        { value: "pasture", description: "Open meadows" },
        { value: "inferno", description: "Blazing magma" },
        { value: "ocean", description: "Aquatic realm" },
        { value: "arctic", description: "Frozen tundra" },
        { value: "city", description: "Metropolitan skyline" },
        { value: "forest", description: "Ancient woodlands" },
        { value: "savanna", description: "Golden plains" },
        { value: "swamp", description: "Murky bayou" },
        { value: "space", description: "Cosmos void" },
        { value: "cyber", description: "Digital matrix" },
        { value: "graveyard", description: "Gothic cemetery" },
        { value: "jurassic", description: "Primeval wilds" },
        { value: "hive", description: "Bio hive" },
        { value: "throne", description: "Gothic sanctuary" },
        { value: "none", description: "Disable particles" }
    ]
}

def "nu_forgum_colors" [] {
    [
        { value: "animal", description: "Creature archetype colors" },
        { value: "rainbow", description: "Dynamic spectrum" },
        { value: "solid", description: "Single pure hue" },
        { value: "none", description: "Monochrome terminal default" }
    ]
}

def "nu_forgum_animals" [] {
    [
        { value: "default", description: "Standard bovine mascot" },
        { value: "dragon", description: "Fire-breathing dragon" },
        { value: "tux", description: "Linux penguin mascot" },
        { value: "cat", description: "Playful feline mascot" },
        { value: "ghost", description: "Spooky floating phantom" },
        { value: "elephant", description: "Gentle giant" },
        { value: "bunny", description: "Cute rabbit mascot" },
        { value: "corgi", description: "Playful corgi" },
        { value: "fox", description: "Clever woodland fox" },
        { value: "random", description: "Pick random mascot" }
    ]
}
"#
    .to_string()
}

fn generate_carapace_spec() -> String {
    r#"# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: forgum
description: Modern animated terminal mascot engine
flags:
  --cow=: Animal mascot name
  --animal=: Animal mascot name
  --effect=: Animation effect
  --mountain=: Mountain / horizon style
  --road=: Road / ground style
  --environment=: Environment particle effect
  --color-mode=: Color rendering mode
  --text=: Text inside speech bubble
  --duration=: Duration in seconds (0 = infinite)
  --fps=: Target frames per second
  --thought-interval=: Interval in seconds for thought rotation
  --eyes=: Custom eyes string
  --tongue=: Custom tongue string
  --palette=: Custom hex palette
  --think: Render in cowthink mode
  --background: Render above prompt as non-blocking overlay
  --banner: Render inline as animated banner
  --split-scroll: Lock terminal scroll margins below animation
completion:
  flag:
    cow: ["default\tStandard bovine mascot", "dragon\tFire-breathing dragon", "tux\tLinux penguin", "cat\tPlayful feline", "ghost\tSpooky phantom", "elephant\tGentle giant", "bunny\tCute rabbit", "corgi\tPlayful corgi", "fox\tWoodland fox", "random\tPick random mascot"]
    animal: ["default\tStandard bovine mascot", "dragon\tFire-breathing dragon", "tux\tLinux penguin", "cat\tPlayful feline", "ghost\tSpooky phantom", "elephant\tGentle giant", "bunny\tCute rabbit", "corgi\tPlayful corgi", "fox\tWoodland fox", "random\tPick random mascot"]
    effect: ["walk\tNatural bovine walking animation", "breathe\tGentle breathing idle animation", "float\tDrifting levitation animation", "fly\tFlying creature animation", "talk\tConversational speech animation", "sway\tSwaying pendulum animation", "pulse\tPulsing scale animation", "glitch\tDigital cyberpunk glitch animation", "particles\tAmbient particle emitter animation", "dissolve\tDissolve and materialize animation"]
    mountain: ["hills\tRolling verdant hills", "peaks\tAlpine peaks", "volcano\tActive volcano", "iceberg\tGlacier ridges", "skyline\tUrban skyline", "seamount\tUnderwater ridges", "plateau\tDesert mesa", "crater\tImpact rim", "gothic\tSpire silhouette", "castle\tFortress ramparts", "garden\tTerraced hedge", "none\tDisable mountains"]
    road: ["dirt\tCountryside dirt trail", "cobblestone\tStone pavement", "magma\tVolcanic basalt", "ice\tPacked crystalline ice", "seabed\tRipple sands", "sidewalk\tPaved asphalt", "roof\tRoof shingles", "grid\tNeon cyber grid", "crypt\tCatacomb flagstones", "savanna\tArid trail", "mud\tSquishy soil", "tracks\tRailroad ties", "checkerboard\tDual tiles", "none\tDisable road"]
    environment: ["pasture\tOpen meadows", "inferno\tBlazing magma", "ocean\tAquatic realm", "arctic\tFrozen tundra", "city\tMetropolitan skyline", "forest\tAncient woodlands", "savanna\tGolden plains", "swamp\tMurky bayou", "space\tCosmos void", "cyber\tDigital matrix", "graveyard\tGothic cemetery", "jurassic\tPrimeval wilds", "hive\tBio hive", "throne\tGothic sanctuary", "none\tDisable particles"]
    color-mode: ["animal\tCreature archetype colors", "rainbow\tDynamic spectrum", "solid\tSingle pure hue", "none\tMonochrome terminal default"]
commands:
  - name: render
    description: Render mascot animation (default)
  - name: think
    description: Render in cowthink mode
  - name: fortune
    description: Print a random fortune
  - name: options
    description: Display available options in structured tables
  - name: completions
    description: Install shell completions and attach to profile
  - name: init
    description: Generate shell integration hook
  - name: tui
    description: Interactive terminal UI
  - name: status
    description: Print engine status
  - name: doctor
    description: Diagnose configuration and capabilities
  - name: checkhealth
    description: Run comprehensive system health check
  - name: config
    description: View or edit configuration
  - name: logs
    description: View, stream, or clear engine logs
  - name: herd
    description: Fleet manager for background daemons
  - name: theme
    description: Manage mascot theme
  - name: demo
    description: Run showcase demo
  - name: showcase
    description: Run 60-second demo reel
  - name: say
    description: Run command and display output in speech bubble
"#.to_string()
}

fn generate_xonsh_completions() -> String {
    r#"# Xonsh completion specification for Forgum
from xonsh.completers.tools import *

@contextual_command_completer_for("forgum")
def _forgum_completer(command):
    opts = {
        "--animal", "--cow", "-a", "--effect", "-e", "--mountain", "--road",
        "--environment", "--color-mode", "--text", "--duration", "-d",
        "--fps", "--thought-interval", "--eyes", "--tongue", "--palette",
        "--think", "--background", "-b", "--banner", "-B", "--split-scroll",
        "render", "think", "fortune", "options", "list", "completions",
        "init", "tui", "status", "doctor", "checkhealth", "config", "logs",
        "herd", "theme", "demo", "showcase", "say", "help"
    }
    return opts
"#.to_string()
}

fn generate_tcsh_completions() -> String {
    r#"# Tcsh completion for Forgum
complete forgum \
  'c/--cow/(default dragon tux cat ghost elephant bunny corgi fox octopus random)/' \
  'c/--animal/(default dragon tux cat ghost elephant bunny corgi fox octopus random)/' \
  'c/-a/(default dragon tux cat ghost elephant bunny corgi fox octopus random)/' \
  'c/--effect/(walk breathe float fly talk sway pulse glitch particles dissolve)/' \
  'c/-e/(walk breathe float fly talk sway pulse glitch particles dissolve)/' \
  'c/--mountain/(hills peaks volcano iceberg skyline seamount plateau crater gothic castle garden none)/' \
  'c/--road/(dirt cobblestone magma ice seabed sidewalk roof grid crypt savanna mud tracks checkerboard none)/' \
  'c/--environment/(pasture inferno ocean arctic city forest savanna swamp space cyber graveyard jurassic hive throne none)/' \
  'c/--color-mode/(animal rainbow solid none)/' \
  'n/completions/(bash zsh fish pwsh powershell elvish nushell carapace xonsh tcsh ksh ion oil yash list)/' \
  'n/init/(bash zsh fish pwsh powershell elvish nushell carapace xonsh tcsh ksh ion oil yash cmd list)/' \
  'p/1/(render think fortune options list completions init tui status doctor checkhealth config logs herd theme demo showcase say help)/'
"#.to_string()
}

fn generate_ksh_completions(cmd: &mut clap::Command) -> String {
    generate_bash_completions(cmd)
}

fn generate_ion_completions() -> String {
    r#"# Ion completion for Forgum
complete -c forgum -a "render think fortune list completions init tui status doctor checkhealth config logs herd theme demo showcase say help"
complete -c forgum -l animal -a "default dragon tux cat ghost elephant bunny corgi fox octopus random"
complete -c forgum -l cow -a "default dragon tux cat ghost elephant bunny corgi fox octopus random"
complete -c forgum -l effect -a "walk breathe float fly talk sway pulse glitch particles dissolve"
complete -c forgum -l mountain -a "hills peaks volcano iceberg skyline seamount plateau crater gothic castle garden none"
complete -c forgum -l road -a "dirt cobblestone magma ice seabed sidewalk roof grid crypt savanna mud tracks checkerboard none"
complete -c forgum -l environment -a "pasture inferno ocean arctic city forest savanna swamp space cyber graveyard jurassic hive throne none"
complete -c forgum -l color-mode -a "animal rainbow solid none"
complete -c forgum -l background
complete -c forgum -l banner
"#.to_string()
}

fn generate_oil_completions(cmd: &mut clap::Command) -> String {
    generate_bash_completions(cmd)
}

fn generate_yash_completions() -> String {
    r#"# Yash completion for Forgum
function completion/forgum {
    typeset -a commands
    commands=(render think fortune list completions init tui status doctor checkhealth config logs herd theme demo showcase say help)
    complete -c commands
}
"#.to_string()
}
