//! Shell completion generation, installation, and multi-shell auto-suggestion support.
//!
//! Provides rich completions with parameter value candidates and descriptive tooltips
//! compatible with `zsh-autosuggestions`, `fzf-tab`, `fish`, `pwsh`, `powershell.exe`,
//! `elvish`, `nushell`, and `carapace` specifications.

use std::io;
use std::path::{Path, PathBuf};

use clap_complete::{generate, shells};

use crate::init::Shell;

/// Result of installing shell completions.
#[derive(Debug, Clone)]
pub struct CompletionInstallResult {
    pub shell: Shell,
    pub script_path: Option<PathBuf>,
    pub rc_path: Option<PathBuf>,
    pub script_written: bool,
    pub rc_updated: bool,
    pub message: String,
}

/// Generate completions and write to stdout (used by CLI or test suites).
pub fn generate_completions(shell: Shell, cmd: &mut clap::Command) -> io::Result<()> {
    let script = generate_completion_script(shell, cmd);
    print!("{script}");
    Ok(())
}

/// Install shell completions to the shell's standard configuration directory
/// and idempotently attach source lines to the shell profile / rc file.
pub fn install_completions(
    shell: Shell,
    cmd: &mut clap::Command,
) -> io::Result<CompletionInstallResult> {
    let script = generate_completion_script(shell, cmd);
    let script_path = shell.completions_script_path();
    let rc_path = shell.shell_rc_path();

    let mut script_written = false;
    let mut rc_updated = false;

    if let Some(ref sp) = script_path {
        script_written = forgum_platform::write_file_if_changed(sp, &script)?;
    }

    if let (Some(ref sp), Some(ref rc)) = (&script_path, &rc_path) {
        if let Some(source_cmd) = shell.shell_source_command(sp) {
            let begin_marker = "# >>> forgum completions >>>";
            let end_marker = "# <<< forgum completions <<<";
            let block = format!(
                "{begin_marker}\n# Generated by forgum completions — do not edit by hand\n{source_cmd}\n{end_marker}\n"
            );
            let current_rc = std::fs::read_to_string(rc).unwrap_or_default();
            let new_rc = forgum_platform::update_delimited_block(
                &current_rc,
                begin_marker,
                end_marker,
                &block,
            );
            rc_updated = forgum_platform::write_file_if_changed(rc, &new_rc)?;
        }
    }

    let message = format_install_message(
        shell,
        script_path.as_deref(),
        rc_path.as_deref(),
        script_written,
        rc_updated,
    );

    Ok(CompletionInstallResult {
        shell,
        script_path,
        rc_path,
        script_written,
        rc_updated,
        message,
    })
}

fn format_install_message(
    shell: Shell,
    script_path: Option<&Path>,
    rc_path: Option<&Path>,
    script_written: bool,
    rc_updated: bool,
) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "\x1b[1;32m✓\x1b[0m Forgum completions configured for \x1b[1m{}\x1b[0m\n",
        shell
    ));

    if let Some(sp) = script_path {
        let status = if script_written {
            "installed"
        } else {
            "up to date"
        };
        out.push_str(&format!(
            "  \x1b[36m•\x1b[0m Script ({}): {}\n",
            status,
            sp.display()
        ));
    }

    if let Some(rc) = rc_path {
        let status = if rc_updated {
            "updated"
        } else {
            "already configured"
        };
        out.push_str(&format!(
            "  \x1b[36m•\x1b[0m Profile ({}): {}\n",
            status,
            rc.display()
        ));
        out.push_str(&format!("\n\x1b[90mTo activate immediately in your current session:\x1b[0m\n  \x1b[1msource {}\x1b[0m\n", rc.display()));
    } else if shell == Shell::Carapace {
        out.push_str("  \x1b[36m•\x1b[0m Carapace spec registered. Completions will appear across all Carapace-managed shells.\n");
    }

    out
}

/// Generate completion script string for the target shell.
pub fn generate_completion_script(shell: Shell, cmd: &mut clap::Command) -> String {
    match shell {
        Shell::Bash => generate_bash_completions(cmd),
        Shell::Zsh => generate_zsh_completions(cmd),
        Shell::Fish => generate_fish_completions(),
        Shell::Pwsh | Shell::PowerShell => generate_powershell_completions(),
        Shell::Elvish => generate_elvish_completions(cmd),
        Shell::Nushell => generate_nushell_completions(),
        Shell::Carapace => generate_carapace_spec(),
        Shell::Xonsh => generate_xonsh_completions(),
        Shell::Tcsh => generate_tcsh_completions(),
        Shell::Ksh => generate_ksh_completions(cmd),
        Shell::Ion => generate_ion_completions(),
        Shell::Oil => generate_oil_completions(cmd),
        Shell::Yash => generate_yash_completions(),
        Shell::Cmd => String::new(),
    }
}

fn generate_bash_completions(cmd: &mut clap::Command) -> String {
    let mut buf = Vec::new();
    generate(shells::Bash, cmd, "forgum", &mut buf);
    let mut script = String::from_utf8_lossy(&buf).into_owned();

    // Enrich with discrete value completion lists for bash
    let enrichment = r#"
# Forgum dynamic value completion helpers for bash
_forgum_effects="walk breathe float fly talk sway pulse glitch particles dissolve"
_forgum_mountains="hills peaks volcano iceberg skyline seamount plateau crater gothic castle garden none"
_forgum_roads="dirt cobblestone magma ice seabed sidewalk roof grid crypt savanna mud tracks checkerboard none"
_forgum_environments="pasture inferno ocean arctic city forest savanna swamp space cyber graveyard jurassic hive throne none"
_forgum_colors="animal rainbow solid none"
_forgum_animals="apt armadillo atat bearface beavis.zen bees bill-the-cat bud-frogs bunny cat cat2 catfence charizardvice charlie claw-arm corgi cower cowfee cthulhu-mini daemon default docker-whale doge dolphin dragon dragon-and-cow duck ebi_furai elephant elephant-in-snake elephant2 eyes fat-banana fat-cow fence flaming-sheep fox ghost ghostbusters glados goat goat2 golden-eagle happy-whale hedgehog hellokitty hippie hiya hypno jellyfish jesus king kiss kitten kitty knight koala kosh lamb lamb2 lobster lollerskates luke-koala mech-and-cow meow milk minotaur mona-lisa moofasa mooghidjirah moojira moose mule mutilated nyan octopus owl panther pawn periodic-table personality-sphere pig pterodactyl pufferfish queen radioactive-kitty ram ren rhino rook rooster satanic sauron seahorse seahorse-big sheep shikato shrug skeleton sloth small smiling-octopus snoopy snoopyhouse snoopysleep spidercow squid squirrel stegosaurus stimpy supermilker surgery telebears three-eyes tiger tortoise turkey turtle tux tux-big tweety-bird unipony vader viper vulpix walrus weeping-angel whale wizard wolf world yoda random"

_forgum_custom_complete() {
    local prev="${COMP_WORDS[COMP_CWORD-1]}"
    local cur="${COMP_WORDS[COMP_CWORD]}"
    case "$prev" in
        --effect|-e)
            COMPREPLY=( $(compgen -W "$_forgum_effects" -- "$cur") )
            return 0
            ;;
        --mountain)
            COMPREPLY=( $(compgen -W "$_forgum_mountains" -- "$cur") )
            return 0
            ;;
        --road)
            COMPREPLY=( $(compgen -W "$_forgum_roads" -- "$cur") )
            return 0
            ;;
        --environment)
            COMPREPLY=( $(compgen -W "$_forgum_environments" -- "$cur") )
            return 0
            ;;
        --color-mode)
            COMPREPLY=( $(compgen -W "$_forgum_colors" -- "$cur") )
            return 0
            ;;
        --cow|--animal|-a)
            COMPREPLY=( $(compgen -W "$_forgum_animals" -- "$cur") )
            return 0
            ;;
    esac
    return 1
}
"#;
    script.push_str(enrichment);
    script
}

fn generate_zsh_completions(cmd: &mut clap::Command) -> String {
    let mut buf = Vec::new();
    generate(shells::Zsh, cmd, "forgum", &mut buf);
    let mut script = String::from_utf8_lossy(&buf).into_owned();

    // Add zsh-autosuggestions / fzf-tab value candidate descriptions
    let zsh_extra = r#"
# ── forgum value completions for zsh & fzf-tab ──
_forgum_effects=(
    'walk:Natural bovine walking animation'
    'breathe:Gentle breathing idle animation'
    'float:Drifting levitation animation'
    'fly:Flying creature animation'
    'talk:Conversational speech animation'
    'sway:Swaying pendulum animation'
    'pulse:Pulsing scale animation'
    'glitch:Digital cyberpunk glitch animation'
    'particles:Ambient particle emitter animation'
    'dissolve:Dissolve and materialize animation'
)
_forgum_mountains=(
    'hills:Rolling verdant hills'
    'peaks:Jagged alpine mountain peaks'
    'volcano:Active smoldering volcano'
    'iceberg:Frozen glacier ridges'
    'skyline:Urban skyscraper silhouette'
    'seamount:Underwater tectonic ridges'
    'plateau:Desert mesa and canyon ridges'
    'crater:Impact rim and astral ridge'
    'gothic:Spire and cathedral silhouette'
    'castle:Fortress ramparts and battlements'
    'garden:Terraced hedge and floral ridge'
    'none:Disable mountain horizon'
)
_forgum_roads=(
    'dirt:Winding countryside trail'
    'cobblestone:Medieval stone pavement'
    'magma:Cracked volcanic basalt'
    'ice:Packed snow and crystalline ice'
    'seabed:Ripple sands and deep coral'
    'sidewalk:Paved urban asphalt'
    'roof:Ceramic roof shingles and tiles'
    'grid:Neon vector cyber grid'
    'crypt:Dark catacomb flagstones'
    'savanna:Sun-baked arid trail'
    'mud:Squishy wet soil'
    'tracks:Parallel steel railroad ties'
    'checkerboard:High-contrast dual tiles'
    'none:Disable ground layer'
)
_forgum_environments=(
    'pasture:Peaceful open meadows'
    'inferno:Blazing magma chambers'
    'ocean:Deep sea aquatic realm'
    'arctic:Frozen tundra and blizzard'
    'city:Bustling metropolitan skyline'
    'forest:Ancient whispering woodlands'
    'savanna:Sun-drenched golden plains'
    'swamp:Murky bayou and mist'
    'space:Deep cosmos and stellar void'
    'cyber:Neon digital matrix'
    'graveyard:Foggy gothic cemetery'
    'jurassic:Prehistoric primeval wilds'
    'hive:Organic bio-mechanical hive'
    'throne:Imperial gothic sanctuary'
    'none:Disable particle effects'
)
_forgum_animals=(
    'apt:Mascot apt'
    'armadillo:Mascot armadillo'
    'atat:Mascot atat'
    'bearface:Mascot bearface'
    'beavis.zen:Mascot beavis.zen'
    'bees:Mascot bees'
    'bill-the-cat:Mascot bill-the-cat'
    'bud-frogs:Mascot bud-frogs'
    'bunny:Mascot bunny'
    'cat:Mascot cat'
    'cat2:Mascot cat2'
    'catfence:Mascot catfence'
    'charizardvice:Mascot charizardvice'
    'charlie:Mascot charlie'
    'claw-arm:Mascot claw-arm'
    'corgi:Mascot corgi'
    'cower:Mascot cower'
    'cowfee:Mascot cowfee'
    'cthulhu-mini:Mascot cthulhu-mini'
    'daemon:Mascot daemon'
    'default:Mascot default'
    'docker-whale:Mascot docker-whale'
    'doge:Mascot doge'
    'dolphin:Mascot dolphin'
    'dragon:Mascot dragon'
    'dragon-and-cow:Mascot dragon-and-cow'
    'duck:Mascot duck'
    'ebi_furai:Mascot ebi_furai'
    'elephant:Mascot elephant'
    'elephant-in-snake:Mascot elephant-in-snake'
    'elephant2:Mascot elephant2'
    'eyes:Mascot eyes'
    'fat-banana:Mascot fat-banana'
    'fat-cow:Mascot fat-cow'
    'fence:Mascot fence'
    'flaming-sheep:Mascot flaming-sheep'
    'fox:Mascot fox'
    'ghost:Mascot ghost'
    'ghostbusters:Mascot ghostbusters'
    'glados:Mascot glados'
    'goat:Mascot goat'
    'goat2:Mascot goat2'
    'golden-eagle:Mascot golden-eagle'
    'happy-whale:Mascot happy-whale'
    'hedgehog:Mascot hedgehog'
    'hellokitty:Mascot hellokitty'
    'hippie:Mascot hippie'
    'hiya:Mascot hiya'
    'hypno:Mascot hypno'
    'jellyfish:Mascot jellyfish'
    'jesus:Mascot jesus'
    'king:Mascot king'
    'kiss:Mascot kiss'
    'kitten:Mascot kitten'
    'kitty:Mascot kitty'
    'knight:Mascot knight'
    'koala:Mascot koala'
    'kosh:Mascot kosh'
    'lamb:Mascot lamb'
    'lamb2:Mascot lamb2'
    'lobster:Mascot lobster'
    'lollerskates:Mascot lollerskates'
    'luke-koala:Mascot luke-koala'
    'mech-and-cow:Mascot mech-and-cow'
    'meow:Mascot meow'
    'milk:Mascot milk'
    'minotaur:Mascot minotaur'
    'mona-lisa:Mascot mona-lisa'
    'moofasa:Mascot moofasa'
    'mooghidjirah:Mascot mooghidjirah'
    'moojira:Mascot moojira'
    'moose:Mascot moose'
    'mule:Mascot mule'
    'mutilated:Mascot mutilated'
    'nyan:Mascot nyan'
    'octopus:Mascot octopus'
    'owl:Mascot owl'
    'panther:Mascot panther'
    'pawn:Mascot pawn'
    'periodic-table:Mascot periodic-table'
    'personality-sphere:Mascot personality-sphere'
    'pig:Mascot pig'
    'pterodactyl:Mascot pterodactyl'
    'pufferfish:Mascot pufferfish'
    'queen:Mascot queen'
    'radioactive-kitty:Mascot radioactive-kitty'
    'ram:Mascot ram'
    'ren:Mascot ren'
    'rhino:Mascot rhino'
    'rook:Mascot rook'
    'rooster:Mascot rooster'
    'satanic:Mascot satanic'
    'sauron:Mascot sauron'
    'seahorse:Mascot seahorse'
    'seahorse-big:Mascot seahorse-big'
    'sheep:Mascot sheep'
    'shikato:Mascot shikato'
    'shrug:Mascot shrug'
    'skeleton:Mascot skeleton'
    'sloth:Mascot sloth'
    'small:Mascot small'
    'smiling-octopus:Mascot smiling-octopus'
    'snoopy:Mascot snoopy'
    'snoopyhouse:Mascot snoopyhouse'
    'snoopysleep:Mascot snoopysleep'
    'spidercow:Mascot spidercow'
    'squid:Mascot squid'
    'squirrel:Mascot squirrel'
    'stegosaurus:Mascot stegosaurus'
    'stimpy:Mascot stimpy'
    'supermilker:Mascot supermilker'
    'surgery:Mascot surgery'
    'telebears:Mascot telebears'
    'three-eyes:Mascot three-eyes'
    'tiger:Mascot tiger'
    'tortoise:Mascot tortoise'
    'turkey:Mascot turkey'
    'turtle:Mascot turtle'
    'tux:Mascot tux'
    'tux-big:Mascot tux-big'
    'tweety-bird:Mascot tweety-bird'
    'unipony:Mascot unipony'
    'vader:Mascot vader'
    'viper:Mascot viper'
    'vulpix:Mascot vulpix'
    'walrus:Mascot walrus'
    'weeping-angel:Mascot weeping-angel'
    'whale:Mascot whale'
    'wizard:Mascot wizard'
    'wolf:Mascot wolf'
    'world:Mascot world'
    'yoda:Mascot yoda'
    'random:Mascot random'
)
"#;
    script.push_str(zsh_extra);
    script
}

fn generate_fish_completions() -> String {
    r#"# forgum fish completion script with auto-suggestions
function __fish_forgum_no_subcommand
    set -l cmd (commandline -poc)
    test (count $cmd) -eq 1
end

complete -c forgum -f

# Subcommands
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'render' -d 'Render mascot animation (default)'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'think' -d 'Render in cowthink mode'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'fortune' -d 'Print a random fortune'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'options' -d 'Display available options in structured tables'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'completions' -d 'Install shell completions and attach to profile'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'init' -d 'Generate shell integration hook'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'tui' -d 'Launch interactive terminal UI'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'status' -d 'Print engine status'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'doctor' -d 'Diagnose configuration and capabilities'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'checkhealth' -d 'Run comprehensive system health check'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'config' -d 'View or edit configuration'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'logs' -d 'View, stream, or clear engine logs'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'herd' -d 'Fleet manager for background daemons'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'theme' -d 'Manage mascot theme'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'demo' -d 'Run showcase demo'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'showcase' -d 'Run 60-second demo reel'
complete -c forgum -n '__fish_forgum_no_subcommand' -a 'say' -d 'Run command and display output in speech bubble'

# Rich option value completions with descriptions
complete -c forgum -l effect -s e -d 'Animation effect' -x -a 'walk	"Natural bovine walking animation" breathe	"Gentle idle breathing animation" float	"Drifting levitation animation" fly	"Flying creature animation" talk	"Conversational jaw animation" sway	"Swaying pendulum animation" pulse	"Pulsing scale animation" glitch	"Digital cyberpunk glitch animation" particles	"Ambient particle emitter animation" dissolve	"Dissolve and materialize animation"'
complete -c forgum -l cow -l animal -s c -s a -d 'Animal mascot name' -x -a 'apt	"Mascot apt" armadillo	"Mascot armadillo" atat	"Mascot atat" bearface	"Mascot bearface" beavis.zen	"Mascot beavis.zen" bees	"Mascot bees" bill-the-cat	"Mascot bill-the-cat" bud-frogs	"Mascot bud-frogs" bunny	"Mascot bunny" cat	"Mascot cat" cat2	"Mascot cat2" catfence	"Mascot catfence" charizardvice	"Mascot charizardvice" charlie	"Mascot charlie" claw-arm	"Mascot claw-arm" corgi	"Mascot corgi" cower	"Mascot cower" cowfee	"Mascot cowfee" cthulhu-mini	"Mascot cthulhu-mini" daemon	"Mascot daemon" default	"Mascot default" docker-whale	"Mascot docker-whale" doge	"Mascot doge" dolphin	"Mascot dolphin" dragon	"Mascot dragon" dragon-and-cow	"Mascot dragon-and-cow" duck	"Mascot duck" ebi_furai	"Mascot ebi_furai" elephant	"Mascot elephant" elephant-in-snake	"Mascot elephant-in-snake" elephant2	"Mascot elephant2" eyes	"Mascot eyes" fat-banana	"Mascot fat-banana" fat-cow	"Mascot fat-cow" fence	"Mascot fence" flaming-sheep	"Mascot flaming-sheep" fox	"Mascot fox" ghost	"Mascot ghost" ghostbusters	"Mascot ghostbusters" glados	"Mascot glados" goat	"Mascot goat" goat2	"Mascot goat2" golden-eagle	"Mascot golden-eagle" happy-whale	"Mascot happy-whale" hedgehog	"Mascot hedgehog" hellokitty	"Mascot hellokitty" hippie	"Mascot hippie" hiya	"Mascot hiya" hypno	"Mascot hypno" jellyfish	"Mascot jellyfish" jesus	"Mascot jesus" king	"Mascot king" kiss	"Mascot kiss" kitten	"Mascot kitten" kitty	"Mascot kitty" knight	"Mascot knight" koala	"Mascot koala" kosh	"Mascot kosh" lamb	"Mascot lamb" lamb2	"Mascot lamb2" lobster	"Mascot lobster" lollerskates	"Mascot lollerskates" luke-koala	"Mascot luke-koala" mech-and-cow	"Mascot mech-and-cow" meow	"Mascot meow" milk	"Mascot milk" minotaur	"Mascot minotaur" mona-lisa	"Mascot mona-lisa" moofasa	"Mascot moofasa" mooghidjirah	"Mascot mooghidjirah" moojira	"Mascot moojira" moose	"Mascot moose" mule	"Mascot mule" mutilated	"Mascot mutilated" nyan	"Mascot nyan" octopus	"Mascot octopus" owl	"Mascot owl" panther	"Mascot panther" pawn	"Mascot pawn" periodic-table	"Mascot periodic-table" personality-sphere	"Mascot personality-sphere" pig	"Mascot pig" pterodactyl	"Mascot pterodactyl" pufferfish	"Mascot pufferfish" queen	"Mascot queen" radioactive-kitty	"Mascot radioactive-kitty" ram	"Mascot ram" ren	"Mascot ren" rhino	"Mascot rhino" rook	"Mascot rook" rooster	"Mascot rooster" satanic	"Mascot satanic" sauron	"Mascot sauron" seahorse	"Mascot seahorse" seahorse-big	"Mascot seahorse-big" sheep	"Mascot sheep" shikato	"Mascot shikato" shrug	"Mascot shrug" skeleton	"Mascot skeleton" sloth	"Mascot sloth" small	"Mascot small" smiling-octopus	"Mascot smiling-octopus" snoopy	"Mascot snoopy" snoopyhouse	"Mascot snoopyhouse" snoopysleep	"Mascot snoopysleep" spidercow	"Mascot spidercow" squid	"Mascot squid" squirrel	"Mascot squirrel" stegosaurus	"Mascot stegosaurus" stimpy	"Mascot stimpy" supermilker	"Mascot supermilker" surgery	"Mascot surgery" telebears	"Mascot telebears" three-eyes	"Mascot three-eyes" tiger	"Mascot tiger" tortoise	"Mascot tortoise" turkey	"Mascot turkey" turtle	"Mascot turtle" tux	"Mascot tux" tux-big	"Mascot tux-big" tweety-bird	"Mascot tweety-bird" unipony	"Mascot unipony" vader	"Mascot vader" viper	"Mascot viper" vulpix	"Mascot vulpix" walrus	"Mascot walrus" weeping-angel	"Mascot weeping-angel" whale	"Mascot whale" wizard	"Mascot wizard" wolf	"Mascot wolf" world	"Mascot world" yoda	"Mascot yoda" random	"Mascot random"'
complete -c forgum -l mountain -d 'Mountain/horizon style' -x -a 'hills	"Rolling verdant hills" peaks	"Jagged alpine peaks" volcano	"Active smoldering volcano" iceberg	"Frozen glacier ridges" skyline	"Urban skyscraper silhouette" seamount	"Underwater tectonic ridges" plateau	"Desert mesa and canyon ridges" crater	"Impact rim and astral ridge" gothic	"Spire and cathedral silhouette" castle	"Fortress ramparts" garden	"Terraced hedge and floral ridge" none	"Disable mountain horizon"'
complete -c forgum -l road -d 'Road/ground style' -x -a 'dirt	"Countryside dirt trail" cobblestone	"Medieval stone pavement" magma	"Cracked volcanic basalt" ice	"Packed crystalline ice" seabed	"Ripple sands and deep coral" sidewalk	"Paved urban asphalt" roof	"Ceramic roof shingles" grid	"Neon vector cyber grid" crypt	"Dark catacomb flagstones" savanna	"Sun-baked arid trail" mud	"Squishy wet soil" tracks	"Railroad ties" checkerboard	"High-contrast dual tiles" none	"Disable ground layer"'
complete -c forgum -l environment -d 'Environment particle effect' -x -a 'pasture	"Open meadows" inferno	"Blazing magma" ocean	"Aquatic realm" arctic	"Frozen tundra" city	"Metropolitan skyline" forest	"Ancient woodlands" savanna	"Golden plains" swamp	"Murky bayou" space	"Cosmos void" cyber	"Digital matrix" graveyard	"Gothic cemetery" jurassic	"Primeval wilds" hive	"Bio hive" throne	"Gothic sanctuary" none	"Disable particles"'
complete -c forgum -l color-mode -d 'Color rendering mode' -x -a 'animal	"Creature archetype colors" rainbow	"Dynamic oscillating spectrum" solid	"Single pure hue" none	"Monochrome terminal default"'
complete -c forgum -l text -s t -d 'Text inside the speech bubble'
complete -c forgum -l think -s T -d 'Render as thought bubble instead of speech bubble'
complete -c forgum -l background -s b -d 'Render above prompt as non-blocking overlay'
complete -c forgum -l banner -s B -d 'Render inline as animated banner above prompt'
complete -c forgum -l duration -s d -d 'Duration in seconds (0 = infinite)'
complete -c forgum -l fps -d 'Target frames per second'
complete -c forgum -l thought-interval -d 'Interval in seconds for rotating fortunes'
complete -c forgum -l split-scroll -d 'Lock scroll margins below animation'
complete -c forgum -l eyes -d 'Custom eyes (e.g. oo, $$, @@)'
complete -c forgum -l tongue -d 'Custom tongue (e.g. U)'
"#.to_string()
}

fn generate_powershell_completions() -> String {
    r#"# forgum PowerShell completion script with argument completer & tooltips
Register-ArgumentCompleter -Native -CommandName 'forgum' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $elements = $commandAst.CommandElements
    $prevWord = if ($elements.Count -ge 2) { $elements[-2].Extent.Text } else { '' }

    $effects = @{
        'walk' = 'Natural bovine walking animation'
        'breathe' = 'Gentle breathing idle animation'
        'float' = 'Drifting levitation animation'
        'fly' = 'Flying creature animation'
        'talk' = 'Conversational speech animation'
        'sway' = 'Swaying pendulum animation'
        'pulse' = 'Pulsing scale animation'
        'glitch' = 'Digital cyberpunk glitch animation'
        'particles' = 'Ambient particle emitter animation'
        'dissolve' = 'Dissolve and materialize animation'
    }

    $mountains = @{
        'hills' = 'Rolling verdant hills'
        'peaks' = 'Jagged alpine mountain peaks'
        'volcano' = 'Active smoldering volcano'
        'iceberg' = 'Frozen glacier ridges'
        'skyline' = 'Urban skyscraper silhouette'
        'seamount' = 'Underwater tectonic ridges'
        'plateau' = 'Desert mesa and canyon ridges'
        'crater' = 'Impact rim and astral ridge'
        'gothic' = 'Spire and cathedral silhouette'
        'castle' = 'Fortress ramparts and battlements'
        'garden' = 'Terraced hedge and floral ridge'
        'none' = 'Disable mountain horizon'
    }

    $roads = @{
        'dirt' = 'Countryside dirt trail'
        'cobblestone' = 'Medieval stone pavement'
        'magma' = 'Cracked volcanic basalt'
        'ice' = 'Packed snow and crystalline ice'
        'seabed' = 'Ripple sands and deep coral'
        'sidewalk' = 'Paved urban asphalt'
        'roof' = 'Ceramic roof shingles'
        'grid' = 'Neon vector cyber grid'
        'crypt' = 'Dark catacomb flagstones'
        'savanna' = 'Sun-baked arid trail'
        'mud' = 'Squishy wet soil'
        'tracks' = 'Parallel steel railroad ties'
        'checkerboard' = 'High-contrast dual tiles'
        'none' = 'Disable ground layer'
    }

    $environments = @{
        'pasture' = 'Peaceful open meadows'
        'inferno' = 'Blazing magma chambers'
        'ocean' = 'Deep sea aquatic realm'
        'arctic' = 'Frozen tundra and blizzard'
        'city' = 'Bustling metropolitan skyline'
        'forest' = 'Ancient whispering woodlands'
        'savanna' = 'Sun-drenched golden plains'
        'swamp' = 'Murky bayou and mist'
        'space' = 'Deep cosmos and stellar void'
        'cyber' = 'Neon digital matrix'
        'graveyard' = 'Foggy gothic cemetery'
        'jurassic' = 'Prehistoric primeval wilds'
        'hive' = 'Organic bio-mechanical hive'
        'throne' = 'Imperial gothic sanctuary'
        'none' = 'Disable particle effects'
    }

    $colors = @{
        'animal' = 'Archetype creature colors'
        'rainbow' = 'Dynamic oscillating spectrum'
        'solid' = 'Single pure hue'
        'none' = 'Monochrome terminal default'
    }

    $animals = @{
        'apt' = 'Mascot apt'
        'armadillo' = 'Mascot armadillo'
        'atat' = 'Mascot atat'
        'bearface' = 'Mascot bearface'
        'beavis.zen' = 'Mascot beavis.zen'
        'bees' = 'Mascot bees'
        'bill-the-cat' = 'Mascot bill-the-cat'
        'bud-frogs' = 'Mascot bud-frogs'
        'bunny' = 'Mascot bunny'
        'cat' = 'Mascot cat'
        'cat2' = 'Mascot cat2'
        'catfence' = 'Mascot catfence'
        'charizardvice' = 'Mascot charizardvice'
        'charlie' = 'Mascot charlie'
        'claw-arm' = 'Mascot claw-arm'
        'corgi' = 'Mascot corgi'
        'cower' = 'Mascot cower'
        'cowfee' = 'Mascot cowfee'
        'cthulhu-mini' = 'Mascot cthulhu-mini'
        'daemon' = 'Mascot daemon'
        'default' = 'Mascot default'
        'docker-whale' = 'Mascot docker-whale'
        'doge' = 'Mascot doge'
        'dolphin' = 'Mascot dolphin'
        'dragon' = 'Mascot dragon'
        'dragon-and-cow' = 'Mascot dragon-and-cow'
        'duck' = 'Mascot duck'
        'ebi_furai' = 'Mascot ebi_furai'
        'elephant' = 'Mascot elephant'
        'elephant-in-snake' = 'Mascot elephant-in-snake'
        'elephant2' = 'Mascot elephant2'
        'eyes' = 'Mascot eyes'
        'fat-banana' = 'Mascot fat-banana'
        'fat-cow' = 'Mascot fat-cow'
        'fence' = 'Mascot fence'
        'flaming-sheep' = 'Mascot flaming-sheep'
        'fox' = 'Mascot fox'
        'ghost' = 'Mascot ghost'
        'ghostbusters' = 'Mascot ghostbusters'
        'glados' = 'Mascot glados'
        'goat' = 'Mascot goat'
        'goat2' = 'Mascot goat2'
        'golden-eagle' = 'Mascot golden-eagle'
        'happy-whale' = 'Mascot happy-whale'
        'hedgehog' = 'Mascot hedgehog'
        'hellokitty' = 'Mascot hellokitty'
        'hippie' = 'Mascot hippie'
        'hiya' = 'Mascot hiya'
        'hypno' = 'Mascot hypno'
        'jellyfish' = 'Mascot jellyfish'
        'jesus' = 'Mascot jesus'
        'king' = 'Mascot king'
        'kiss' = 'Mascot kiss'
        'kitten' = 'Mascot kitten'
        'kitty' = 'Mascot kitty'
        'knight' = 'Mascot knight'
        'koala' = 'Mascot koala'
        'kosh' = 'Mascot kosh'
        'lamb' = 'Mascot lamb'
        'lamb2' = 'Mascot lamb2'
        'lobster' = 'Mascot lobster'
        'lollerskates' = 'Mascot lollerskates'
        'luke-koala' = 'Mascot luke-koala'
        'mech-and-cow' = 'Mascot mech-and-cow'
        'meow' = 'Mascot meow'
        'milk' = 'Mascot milk'
        'minotaur' = 'Mascot minotaur'
        'mona-lisa' = 'Mascot mona-lisa'
        'moofasa' = 'Mascot moofasa'
        'mooghidjirah' = 'Mascot mooghidjirah'
        'moojira' = 'Mascot moojira'
        'moose' = 'Mascot moose'
        'mule' = 'Mascot mule'
        'mutilated' = 'Mascot mutilated'
        'nyan' = 'Mascot nyan'
        'octopus' = 'Mascot octopus'
        'owl' = 'Mascot owl'
        'panther' = 'Mascot panther'
        'pawn' = 'Mascot pawn'
        'periodic-table' = 'Mascot periodic-table'
        'personality-sphere' = 'Mascot personality-sphere'
        'pig' = 'Mascot pig'
        'pterodactyl' = 'Mascot pterodactyl'
        'pufferfish' = 'Mascot pufferfish'
        'queen' = 'Mascot queen'
        'radioactive-kitty' = 'Mascot radioactive-kitty'
        'ram' = 'Mascot ram'
        'ren' = 'Mascot ren'
        'rhino' = 'Mascot rhino'
        'rook' = 'Mascot rook'
        'rooster' = 'Mascot rooster'
        'satanic' = 'Mascot satanic'
        'sauron' = 'Mascot sauron'
        'seahorse' = 'Mascot seahorse'
        'seahorse-big' = 'Mascot seahorse-big'
        'sheep' = 'Mascot sheep'
        'shikato' = 'Mascot shikato'
        'shrug' = 'Mascot shrug'
        'skeleton' = 'Mascot skeleton'
        'sloth' = 'Mascot sloth'
        'small' = 'Mascot small'
        'smiling-octopus' = 'Mascot smiling-octopus'
        'snoopy' = 'Mascot snoopy'
        'snoopyhouse' = 'Mascot snoopyhouse'
        'snoopysleep' = 'Mascot snoopysleep'
        'spidercow' = 'Mascot spidercow'
        'squid' = 'Mascot squid'
        'squirrel' = 'Mascot squirrel'
        'stegosaurus' = 'Mascot stegosaurus'
        'stimpy' = 'Mascot stimpy'
        'supermilker' = 'Mascot supermilker'
        'surgery' = 'Mascot surgery'
        'telebears' = 'Mascot telebears'
        'three-eyes' = 'Mascot three-eyes'
        'tiger' = 'Mascot tiger'
        'tortoise' = 'Mascot tortoise'
        'turkey' = 'Mascot turkey'
        'turtle' = 'Mascot turtle'
        'tux' = 'Mascot tux'
        'tux-big' = 'Mascot tux-big'
        'tweety-bird' = 'Mascot tweety-bird'
        'unipony' = 'Mascot unipony'
        'vader' = 'Mascot vader'
        'viper' = 'Mascot viper'
        'vulpix' = 'Mascot vulpix'
        'walrus' = 'Mascot walrus'
        'weeping-angel' = 'Mascot weeping-angel'
        'whale' = 'Mascot whale'
        'wizard' = 'Mascot wizard'
        'wolf' = 'Mascot wolf'
        'world' = 'Mascot world'
        'yoda' = 'Mascot yoda'
        'random' = 'Mascot random'
    }

    $targetMap = $null
    switch ($prevWord) {
        { $_ -in '--effect', '-e' } { $targetMap = $effects }
        '--mountain' { $targetMap = $mountains }
        '--road' { $targetMap = $roads }
        '--environment' { $targetMap = $environments }
        '--color-mode' { $targetMap = $colors }
        { $_ -in '--cow', '--animal', '-a' } { $targetMap = $animals }
    }

    if ($targetMap) {
        $targetMap.GetEnumerator() | Where-Object { $_.Key -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_.Key, $_.Key, 'ParameterValue', $_.Value)
        }
        return
    }

    $flags = @(
        '--cow', '--animal', '--effect', '--mountain', '--road', '--environment',
        '--color-mode', '--text', '--think', '--background', '--banner',
        '--duration', '--fps', '--thought-interval', '--split-scroll',
        '--eyes', '--tongue', '--palette'
    )
    $subcommands = @(
        'render', 'think', 'fortune', 'options', 'completions', 'init', 'tui',
        'status', 'doctor', 'checkhealth', 'config', 'logs', 'herd', 'theme',
        'demo', 'showcase', 'say'
    )

    if ($wordToComplete -like '-*') {
        $flags | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
        }
    } else {
        $subcommands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'Command', $_)
        }
    }
}
"#.to_string()
}

fn generate_elvish_completions(cmd: &mut clap::Command) -> String {
    let mut buf = Vec::new();
    generate(shells::Elvish, cmd, "forgum", &mut buf);
    String::from_utf8_lossy(&buf).into_owned()
}

fn generate_nushell_completions() -> String {
    r#"# forgum nushell completion definitions
export extern "forgum" [
    --cow(-c): string@"nu_forgum_animals"              # Animal mascot name
    --animal(-a): string@"nu_forgum_animals"           # Animal mascot name
    --effect(-e): string@"nu_forgum_effects"           # Animation effect
    --mountain: string@"nu_forgum_mountains"           # Mountain/horizon style
    --road: string@"nu_forgum_roads"                   # Road/ground style
    --environment: string@"nu_forgum_environments"     # Environment particle effect
    --color-mode: string@"nu_forgum_colors"            # Color mode
    --text(-t): string                                 # Text inside speech bubble
    --think(-T)                                        # Render in cowthink mode
    --background(-b)                                   # Non-blocking overlay above prompt
    --banner(-B)                                       # Inline banner above prompt
    --duration(-d): int                                # Duration in seconds
    --fps: int                                         # Target FPS
    --thought-interval: int                            # Seconds between thought rotations
    --split-scroll                                     # Lock scroll margins below animation
]

def "nu_forgum_effects" [] {
    [
        { value: "walk", description: "Natural bovine walking animation" },
        { value: "breathe", description: "Gentle breathing idle animation" },
        { value: "float", description: "Drifting levitation animation" },
        { value: "fly", description: "Flying creature animation" },
        { value: "talk", description: "Conversational speech animation" },
        { value: "sway", description: "Swaying pendulum animation" },
        { value: "pulse", description: "Pulsing scale animation" },
        { value: "glitch", description: "Digital cyberpunk glitch animation" },
        { value: "particles", description: "Ambient particle emitter animation" },
        { value: "dissolve", description: "Dissolve and materialize animation" }
    ]
}

def "nu_forgum_mountains" [] {
    [
        { value: "hills", description: "Rolling verdant hills" },
        { value: "peaks", description: "Jagged alpine mountain peaks" },
        { value: "volcano", description: "Active smoldering volcano" },
        { value: "iceberg", description: "Frozen glacier ridges" },
        { value: "skyline", description: "Urban skyscraper silhouette" },
        { value: "seamount", description: "Underwater tectonic ridges" },
        { value: "plateau", description: "Desert mesa and canyon ridges" },
        { value: "crater", description: "Impact rim and astral ridge" },
        { value: "gothic", description: "Spire and cathedral silhouette" },
        { value: "castle", description: "Fortress ramparts and battlements" },
        { value: "garden", description: "Terraced hedge and floral ridge" },
        { value: "none", description: "Disable mountain horizon" }
    ]
}

def "nu_forgum_roads" [] {
    [
        { value: "dirt", description: "Countryside dirt trail" },
        { value: "cobblestone", description: "Medieval stone pavement" },
        { value: "magma", description: "Cracked volcanic basalt" },
        { value: "ice", description: "Packed crystalline ice" },
        { value: "seabed", description: "Ripple sands and deep coral" },
        { value: "sidewalk", description: "Paved urban asphalt" },
        { value: "roof", description: "Ceramic roof shingles" },
        { value: "grid", description: "Neon vector cyber grid" },
        { value: "crypt", description: "Dark catacomb flagstones" },
        { value: "savanna", description: "Sun-baked arid trail" },
        { value: "mud", description: "Squishy wet soil" },
        { value: "tracks", description: "Railroad ties" },
        { value: "checkerboard", description: "High-contrast dual tiles" },
        { value: "none", description: "Disable ground layer" }
    ]
}

def "nu_forgum_environments" [] {
    [
        { value: "pasture", description: "Open meadows" },
        { value: "inferno", description: "Blazing magma" },
        { value: "ocean", description: "Aquatic realm" },
        { value: "arctic", description: "Frozen tundra" },
        { value: "city", description: "Metropolitan skyline" },
        { value: "forest", description: "Ancient woodlands" },
        { value: "savanna", description: "Golden plains" },
        { value: "swamp", description: "Murky bayou" },
        { value: "space", description: "Cosmos void" },
        { value: "cyber", description: "Digital matrix" },
        { value: "graveyard", description: "Gothic cemetery" },
        { value: "jurassic", description: "Primeval wilds" },
        { value: "hive", description: "Bio hive" },
        { value: "throne", description: "Gothic sanctuary" },
        { value: "none", description: "Disable particles" }
    ]
}

def "nu_forgum_colors" [] {
    [
        { value: "animal", description: "Creature archetype colors" },
        { value: "rainbow", description: "Dynamic spectrum" },
        { value: "solid", description: "Single pure hue" },
        { value: "none", description: "Monochrome terminal default" }
    ]
}

def "nu_forgum_animals" [] {
    [
        { value: "apt", description: "Mascot apt" },
        { value: "armadillo", description: "Mascot armadillo" },
        { value: "atat", description: "Mascot atat" },
        { value: "bearface", description: "Mascot bearface" },
        { value: "beavis.zen", description: "Mascot beavis.zen" },
        { value: "bees", description: "Mascot bees" },
        { value: "bill-the-cat", description: "Mascot bill-the-cat" },
        { value: "bud-frogs", description: "Mascot bud-frogs" },
        { value: "bunny", description: "Mascot bunny" },
        { value: "cat", description: "Mascot cat" },
        { value: "cat2", description: "Mascot cat2" },
        { value: "catfence", description: "Mascot catfence" },
        { value: "charizardvice", description: "Mascot charizardvice" },
        { value: "charlie", description: "Mascot charlie" },
        { value: "claw-arm", description: "Mascot claw-arm" },
        { value: "corgi", description: "Mascot corgi" },
        { value: "cower", description: "Mascot cower" },
        { value: "cowfee", description: "Mascot cowfee" },
        { value: "cthulhu-mini", description: "Mascot cthulhu-mini" },
        { value: "daemon", description: "Mascot daemon" },
        { value: "default", description: "Mascot default" },
        { value: "docker-whale", description: "Mascot docker-whale" },
        { value: "doge", description: "Mascot doge" },
        { value: "dolphin", description: "Mascot dolphin" },
        { value: "dragon", description: "Mascot dragon" },
        { value: "dragon-and-cow", description: "Mascot dragon-and-cow" },
        { value: "duck", description: "Mascot duck" },
        { value: "ebi_furai", description: "Mascot ebi_furai" },
        { value: "elephant", description: "Mascot elephant" },
        { value: "elephant-in-snake", description: "Mascot elephant-in-snake" },
        { value: "elephant2", description: "Mascot elephant2" },
        { value: "eyes", description: "Mascot eyes" },
        { value: "fat-banana", description: "Mascot fat-banana" },
        { value: "fat-cow", description: "Mascot fat-cow" },
        { value: "fence", description: "Mascot fence" },
        { value: "flaming-sheep", description: "Mascot flaming-sheep" },
        { value: "fox", description: "Mascot fox" },
        { value: "ghost", description: "Mascot ghost" },
        { value: "ghostbusters", description: "Mascot ghostbusters" },
        { value: "glados", description: "Mascot glados" },
        { value: "goat", description: "Mascot goat" },
        { value: "goat2", description: "Mascot goat2" },
        { value: "golden-eagle", description: "Mascot golden-eagle" },
        { value: "happy-whale", description: "Mascot happy-whale" },
        { value: "hedgehog", description: "Mascot hedgehog" },
        { value: "hellokitty", description: "Mascot hellokitty" },
        { value: "hippie", description: "Mascot hippie" },
        { value: "hiya", description: "Mascot hiya" },
        { value: "hypno", description: "Mascot hypno" },
        { value: "jellyfish", description: "Mascot jellyfish" },
        { value: "jesus", description: "Mascot jesus" },
        { value: "king", description: "Mascot king" },
        { value: "kiss", description: "Mascot kiss" },
        { value: "kitten", description: "Mascot kitten" },
        { value: "kitty", description: "Mascot kitty" },
        { value: "knight", description: "Mascot knight" },
        { value: "koala", description: "Mascot koala" },
        { value: "kosh", description: "Mascot kosh" },
        { value: "lamb", description: "Mascot lamb" },
        { value: "lamb2", description: "Mascot lamb2" },
        { value: "lobster", description: "Mascot lobster" },
        { value: "lollerskates", description: "Mascot lollerskates" },
        { value: "luke-koala", description: "Mascot luke-koala" },
        { value: "mech-and-cow", description: "Mascot mech-and-cow" },
        { value: "meow", description: "Mascot meow" },
        { value: "milk", description: "Mascot milk" },
        { value: "minotaur", description: "Mascot minotaur" },
        { value: "mona-lisa", description: "Mascot mona-lisa" },
        { value: "moofasa", description: "Mascot moofasa" },
        { value: "mooghidjirah", description: "Mascot mooghidjirah" },
        { value: "moojira", description: "Mascot moojira" },
        { value: "moose", description: "Mascot moose" },
        { value: "mule", description: "Mascot mule" },
        { value: "mutilated", description: "Mascot mutilated" },
        { value: "nyan", description: "Mascot nyan" },
        { value: "octopus", description: "Mascot octopus" },
        { value: "owl", description: "Mascot owl" },
        { value: "panther", description: "Mascot panther" },
        { value: "pawn", description: "Mascot pawn" },
        { value: "periodic-table", description: "Mascot periodic-table" },
        { value: "personality-sphere", description: "Mascot personality-sphere" },
        { value: "pig", description: "Mascot pig" },
        { value: "pterodactyl", description: "Mascot pterodactyl" },
        { value: "pufferfish", description: "Mascot pufferfish" },
        { value: "queen", description: "Mascot queen" },
        { value: "radioactive-kitty", description: "Mascot radioactive-kitty" },
        { value: "ram", description: "Mascot ram" },
        { value: "ren", description: "Mascot ren" },
        { value: "rhino", description: "Mascot rhino" },
        { value: "rook", description: "Mascot rook" },
        { value: "rooster", description: "Mascot rooster" },
        { value: "satanic", description: "Mascot satanic" },
        { value: "sauron", description: "Mascot sauron" },
        { value: "seahorse", description: "Mascot seahorse" },
        { value: "seahorse-big", description: "Mascot seahorse-big" },
        { value: "sheep", description: "Mascot sheep" },
        { value: "shikato", description: "Mascot shikato" },
        { value: "shrug", description: "Mascot shrug" },
        { value: "skeleton", description: "Mascot skeleton" },
        { value: "sloth", description: "Mascot sloth" },
        { value: "small", description: "Mascot small" },
        { value: "smiling-octopus", description: "Mascot smiling-octopus" },
        { value: "snoopy", description: "Mascot snoopy" },
        { value: "snoopyhouse", description: "Mascot snoopyhouse" },
        { value: "snoopysleep", description: "Mascot snoopysleep" },
        { value: "spidercow", description: "Mascot spidercow" },
        { value: "squid", description: "Mascot squid" },
        { value: "squirrel", description: "Mascot squirrel" },
        { value: "stegosaurus", description: "Mascot stegosaurus" },
        { value: "stimpy", description: "Mascot stimpy" },
        { value: "supermilker", description: "Mascot supermilker" },
        { value: "surgery", description: "Mascot surgery" },
        { value: "telebears", description: "Mascot telebears" },
        { value: "three-eyes", description: "Mascot three-eyes" },
        { value: "tiger", description: "Mascot tiger" },
        { value: "tortoise", description: "Mascot tortoise" },
        { value: "turkey", description: "Mascot turkey" },
        { value: "turtle", description: "Mascot turtle" },
        { value: "tux", description: "Mascot tux" },
        { value: "tux-big", description: "Mascot tux-big" },
        { value: "tweety-bird", description: "Mascot tweety-bird" },
        { value: "unipony", description: "Mascot unipony" },
        { value: "vader", description: "Mascot vader" },
        { value: "viper", description: "Mascot viper" },
        { value: "vulpix", description: "Mascot vulpix" },
        { value: "walrus", description: "Mascot walrus" },
        { value: "weeping-angel", description: "Mascot weeping-angel" },
        { value: "whale", description: "Mascot whale" },
        { value: "wizard", description: "Mascot wizard" },
        { value: "wolf", description: "Mascot wolf" },
        { value: "world", description: "Mascot world" },
        { value: "yoda", description: "Mascot yoda" },
        { value: "random", description: "Mascot random" },
    ]
},
        { value: "dragon", description: "Fire-breathing dragon" },
        { value: "tux", description: "Linux penguin mascot" },
        { value: "cat", description: "Playful feline mascot" },
        { value: "ghost", description: "Spooky floating phantom" },
        { value: "elephant", description: "Gentle giant" },
        { value: "bunny", description: "Cute rabbit mascot" },
        { value: "corgi", description: "Playful corgi" },
        { value: "fox", description: "Clever woodland fox" },
        { value: "random", description: "Pick random mascot" }
    ]
}
"#
    .to_string()
}

fn generate_carapace_spec() -> String {
    r#"# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: forgum
description: Modern animated terminal mascot engine
flags:
  --cow=: Animal mascot name
  --animal=: Animal mascot name
  --effect=: Animation effect
  --mountain=: Mountain / horizon style
  --road=: Road / ground style
  --environment=: Environment particle effect
  --color-mode=: Color rendering mode
  --text=: Text inside speech bubble
  --duration=: Duration in seconds (0 = infinite)
  --fps=: Target frames per second
  --thought-interval=: Interval in seconds for thought rotation
  --eyes=: Custom eyes string
  --tongue=: Custom tongue string
  --palette=: Custom hex palette
  --think: Render in cowthink mode
  --background: Render above prompt as non-blocking overlay
  --banner: Render inline as animated banner
  --split-scroll: Lock terminal scroll margins below animation
completion:
  flag:
    cow: ["default\tStandard bovine mascot", "dragon\tFire-breathing dragon", "tux\tLinux penguin", "cat\tPlayful feline", "ghost\tSpooky phantom", "elephant\tGentle giant", "bunny\tCute rabbit", "corgi\tPlayful corgi", "fox\tWoodland fox", "random\tPick random mascot"]
    animal: ["default\tStandard bovine mascot", "dragon\tFire-breathing dragon", "tux\tLinux penguin", "cat\tPlayful feline", "ghost\tSpooky phantom", "elephant\tGentle giant", "bunny\tCute rabbit", "corgi\tPlayful corgi", "fox\tWoodland fox", "random\tPick random mascot"]
    effect: ["walk\tNatural bovine walking animation", "breathe\tGentle breathing idle animation", "float\tDrifting levitation animation", "fly\tFlying creature animation", "talk\tConversational speech animation", "sway\tSwaying pendulum animation", "pulse\tPulsing scale animation", "glitch\tDigital cyberpunk glitch animation", "particles\tAmbient particle emitter animation", "dissolve\tDissolve and materialize animation"]
    mountain: ["hills\tRolling verdant hills", "peaks\tAlpine peaks", "volcano\tActive volcano", "iceberg\tGlacier ridges", "skyline\tUrban skyline", "seamount\tUnderwater ridges", "plateau\tDesert mesa", "crater\tImpact rim", "gothic\tSpire silhouette", "castle\tFortress ramparts", "garden\tTerraced hedge", "none\tDisable mountains"]
    road: ["dirt\tCountryside dirt trail", "cobblestone\tStone pavement", "magma\tVolcanic basalt", "ice\tPacked crystalline ice", "seabed\tRipple sands", "sidewalk\tPaved asphalt", "roof\tRoof shingles", "grid\tNeon cyber grid", "crypt\tCatacomb flagstones", "savanna\tArid trail", "mud\tSquishy soil", "tracks\tRailroad ties", "checkerboard\tDual tiles", "none\tDisable road"]
    environment: ["pasture\tOpen meadows", "inferno\tBlazing magma", "ocean\tAquatic realm", "arctic\tFrozen tundra", "city\tMetropolitan skyline", "forest\tAncient woodlands", "savanna\tGolden plains", "swamp\tMurky bayou", "space\tCosmos void", "cyber\tDigital matrix", "graveyard\tGothic cemetery", "jurassic\tPrimeval wilds", "hive\tBio hive", "throne\tGothic sanctuary", "none\tDisable particles"]
    color-mode: ["animal\tCreature archetype colors", "rainbow\tDynamic spectrum", "solid\tSingle pure hue", "none\tMonochrome terminal default"]
commands:
  - name: render
    description: Render mascot animation (default)
  - name: think
    description: Render in cowthink mode
  - name: fortune
    description: Print a random fortune
  - name: options
    description: Display available options in structured tables
  - name: completions
    description: Install shell completions and attach to profile
  - name: init
    description: Generate shell integration hook
  - name: tui
    description: Interactive terminal UI
  - name: status
    description: Print engine status
  - name: doctor
    description: Diagnose configuration and capabilities
  - name: checkhealth
    description: Run comprehensive system health check
  - name: config
    description: View or edit configuration
  - name: logs
    description: View, stream, or clear engine logs
  - name: herd
    description: Fleet manager for background daemons
  - name: theme
    description: Manage mascot theme
  - name: demo
    description: Run showcase demo
  - name: showcase
    description: Run 60-second demo reel
  - name: say
    description: Run command and display output in speech bubble
"#.to_string()
}

fn generate_xonsh_completions() -> String {
    r#"# Xonsh completion specification for Forgum
from xonsh.completers.tools import *

@contextual_command_completer_for("forgum")
def _forgum_completer(command):
    opts = {
        "--animal", "--cow", "-a", "--effect", "-e", "--mountain", "--road",
        "--environment", "--color-mode", "--text", "--duration", "-d",
        "--fps", "--thought-interval", "--eyes", "--tongue", "--palette",
        "--think", "--background", "-b", "--banner", "-B", "--split-scroll",
        "render", "think", "fortune", "options", "list", "completions",
        "init", "tui", "status", "doctor", "checkhealth", "config", "logs",
        "herd", "theme", "demo", "showcase", "say", "help"
    }
    return opts
"#
    .to_string()
}

fn generate_tcsh_completions() -> String {
    r#"# Tcsh completion for Forgum
complete forgum \
  'c/--cow/(default dragon tux cat ghost elephant bunny corgi fox octopus random)/' \
  'c/--animal/(default dragon tux cat ghost elephant bunny corgi fox octopus random)/' \
  'c/-a/(default dragon tux cat ghost elephant bunny corgi fox octopus random)/' \
  'c/--effect/(walk breathe float fly talk sway pulse glitch particles dissolve)/' \
  'c/-e/(walk breathe float fly talk sway pulse glitch particles dissolve)/' \
  'c/--mountain/(hills peaks volcano iceberg skyline seamount plateau crater gothic castle garden none)/' \
  'c/--road/(dirt cobblestone magma ice seabed sidewalk roof grid crypt savanna mud tracks checkerboard none)/' \
  'c/--environment/(pasture inferno ocean arctic city forest savanna swamp space cyber graveyard jurassic hive throne none)/' \
  'c/--color-mode/(animal rainbow solid none)/' \
  'n/completions/(bash zsh fish pwsh powershell elvish nushell carapace xonsh tcsh ksh ion oil yash list)/' \
  'n/init/(bash zsh fish pwsh powershell elvish nushell carapace xonsh tcsh ksh ion oil yash cmd list)/' \
  'p/1/(render think fortune options list completions init tui status doctor checkhealth config logs herd theme demo showcase say help)/'
"#.to_string()
}

fn generate_ksh_completions(cmd: &mut clap::Command) -> String {
    generate_bash_completions(cmd)
}

fn generate_ion_completions() -> String {
    r#"# Ion completion for Forgum
complete -c forgum -a "render think fortune list completions init tui status doctor checkhealth config logs herd theme demo showcase say help"
complete -c forgum -l animal -a "apt armadillo atat bearface beavis.zen bees bill-the-cat bud-frogs bunny cat cat2 catfence charizardvice charlie claw-arm corgi cower cowfee cthulhu-mini daemon default docker-whale doge dolphin dragon dragon-and-cow duck ebi_furai elephant elephant-in-snake elephant2 eyes fat-banana fat-cow fence flaming-sheep fox ghost ghostbusters glados goat goat2 golden-eagle happy-whale hedgehog hellokitty hippie hiya hypno jellyfish jesus king kiss kitten kitty knight koala kosh lamb lamb2 lobster lollerskates luke-koala mech-and-cow meow milk minotaur mona-lisa moofasa mooghidjirah moojira moose mule mutilated nyan octopus owl panther pawn periodic-table personality-sphere pig pterodactyl pufferfish queen radioactive-kitty ram ren rhino rook rooster satanic sauron seahorse seahorse-big sheep shikato shrug skeleton sloth small smiling-octopus snoopy snoopyhouse snoopysleep spidercow squid squirrel stegosaurus stimpy supermilker surgery telebears three-eyes tiger tortoise turkey turtle tux tux-big tweety-bird unipony vader viper vulpix walrus weeping-angel whale wizard wolf world yoda random"
complete -c forgum -l cow -a "apt armadillo atat bearface beavis.zen bees bill-the-cat bud-frogs bunny cat cat2 catfence charizardvice charlie claw-arm corgi cower cowfee cthulhu-mini daemon default docker-whale doge dolphin dragon dragon-and-cow duck ebi_furai elephant elephant-in-snake elephant2 eyes fat-banana fat-cow fence flaming-sheep fox ghost ghostbusters glados goat goat2 golden-eagle happy-whale hedgehog hellokitty hippie hiya hypno jellyfish jesus king kiss kitten kitty knight koala kosh lamb lamb2 lobster lollerskates luke-koala mech-and-cow meow milk minotaur mona-lisa moofasa mooghidjirah moojira moose mule mutilated nyan octopus owl panther pawn periodic-table personality-sphere pig pterodactyl pufferfish queen radioactive-kitty ram ren rhino rook rooster satanic sauron seahorse seahorse-big sheep shikato shrug skeleton sloth small smiling-octopus snoopy snoopyhouse snoopysleep spidercow squid squirrel stegosaurus stimpy supermilker surgery telebears three-eyes tiger tortoise turkey turtle tux tux-big tweety-bird unipony vader viper vulpix walrus weeping-angel whale wizard wolf world yoda random"
complete -c forgum -l effect -a "walk breathe float fly talk sway pulse glitch particles dissolve"
complete -c forgum -l mountain -a "hills peaks volcano iceberg skyline seamount plateau crater gothic castle garden none"
complete -c forgum -l road -a "dirt cobblestone magma ice seabed sidewalk roof grid crypt savanna mud tracks checkerboard none"
complete -c forgum -l environment -a "pasture inferno ocean arctic city forest savanna swamp space cyber graveyard jurassic hive throne none"
complete -c forgum -l color-mode -a "animal rainbow solid none"
complete -c forgum -l background
complete -c forgum -l banner
"#.to_string()
}

fn generate_oil_completions(cmd: &mut clap::Command) -> String {
    generate_bash_completions(cmd)
}

fn generate_yash_completions() -> String {
    r#"# Yash completion for Forgum
function completion/forgum {
    typeset -a commands
    commands=(render think fortune list completions init tui status doctor checkhealth config logs herd theme demo showcase say help)
    complete -c commands
}
"#.to_string()
}
