//! Shell hook generation for `forgum init <shell>`.
//!
//! Generates shell-specific hooks that:
//! 1. Resolve the engine path (baked at init time)
//! 2. Call `forgum-engine render` with argv flags (no JSON in shell)
//! 3. Sweep dead daemons on precmd
//!
//! Supported shells: bash, zsh, fish, pwsh.

use std::fmt;

/// Supported shell types.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Shell {
    Bash,
    Zsh,
    Fish,
    Pwsh,
}

impl Shell {
    /// Parse a shell name string.
    pub fn parse(name: &str) -> Option<Self> {
        match name.to_lowercase().as_str() {
            "bash" => Some(Shell::Bash),
            "zsh" => Some(Shell::Zsh),
            "fish" => Some(Shell::Fish),
            "pwsh" | "powershell" => Some(Shell::Pwsh),
            _ => None,
        }
    }

    /// Default config file path for this shell.
    pub fn default_config_path(&self) -> &str {
        match self {
            Shell::Bash | Shell::Zsh | Shell::Fish => "$HOME/.config/Forgum/config.json",
            Shell::Pwsh => "$env:APPDATA\\Forgum\\config.json",
        }
    }
}

impl fmt::Display for Shell {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Shell::Bash => write!(f, "bash"),
            Shell::Zsh => write!(f, "zsh"),
            Shell::Fish => write!(f, "fish"),
            Shell::Pwsh => write!(f, "pwsh"),
        }
    }
}

/// Generate a shell hook script.
///
/// `engine_path` is the absolute path to `forgum-engine`, baked in at init time.
pub fn generate_hook(shell: Shell, engine_path: &str) -> String {
    match shell {
        Shell::Bash => generate_bash_hook(engine_path),
        Shell::Zsh => generate_zsh_hook(engine_path),
        Shell::Fish => generate_fish_hook(engine_path),
        Shell::Pwsh => generate_pwsh_hook(engine_path),
    }
}

fn generate_bash_hook(engine: &str) -> String {
    format!(
        r#"# >>> forgum (bash) >>>
# Generated by forgum-engine init bash — do not edit by hand
__FORGUM_ENGINE="{engine}"
__FORGUM_CONFIG="${{FORGUM_CONFIG:-$HOME/.config/Forgum/config.json}}"
__FORGUM_RUNTIME="${{XDG_RUNTIME_DIR:-/tmp/forgum-$UID}}/forgum"
mkdir -p "$__FORGUM_RUNTIME"

forgum() {{
  local text="$*"
  if [ -z "$text" ]; then
    text="$("$__FORGUM_ENGINE" fortune 2>/dev/null)"
  fi
  "$__FORGUM_ENGINE" render \
    --config "$__FORGUM_CONFIG" \
    --text "$text" \
    --background --duration 0 "$@"
}}

__forgum_precmd() {{
  local state="$__FORGUM_RUNTIME/daemon.json"
  if [ -f "$state" ]; then
    local pid; pid=$(awk -F'"' '/pid/{{print $4}}' "$state" 2>/dev/null)
    if [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
      local rows; rows=$(awk -F'"' '/ob_y1/{{print $4}}' "$state" 2>/dev/null || echo 0)
      local cols=${{COLUMNS:-80}}
      printf '\x1b7'
      local y=1; while [ "$y" -le "$rows" ]; do printf '\x1b[%d;1H%*s' "$y" "$cols" ''; y=$((y+1)); done
      printf '\x1b8\x1b[0m'
      rm -f "$state"
    fi
  fi
}}
PROMPT_COMMAND="__forgum_precmd${{PROMPT_COMMAND:+; $PROMPT_COMMAND}}"
# <<< forgum <<<
"#
    )
}

fn generate_zsh_hook(engine: &str) -> String {
    format!(
        r#"# >>> forgum (zsh) >>>
# Generated by forgum-engine init zsh — do not edit by hand
__FORGUM_ENGINE="{engine}"
__FORGUM_CONFIG="${{FORGUM_CONFIG:-$HOME/.config/Forgum/config.json}}"
__FORGUM_RUNTIME="${{XDG_RUNTIME_DIR:-/tmp/forgum-$UID}}/forgum"
mkdir -p "$__FORGUM_RUNTIME"

forgum() {{
  local text="$*"
  if [ -z "$text" ]; then
    text="$("$__FORGUM_ENGINE" fortune 2>/dev/null)"
  fi
  "$__FORGUM_ENGINE" render \
    --config "$__FORGUM_CONFIG" \
    --text "$text" \
    --background --duration 0 "$@"
}}

__forgum_precmd() {{
  local state="$__FORGUM_RUNTIME/daemon.json"
  if [ -f "$state" ]; then
    local pid; pid=$(awk -F'"' '/pid/{{print $4}}' "$state" 2>/dev/null)
    if [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
      local rows; rows=$(awk -F'"' '/ob_y1/{{print $4}}' "$state" 2>/dev/null || echo 0)
      local cols=${{COLUMNS:-80}}
      printf '\x1b7'
      local y=1; while [ "$y" -le "$rows" ]; do printf '\x1b[%d;1H%*s' "$y" "$cols" ''; y=$((y+1)); done
      printf '\x1b8\x1b[0m'
      rm -f "$state"
    fi
  fi
}}
precmd_functions+=(__forgum_precmd)
# <<< forgum <<<
"#
    )
}

fn generate_fish_hook(engine: &str) -> String {
    format!(
        r#"# >>> forgum (fish) >>>
# Generated by forgum-engine init fish — do not edit by hand
set -g __forgum_engine "{engine}"
set -g __forgum_config "$FORGUM_CONFIG"; or set -g __forgum_config "$HOME/.config/Forgum/config.json"
set -g __forgum_runtime (set -q XDG_RUNTIME_DIR; and echo "$XDG_RUNTIME_DIR/forgum"; or echo "/tmp/forgum-"(id -u)"/forgum")
mkdir -p $__forgum_runtime

function forgum
    set text $argv
    if test (count $argv) -eq 0
        set text ($__forgum_engine fortune 2>/dev/null)
    end
    $__forgum_engine render --config $__forgum_config --text "$text" --background --duration 0 $argv
end

function __forgum_sweep --on-event fish_prompt
    set state $__forgum_runtime/daemon.json
    if test -f $state
        set pid (awk -F'"' '/pid/{{print $4}}' $state 2>/dev/null)
        if test -n "$pid"; and not kill -0 $pid 2>/dev/null
            set rows (awk -F'"' '/ob_y1/{{print $4}}' $state 2>/dev/null; or echo 0)
            set cols $COLUMNS
            printf '\x1b7'
            for y in (seq 1 $rows); printf '\x1b[%d;1H%*s' $y $cols ''; end
            printf '\x1b8\x1b[0m'
            rm -f $state
        end
    end
end
# <<< forgum <<<
"#
    )
}

fn generate_pwsh_hook(engine: &str) -> String {
    format!(
        r#"# >>> forgum (pwsh) >>>
# Generated by forgum-engine init pwsh — do not edit by hand
$__ForgumEngine = '{engine}'
$__ForgumConfig = if ($env:FORGUM_CONFIG) {{ $env:FORGUM_CONFIG }} else {{ Join-Path $env:APPDATA 'Forgum\config.json' }}

function forgum {{
    param([Parameter(ValueFromRemainingArguments)][string[]]$Args)
    $text = if ($Args) {{ ($Args -join ' ') }} else {{ & $__ForgumEngine fortune 2>$null }}
    & $__ForgumEngine render --config $__ForgumConfig --text $text --background --duration 0 @Args
}}

$global:__ForgumPromptBackup = $function:prompt
function global:prompt {{
    $state = Join-Path $env:TEMP 'Forgum\daemon.json'
    if (Test-Path $state) {{
        $info = Get-Content $state -Raw | ConvertFrom-Json
        if ($info.pid -and -not (Get-Process -Id $info.pid -EA SilentlyContinue)) {{
            [Console]::Write("`e7")
            1..$info.ob_y1 | ForEach-Object {{ [Console]::Write("`e[$($_);1H$(' ' * ($Host.UI.RawUI.WindowSize.Width)))") }}
            [Console]::Write("`e8`e[0m")
            Remove-Item $state -Force
        }}
    }}
    & $global:__ForgumPromptBackup
}}
# <<< forgum <<<
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shell_parse_valid() {
        assert_eq!(Shell::parse("bash"), Some(Shell::Bash));
        assert_eq!(Shell::parse("zsh"), Some(Shell::Zsh));
        assert_eq!(Shell::parse("fish"), Some(Shell::Fish));
        assert_eq!(Shell::parse("pwsh"), Some(Shell::Pwsh));
        assert_eq!(Shell::parse("powershell"), Some(Shell::Pwsh));
    }

    #[test]
    fn shell_parse_invalid() {
        assert_eq!(Shell::parse("ksh"), None);
        assert_eq!(Shell::parse(""), None);
    }

    #[test]
    fn bash_hook_has_required_parts() {
        let hook = generate_hook(Shell::Bash, "/usr/local/bin/forgum-engine");
        assert!(hook.contains("forgum()"));
        assert!(hook.contains("__forgum_precmd"));
        assert!(hook.contains("PROMPT_COMMAND"));
        assert!(hook.contains("/usr/local/bin/forgum-engine"));
        assert!(hook.contains("--background"));
        assert!(hook.contains("--duration 0"));
    }

    #[test]
    fn zsh_hook_uses_precmd_functions() {
        let hook = generate_hook(Shell::Zsh, "/usr/local/bin/forgum-engine");
        assert!(hook.contains("precmd_functions"));
        assert!(hook.contains("forgum()"));
    }

    #[test]
    fn fish_hook_uses_function() {
        let hook = generate_hook(Shell::Fish, "/usr/local/bin/forgum-engine");
        assert!(hook.contains("function forgum"));
        assert!(hook.contains("function __forgum_sweep"));
        assert!(hook.contains("--on-event fish_prompt"));
    }

    #[test]
    fn pwsh_hook_has_prompt_wrapper() {
        let hook = generate_hook(Shell::Pwsh, "C:\\forgum-engine.exe");
        assert!(hook.contains("function forgum"));
        assert!(hook.contains("__ForgumPromptBackup"));
        assert!(hook.contains("function global:prompt"));
    }

    #[test]
    fn all_hooks_contain_engine_path() {
        let path = "/opt/forgum/bin/forgum-engine";
        for shell in [Shell::Bash, Shell::Zsh, Shell::Fish, Shell::Pwsh] {
            let hook = generate_hook(shell, path);
            assert!(hook.contains(path), "shell {shell} missing engine path");
        }
    }

    #[test]
    fn all_hooks_have_header_and_footer() {
        for shell in [Shell::Bash, Shell::Zsh, Shell::Fish, Shell::Pwsh] {
            let hook = generate_hook(shell, "/usr/bin/forgum-engine");
            assert!(hook.contains(">>> forgum"), "shell {shell} missing header");
            assert!(hook.contains("<<< forgum"), "shell {shell} missing footer");
        }
    }
}
