//! Shell hook generation for `forgum init <shell>`.
//!
//! Generates shell-specific hooks that:
//! 1. Resolve the engine path (baked at init time)
//! 2. Call `forgum-engine render` with argv flags (no JSON in shell)
//! 3. Sweep dead daemons on precmd
//!
//! Supported shells: bash, zsh, fish, pwsh (7+), powershell.exe (5.1), cmd.exe.

/// Supported shell types. Canonical definition lives in `forgum-platform::shell`;
/// re-exported here so engine code keeps using `forgum_engine::init::Shell`.
pub use forgum_platform::shell::Shell;

/// Generate a shell hook script.
///
/// `engine_path` is the absolute path to `forgum-engine`, baked in at init time.
pub fn generate_hook(shell: Shell, engine_path: &str) -> String {
    generate_hook_with_args(shell, engine_path, &[])
}

/// Generate a shell hook script with optional render arguments forwarded.
pub fn generate_hook_with_args(shell: Shell, engine_path: &str, render_args: &[String]) -> String {
    let extra = if render_args.is_empty() {
        String::new()
    } else {
        format!(" {}", render_args.join(" "))
    };
    match shell {
        Shell::Bash => generate_bash_hook(engine_path, &extra),
        Shell::Zsh => generate_zsh_hook(engine_path, &extra),
        Shell::Fish => generate_fish_hook(engine_path, &extra),
        Shell::Pwsh => generate_pwsh_hook(engine_path, &extra),
        Shell::Cmd => generate_cmd_hook(engine_path),
        Shell::PowerShell => generate_powershell_hook(engine_path, &extra),
        Shell::Elvish => generate_elvish_hook(engine_path, &extra),
        Shell::Nushell => generate_nushell_hook(engine_path, &extra),
        Shell::Xonsh => generate_xonsh_hook(engine_path, &extra),
        Shell::Tcsh => generate_tcsh_hook(engine_path, &extra),
        Shell::Ksh => generate_ksh_hook(engine_path, &extra),
        Shell::Ion => generate_ion_hook(engine_path, &extra),
        Shell::Oil => generate_oil_hook(engine_path, &extra),
        Shell::Yash => generate_yash_hook(engine_path, &extra),
        Shell::Carapace => {
            "# Carapace completion spec: run `forgum completions carapace` to install\n".to_string()
        }
    }
}

/// Generate a tmux config block for `forgum tmux install`.
///
/// `engine_path` is the absolute path to `forgum-engine`, baked in at init time.
pub fn generate_tmux_config(engine_path: &str) -> String {
    format!(
        "# >>> forgum tmux >>>\n\
         # Generated by forgum-engine tmux install — do not edit by hand\n\
         set -g status-right-length 100\n\
         set -g status-interval 5\n\
         set -g status-right \"#({engine} status-line --max-len 70 2>/dev/null)\"\n\
         set-hook -g pane-focus-in  'run-shell \"{engine} --background --daemon 2>/dev/null\"'\n\
         set-hook -g pane-focus-out 'run-shell \"{engine} control send stop 2>/dev/null\"'\n\
         # <<< forgum tmux <<<\n",
        engine = engine_path
    )
}

pub fn generate_zellij_config(_engine_path: &str) -> String {
    "# >>> forgum zellij >>>\n\
     # Generated by forgum-engine zellij install\n\
     zellij run -- forgum-engine --background --daemon\n\
     # <<< forgum zellij <<<\n"
        .to_string()
}

pub fn generate_wezterm_config(engine_path: &str) -> String {
    format!(
        "-- >>> forgum wezterm >>>\n\
         -- Generated by forgum-engine wezterm install\n\
         local wezterm = require 'wezterm'\n\
         return {{\n\
         status_update_interval = 1000,\n\
         wezterm.on('update-status', function(window, pane)\n\
         local handle = io.popen('{engine} status-line --max-len 60 2>/dev/null')\n\
         local status = handle:read('*a') or ''\n\
         handle:close()\n\
         return {{ {{ Text = status }} }}\n\
         end),\n\
         }}\n\
         -- <<< forgum wezterm <<<\n",
        engine = engine_path
    )
}

pub fn generate_screen_config(engine_path: &str) -> String {
    format!(
        "# >>> forgum screen >>>\n\
         # Generated by forgum-engine screen install — do not edit by hand\n\
         # Add the following to your ~/.screenrc:\n\
         #\n\
         # hardstatus alwayslastline\n\
         # hardstatus string '%{{= kG}}[%{{G}}%H%{{g}}][%= %{{= kw}}%?%-Lw%?%{{r}}(%{{W}}%n*%f%t%?(%u)%?%{{r}})%{{w}}%?%+Lw%?%?%= %{{= kg}}][%{{B}}%Y-%m-%d %{{W}}%c%{{g}}]'\n\
         #\n\
         # Start forgum daemon in background:\n\
         # {engine} --background --daemon\n\
         #\n\
         # Stop daemon when detaching:\n\
         # {engine} control send stop\n\
         # <<< forgum screen <<<\n",
        engine = engine_path
    )
}

fn generate_bash_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (bash) >>>
# Generated by forgum-engine init bash — do not edit by hand
__FORGUM_ENGINE="{engine}"
__FORGUM_CONFIG="${{FORGUM_CONFIG:-$HOME/.config/Forgum/config.json}}"
__FORGUM_RUNTIME="${{XDG_RUNTIME_DIR:-/tmp/forgum-$UID}}/forgum"
mkdir -p "$__FORGUM_RUNTIME" 2>/dev/null

forgum() {{
  case "$1" in
    init|fortune|status|config|control|remote|profile|render|clean|preset|doctor|tmux|zellij|wezterm|screen|help)
      "$__FORGUM_ENGINE" "$@"
      return
      ;;
  esac
  local text="$*"
  if [ -z "$text" ]; then
    text="$("$__FORGUM_ENGINE" fortune 2>/dev/null)"
  fi
  "$__FORGUM_ENGINE" render \
    --config "$__FORGUM_CONFIG" \
    --text "$text" \
    --background --duration 0{extra} "$@"
}}

forgum-init() {{
  "$__FORGUM_ENGINE" init "$@"
}}

__forgum_precmd() {{
  [ -z "$__FORGUM_ENGINE" ] && return
  local state="$__FORGUM_RUNTIME/daemon.json"
  if [ -f "$state" ]; then
    local pid; pid=$(awk -F'"' '/pid/{{print $4}}' "$state" 2>/dev/null)
    if [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
      local rows; rows=$(awk -F'"' '/ob_y1/{{print $4}}' "$state" 2>/dev/null || echo 0)
      local cols=${{COLUMNS:-80}}
      printf '\x1b7'
      local y=1; while [ "$y" -le "$rows" ]; do printf '\x1b[%d;1H%*s' "$y" "$cols" ''; y=$((y+1)); done
      printf '\x1b8\x1b[0m'
      rm -f "$state"
    fi
  fi

  if [ -f "$__FORGUM_CONFIG" ]; then
    local auto; auto=$(grep -o '"auto_render_on_prompt":\s*[^,}}]*' "$__FORGUM_CONFIG" 2>/dev/null | awk '{{print $2}}')
    local mode; mode=$(grep -o '"shell_attach_mode":\s*"[^"]*"' "$__FORGUM_CONFIG" 2>/dev/null | cut -d'"' -f4)
    if [ "$auto" != "false" ]; then
      case "$mode" in
        banner) "$__FORGUM_ENGINE" render --banner --duration 1{extra} 2>/dev/null ;;
        split) printf '\x1b[9;%dr' "${{LINES:-30}}"; "$__FORGUM_ENGINE" render --background --duration 0{extra} >/dev/null 2>&1 ;;
        reactive) "$__FORGUM_ENGINE" render --background --duration 0{extra} >/dev/null 2>&1 ;;
        *) ;;
      esac
    fi
  fi
}}
if [[ -v PROMPT_COMMAND ]]; then
  PROMPT_COMMAND="__forgum_precmd${{PROMPT_COMMAND:+;$PROMPT_COMMAND}}"
else
  PROMPT_COMMAND="__forgum_precmd"
fi
# <<< forgum <<<
"#
    )
}

fn generate_zsh_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (zsh) >>>
# Generated by forgum-engine init zsh — do not edit by hand
__FORGUM_ENGINE="{engine}"
__FORGUM_CONFIG="${{FORGUM_CONFIG:-$HOME/.config/Forgum/config.json}}"
__FORGUM_RUNTIME="${{XDG_RUNTIME_DIR:-/tmp/forgum-$UID}}/forgum"
mkdir -p "$__FORGUM_RUNTIME" 2>/dev/null

forgum() {{
  case "$1" in
    init|fortune|status|config|control|remote|profile|render|clean|preset|doctor|tmux|zellij|wezterm|screen|help)
      "$__FORGUM_ENGINE" "$@"
      return
      ;;
  esac
  local text="$*"
  if [ -z "$text" ]; then
    text="$("$__FORGUM_ENGINE" fortune 2>/dev/null)"
  fi
  "$__FORGUM_ENGINE" render \
    --config "$__FORGUM_CONFIG" \
    --text "$text" \
    --background --duration 0{extra} "$@"
}}

forgum-init() {{
  "$__FORGUM_ENGINE" init "$@"
}}

__forgum_precmd() {{
  [ -z "$__FORGUM_ENGINE" ] && return
  local state="$__FORGUM_RUNTIME/daemon.json"
  if [ -f "$state" ]; then
    local pid; pid=$(awk -F'"' '/pid/{{print $4}}' "$state" 2>/dev/null)
    if [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
      local rows; rows=$(awk -F'"' '/ob_y1/{{print $4}}' "$state" 2>/dev/null || echo 0)
      local cols=${{COLUMNS:-80}}
      printf '\x1b7'
      local y=1; while [ "$y" -le "$rows" ]; do printf '\x1b[%d;1H%*s' "$y" "$cols" ''; y=$((y+1)); done
      printf '\x1b8\x1b[0m'
      rm -f "$state"
    fi
  fi

  if [ -f "$__FORGUM_CONFIG" ]; then
    local auto; auto=$(grep -o '"auto_render_on_prompt":\s*[^,}}]*' "$__FORGUM_CONFIG" 2>/dev/null | awk '{{print $2}}')
    local mode; mode=$(grep -o '"shell_attach_mode":\s*"[^"]*"' "$__FORGUM_CONFIG" 2>/dev/null | cut -d'"' -f4)
    if [ "$auto" != "false" ]; then
      case "$mode" in
        banner) "$__FORGUM_ENGINE" render --banner --duration 1{extra} 2>/dev/null ;;
        split) printf '\x1b[9;%dr' "${{LINES:-30}}"; "$__FORGUM_ENGINE" render --background --duration 0{extra} >/dev/null 2>&1 ;;
        reactive) "$__FORGUM_ENGINE" render --background --duration 0{extra} >/dev/null 2>&1 ;;
        *) ;;
      esac
    fi
  fi
}}
typeset -a precmd_functions 2>/dev/null
precmd_functions+=(__forgum_precmd)
# <<< forgum <<<
"#
    )
}

fn generate_fish_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (fish) >>>
# Generated by forgum-engine init fish — do not edit by hand
set -g __forgum_engine "{engine}"
set -g __forgum_config "$FORGUM_CONFIG"; or set -g __forgum_config "$HOME/.config/Forgum/config.json"
set -g __forgum_runtime (set -q XDG_RUNTIME_DIR; and echo "$XDG_RUNTIME_DIR/forgum"; or echo "/tmp/forgum-"(id -u)"/forgum")
mkdir -p $__forgum_runtime 2>/dev/null

function forgum
    switch "$argv[1]"
        case init fortune status config control remote profile render clean preset doctor tmux zellij wezterm screen help
            $__forgum_engine $argv
            return
    end
    set text $argv
    if not set -q argv[1]
        set text ($__forgum_engine fortune 2>/dev/null)
    end
    $__forgum_engine render --config $__forgum_config --text "$text" --background --duration 0{extra} $argv
end

function forgum-init
    $__forgum_engine init $argv
end

function __forgum_sweep --on-event fish_prompt
    set -q __forgum_engine; or return
    set state $__forgum_runtime/daemon.json
    if test -f $state
        set pid (awk -F'"' '/pid/{{print $4}}' $state 2>/dev/null)
        if test -n "$pid"; and not kill -0 $pid 2>/dev/null
            set rows (awk -F'"' '/ob_y1/{{print $4}}' $state 2>/dev/null; or echo 0)
            set cols $COLUMNS
            printf '\x1b7'
            for y in (seq 1 $rows); printf '\x1b[%d;1H%*s' $y $cols ''; end
            printf '\x1b8\x1b[0m'
            rm -f $state
        end
    end
end
# <<< forgum <<<
"#
    )
}

fn generate_pwsh_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (pwsh) >>>
# Generated by forgum-engine init pwsh — do not edit by hand
$__ForgumEngine = '{engine}'
$__ForgumConfig = if ($env:FORGUM_CONFIG) {{ $env:FORGUM_CONFIG }} else {{ Join-Path $env:APPDATA 'Forgum\config.json' }}

function forgum {{
    param([Parameter(ValueFromRemainingArguments)][string[]]$Args)
    if ($Args -and $Args.Count -gt 0) {{
        switch ($Args[0]) {{
            {{ $_ -in 'init','fortune','status','config','control','remote','profile','render','clean','preset','doctor','tmux','zellij','wezterm','screen','help' }} {{
                & $__ForgumEngine @Args
                return
            }}
        }}
    }}
    $text = if ($Args) {{ ($Args -join ' ') }} else {{ & $__ForgumEngine fortune 2>$null }}
    & $__ForgumEngine render --config $__ForgumConfig --text $text --background --duration 0{extra} @Args
}}

function forgum-init {{
    param([Parameter(ValueFromRemainingArguments)][string[]]$Args)
    & $__ForgumEngine init @Args
}}

$global:__ForgumPromptBackup = $function:prompt
$global:__ForgumEsc = if ($PSVersionTable.PSVersion.Major -ge 7) {{ '`e' }} else {{ [char]27 }}
function global:prompt {{
    $esc = $global:__ForgumEsc
    $state = Join-Path $env:TEMP 'Forgum\daemon.json'
    if (Test-Path $state) {{
        try {{
            $info = Get-Content $state -Raw | ConvertFrom-Json
            if ($info.pid -and -not (Get-Process -Id $info.pid -EA SilentlyContinue)) {{
                [Console]::Write("$esc7")
                $w = if ($Host.UI.RawUI) {{ $Host.UI.RawUI.WindowSize.Width }} else {{ 80 }}
                1..$info.ob_y1 | ForEach-Object {{ [Console]::Write("$esc[$($_);1H$(' ' * $w)") }}
                [Console]::Write("$esc8$esc[0m")
                Remove-Item $state -Force
            }}
        }} catch {{ }}
    }}

    # Prompt attachment handler
    if (Test-Path $__ForgumConfig) {{
        try {{
            $cfg = Get-Content $__ForgumConfig -Raw | ConvertFrom-Json
            if ($cfg.auto_render_on_prompt -ne $false) {{
                switch ($cfg.shell_attach_mode) {{
                    'banner' {{
                        & $__ForgumEngine render --banner --duration 1{extra} 2>$null
                    }}
                    'split' {{
                        $h = if ($Host.UI.RawUI) {{ $Host.UI.RawUI.WindowSize.Height }} else {{ 30 }}
                        [Console]::Write("$esc[9;$($h)r")
                        & $__ForgumEngine render --background --duration 0{extra} 2>$null
                    }}
                    'reactive' {{
                        & $__ForgumEngine render --background --duration 0{extra} 2>$null
                    }}
                    default {{ }}
                }}
            }}
        }} catch {{ }}
    }}

    & $global:__ForgumPromptBackup
}}
# <<< forgum <<<
"#
    )
}

fn generate_cmd_hook(engine: &str) -> String {
    format!(
        r#"@echo off
rem >>> forgum (cmd) >>>
rem Generated by forgum-engine init cmd — do not edit by hand
rem
rem NOTE: cmd.exe has NO precmd hook model. We inject a `prompt` macro that
rem runs the dead-daemon sweeper on every prompt, and register a `forgum`
rem alias via doskey. The previous prompt is preserved by capturing it into
rem _FORGUM_OLD_PROMPT first. To persist across sessions, either source this
rem file from your auto-run script or set the registry AutoRun key:
rem   reg add "HKCU\Software\Microsoft\Command Processor" /v AutoRun /t REG_SZ /d "<this-file>"
rem (AutoRun persistence is user-opt-in; forgum never mutates the registry.)
set "_FORGUM_ENGINE={engine}"
if not defined _FORGUM_OLD_PROMPT set "_FORGUM_OLD_PROMPT=$P$G"
doskey forgum="{engine}" $*
doskey forgum-init="{engine}" init $*
prompt $_FORGUM_OLD_PROMPT$G & "%_FORGUM_ENGINE%" sweep
rem <<< forgum <<<
"#
    )
}

fn generate_powershell_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (powershell) >>>
# Generated by forgum-engine init powershell — do not edit by hand
$__ForgumEngine = '{engine}'
$__ForgumConfig = if ($env:FORGUM_CONFIG) {{ $env:FORGUM_CONFIG }} else {{ Join-Path $env:APPDATA 'Forgum\config.json' }}

function forgum {{
    param([Parameter(ValueFromRemainingArguments)][string[]]$Args)
    if ($Args -and $Args.Count -gt 0) {{
        switch ($Args[0]) {{
            {{ $_ -in 'init','fortune','status','config','control','remote','profile','render','clean','preset','doctor','tmux','zellij','wezterm','screen','help' }} {{
                & $__ForgumEngine @Args
                return
            }}
        }}
    }}
    $text = if ($Args) {{ ($Args -join ' ') }} else {{ & $__ForgumEngine fortune 2>$null }}
    & $__ForgumEngine render --config $__ForgumConfig --text $text --background --duration 0{extra} @Args
}}

function forgum-init {{
    param([Parameter(ValueFromRemainingArguments)][string[]]$Args)
    & $__ForgumEngine init @Args
}}

$global:__ForgumPromptBackup = $function:prompt
$global:__ForgumEsc = if ($PSVersionTable.PSVersion.Major -ge 7) {{ '`e' }} else {{ [char]27 }}
function global:prompt {{
    $esc = $global:__ForgumEsc
    $state = Join-Path $env:TEMP 'Forgum\daemon.json'
    if (Test-Path $state) {{
        try {{
            $info = Get-Content $state -Raw | ConvertFrom-Json
            if ($info.pid -and -not (Get-Process -Id $info.pid -EA SilentlyContinue)) {{
                [Console]::Write("$esc7")
                $w = if ($Host.UI.RawUI) {{ $Host.UI.RawUI.WindowSize.Width }} else {{ 80 }}
                1..$info.ob_y1 | ForEach-Object {{ [Console]::Write("$esc[$($_);1H$(' ' * $w)") }}
                [Console]::Write("$esc8$esc[0m")
                Remove-Item $state -Force
            }}
        }} catch {{ }}
    }}

    # Prompt attachment handler
    if (Test-Path $__ForgumConfig) {{
        try {{
            $cfg = Get-Content $__ForgumConfig -Raw | ConvertFrom-Json
            if ($cfg.auto_render_on_prompt -ne $false) {{
                switch ($cfg.shell_attach_mode) {{
                    'banner' {{
                        & $__ForgumEngine render --banner --duration 1{extra} 2>$null
                    }}
                    'split' {{
                        $h = if ($Host.UI.RawUI) {{ $Host.UI.RawUI.WindowSize.Height }} else {{ 30 }}
                        [Console]::Write("$esc[9;$($h)r")
                        & $__ForgumEngine render --background --duration 0{extra} 2>$null
                    }}
                    'reactive' {{
                        & $__ForgumEngine render --background --duration 0{extra} 2>$null
                    }}
                    default {{ }}
                }}
            }}
        }} catch {{ }}
    }}

    & $global:__ForgumPromptBackup
}}
# <<< forgum <<<
"#
    )
}

fn generate_elvish_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (elvish) >>>
# Generated by forgum-engine init elvish — do not edit by hand
var __forgum_engine = '{engine}'
fn forgum {{|@args|
  if (eq (count $args) 0) {{{{
    var text = ($__forgum_engine fortune 2>/dev/null)
    $__forgum_engine render --text $text --background --duration 0{extra}
  }}}} else {{{{
    $__forgum_engine $@args
  }}}}
}}
# <<< forgum <<<
"#
    )
}

fn generate_nushell_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (nushell) >>>
# Generated by forgum-engine init nushell — do not edit by hand
def --wrapped forgum [...rest] {{
    if ($rest | is-empty) {{
        let text = (^"{engine}" fortune | complete).stdout
        ^"{engine}" render --text $text --background --duration 0{extra}
    }} else {{
        ^"{engine}" ...$rest
    }}
}}
# <<< forgum <<<
"#
    )
}

fn generate_xonsh_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (xonsh) >>>
# Generated by forgum-engine init xonsh — do not edit by hand
def _forgum_cmd(args, stdin=None):
    if not args:
        text = !({engine} fortune).output
        !({engine} render --text @(text.strip()) --background --duration 0{extra})
    else:
        !({engine} @(args))

aliases['forgum'] = _forgum_cmd
aliases['forgum-init'] = lambda args, stdin=None: !({engine} init @(args))
# <<< forgum <<<
"#
    )
}

fn generate_tcsh_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (tcsh) >>>
# Generated by forgum-engine init tcsh — do not edit by hand
alias forgum '{engine} render --background --duration 0{extra}'
alias forgum-init '{engine} init'
# <<< forgum <<<
"#
    )
}

fn generate_ksh_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (ksh) >>>
# Generated by forgum-engine init ksh — do not edit by hand
forgum() {{
    if [ $# -eq 0 ]; then
        text="$({engine} fortune 2>/dev/null)"
        {engine} render --text "$text" --background --duration 0{extra}
    else
        {engine} "$@"
    fi
}}
alias forgum-init='{engine} init'
# <<< forgum <<<
"#
    )
}

fn generate_ion_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (ion) >>>
# Generated by forgum-engine init ion — do not edit by hand
fn forgum
    if test (len @args) -eq 0
        let text = $({engine} fortune)
        {engine} render --text "$text" --background --duration 0{extra}
    else
        {engine} @args
    end
end
# <<< forgum <<<
"#
    )
}

fn generate_oil_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (oil) >>>
# Generated by forgum-engine init oil — do not edit by hand
proc forgum(...args) {{
    if (len(args) === 0) {{
        var text = $({engine} fortune)
        {engine} render --text "$text" --background --duration 0{extra}
    }} else {{
        {engine} @args
    }}
}}
# <<< forgum <<<
"#
    )
}

fn generate_yash_hook(engine: &str, extra: &str) -> String {
    format!(
        r#"# >>> forgum (yash) >>>
# Generated by forgum-engine init yash — do not edit by hand
function forgum() {{
    if [ $# -eq 0 ]; then
        text="$({engine} fortune 2>/dev/null)"
        {engine} render --text "$text" --background --duration 0{extra}
    else
        {engine} "$@"
    fi
}}
alias forgum-init='{engine} init'
# <<< forgum <<<
"#
    )
}

/// Generate Starship prompt integration block.
pub fn generate_starship_config(engine_path: &str) -> String {
    format!(
        r#"# >>> forgum starship >>>
# Append this custom module to your ~/.config/starship.toml:
[custom.forgum]
command = "{engine_path} status-line --max-len 30 2>/dev/null"
when = "true"
format = "[$output]($style) "
style = "bold green"
# <<< forgum starship <<<
"#
    )
}

/// Generate Byobu status line script.
pub fn generate_byobu_config(engine_path: &str) -> String {
    format!(
        r#"# >>> forgum byobu >>>
# Place in ~/.byobu/bin/10_forgum (make executable: chmod +x ~/.byobu/bin/10_forgum):
#!/bin/sh
{engine_path} status-line --max-len 40 2>/dev/null
# <<< forgum byobu <<<
"#
    )
}

/// Generate Navi interactive cheatsheet.
pub fn generate_navi_cheatsheet() -> String {
    r#"% forgum, animated ascii mascots

# Render default animated mascot
forgum render

# Render specific animal mascot with animation effect
forgum --animal <animal> --effect <effect>

# Run in background overlay mode above prompt
forgum --background --duration 0

# Interactive TUI dashboard (5 tabs: Mascots, Scenery, Effects, Installer, Config)
forgum-tui

# Inspect all built-in animals, effects, environments, and road styles
forgum list all

# Generate shell completions for any shell
forgum completions <shell>

# Generate shell integration hook
forgum init <shell>
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shell_parse_valid() {
        assert_eq!(Shell::parse("bash"), Some(Shell::Bash));
        assert_eq!(Shell::parse("zsh"), Some(Shell::Zsh));
        assert_eq!(Shell::parse("fish"), Some(Shell::Fish));
        assert_eq!(Shell::parse("pwsh"), Some(Shell::Pwsh));
        assert_eq!(Shell::parse("powershell"), Some(Shell::PowerShell));
        assert_eq!(Shell::parse("cmd"), Some(Shell::Cmd));
        assert_eq!(Shell::parse("xonsh"), Some(Shell::Xonsh));
        assert_eq!(Shell::parse("tcsh"), Some(Shell::Tcsh));
        assert_eq!(Shell::parse("ksh"), Some(Shell::Ksh));
        assert_eq!(Shell::parse("ion"), Some(Shell::Ion));
        assert_eq!(Shell::parse("oil"), Some(Shell::Oil));
        assert_eq!(Shell::parse("yash"), Some(Shell::Yash));
    }

    #[test]
    fn shell_parse_invalid() {
        assert_eq!(Shell::parse("unknown_shell_xyz"), None);
        assert_eq!(Shell::parse(""), None);
    }

    #[test]
    fn bash_hook_has_required_parts() {
        let hook = generate_hook(Shell::Bash, "/usr/local/bin/forgum-engine");
        assert!(hook.contains("forgum()"));
        assert!(hook.contains("__forgum_precmd"));
        assert!(hook.contains("PROMPT_COMMAND"));
        assert!(hook.contains("/usr/local/bin/forgum-engine"));
        assert!(hook.contains("--background"));
        assert!(hook.contains("--duration 0"));
    }

    #[test]
    fn zsh_hook_uses_precmd_functions() {
        let hook = generate_hook(Shell::Zsh, "/usr/local/bin/forgum-engine");
        assert!(hook.contains("precmd_functions"));
        assert!(hook.contains("forgum()"));
    }

    #[test]
    fn fish_hook_uses_function() {
        let hook = generate_hook(Shell::Fish, "/usr/local/bin/forgum-engine");
        assert!(hook.contains("function forgum"));
        assert!(hook.contains("function __forgum_sweep"));
        assert!(hook.contains("--on-event fish_prompt"));
    }

    #[test]
    fn pwsh_hook_has_prompt_wrapper() {
        let hook = generate_hook(Shell::Pwsh, "C:\\forgum-engine.exe");
        assert!(hook.contains("function forgum"));
        assert!(hook.contains("__ForgumPromptBackup"));
        assert!(hook.contains("function global:prompt"));
    }

    #[test]
    fn cmd_hook_has_required_parts() {
        let engine = "C:\\forgum-engine.exe";
        let hook = generate_cmd_hook(engine);
        assert!(hook.contains(">>> forgum"));
        assert!(hook.contains("<<< forgum"));
        assert!(hook.contains("prompt"));
        assert!(hook.contains("sweep"));
        assert!(hook.contains(engine));
        assert!(hook.contains("cmd"));
    }

    #[test]
    fn powershell_hook_has_prompt_wrapper() {
        let hook = generate_hook(Shell::PowerShell, "C:\\forgum-engine.exe");
        assert!(hook.contains("function forgum"));
        assert!(hook.contains("__ForgumPromptBackup"));
        assert!(hook.contains("function global:prompt"));
    }

    #[test]
    fn cmd_display_and_parse() {
        assert_eq!(Shell::Cmd.to_string(), "cmd");
        assert_eq!(Shell::PowerShell.to_string(), "powershell");
        assert_eq!(Shell::parse("CMD"), Some(Shell::Cmd));
    }

    #[test]
    fn all_hooks_contain_engine_path() {
        let path = "/opt/forgum/bin/forgum-engine";
        for shell in [
            Shell::Bash,
            Shell::Zsh,
            Shell::Fish,
            Shell::Pwsh,
            Shell::Cmd,
            Shell::PowerShell,
        ] {
            let hook = generate_hook(shell, path);
            assert!(hook.contains(path), "shell {shell} missing engine path");
        }
    }

    #[test]
    fn all_hooks_have_header_and_footer() {
        for shell in [
            Shell::Bash,
            Shell::Zsh,
            Shell::Fish,
            Shell::Pwsh,
            Shell::Cmd,
            Shell::PowerShell,
        ] {
            let hook = generate_hook(shell, "/usr/bin/forgum-engine");
            assert!(hook.contains(">>> forgum"), "shell {shell} missing header");
            assert!(hook.contains("<<< forgum"), "shell {shell} missing footer");
        }
    }

    #[test]
    fn zellij_config_has_required_parts() {
        let config = generate_zellij_config("/usr/local/bin/forgum-engine");
        assert!(config.contains(">>> forgum zellij >>>"));
        assert!(config.contains("<<< forgum zellij <<<"));
    }

    #[test]
    fn wezterm_config_has_required_parts() {
        let config = generate_wezterm_config("/usr/local/bin/forgum-engine");
        assert!(config.contains(">>> forgum wezterm >>>"));
        assert!(config.contains("<<< forgum wezterm <<<"));
        assert!(config.contains("/usr/local/bin/forgum-engine"));
    }

    #[test]
    fn screen_config_has_required_parts() {
        let config = generate_screen_config("/usr/local/bin/forgum-engine");
        assert!(config.contains(">>> forgum screen >>>"));
        assert!(config.contains("<<< forgum screen <<<"));
    }

    #[test]
    fn tmux_config_has_required_parts() {
        let config = generate_tmux_config("/usr/local/bin/forgum-engine");
        assert!(config.contains(">>> forgum tmux >>>"));
        assert!(config.contains("<<< forgum tmux <<<"));
        assert!(config.contains("status-right-length 100"));
        assert!(config.contains("status-interval 5"));
        assert!(config.contains("status-right"));
        assert!(config.contains("status-line --max-len 70"));
        assert!(config.contains("pane-focus-in"));
        assert!(config.contains("pane-focus-out"));
        assert!(config.contains("/usr/local/bin/forgum-engine"));
    }

    #[test]
    fn forgum_init_shim_present_in_all_shells() {
        for shell in [
            Shell::Bash,
            Shell::Zsh,
            Shell::Fish,
            Shell::Pwsh,
            Shell::PowerShell,
            Shell::Cmd,
        ] {
            let hook = generate_hook(shell, "/usr/bin/forgum-engine");
            assert!(
                hook.contains("forgum-init"),
                "shell {shell:?} must contain 'forgum-init' alias or function"
            );
        }
    }
}
