//! Shell hook generation for `forgum init <shell>`.
//!
//! Generates shell-specific hooks that:
//! 1. Resolve the engine path (baked at init time)
//! 2. Call `forgum-engine render` with argv flags (no JSON in shell)
//! 3. Sweep dead daemons on precmd
//!
//! Supported shells: bash, zsh, fish, pwsh (7+), powershell.exe (5.1), cmd.exe.

/// Supported shell types. Canonical definition lives in `forgum-platform::shell`;
/// re-exported here so engine code keeps using `forgum_engine::init::Shell`.
pub use forgum_platform::shell::Shell;

/// Generate a shell hook script.
///
/// `engine_path` is the absolute path to `forgum-engine`, baked in at init time.
pub fn generate_hook(shell: Shell, engine_path: &str) -> String {
    match shell {
        Shell::Bash => generate_bash_hook(engine_path),
        Shell::Zsh => generate_zsh_hook(engine_path),
        Shell::Fish => generate_fish_hook(engine_path),
        Shell::Pwsh => generate_pwsh_hook(engine_path),
        Shell::Cmd => generate_cmd_hook(engine_path),
        Shell::PowerShell => generate_powershell_hook(engine_path),
    }
}

/// Generate a tmux config block for `forgum tmux install`.
///
/// `engine_path` is the absolute path to `forgum-engine`, baked in at init time.
pub fn generate_tmux_config(engine_path: &str) -> String {
    format!(
        "# >>> forgum tmux >>>\n\
         # Generated by forgum-engine tmux install — do not edit by hand\n\
         set -g status-right-length 100\n\
         set -g status-interval 5\n\
         set -g status-right \"#({engine} status-line --max-len 70 2>/dev/null)\"\n\
         set-hook -g pane-focus-in  'run-shell \"{engine} --background --daemon 2>/dev/null\"'\n\
         set-hook -g pane-focus-out 'run-shell \"{engine} control send stop 2>/dev/null\"'\n\
         # <<< forgum tmux <<<\n",
        engine = engine_path
    )
}

pub fn generate_zellij_config(_engine_path: &str) -> String {
    "# >>> forgum zellij >>>\n\
     # Generated by forgum-engine zellij install\n\
     zellij run -- forgum-engine --background --daemon\n\
     # <<< forgum zellij <<<\n"
        .to_string()
}

pub fn generate_wezterm_config(engine_path: &str) -> String {
    format!(
        "-- >>> forgum wezterm >>>\n\
         -- Generated by forgum-engine wezterm install\n\
         local wezterm = require 'wezterm'\n\
         return {{\n\
         status_update_interval = 1000,\n\
         wezterm.on('update-status', function(window, pane)\n\
         local handle = io.popen('{engine} status-line --max-len 60 2>/dev/null')\n\
         local status = handle:read('*a') or ''\n\
         handle:close()\n\
         return {{ {{ Text = status }} }}\n\
         end),\n\
         }}\n\
         -- <<< forgum wezterm <<<\n",
        engine = engine_path
    )
}

pub fn generate_screen_config(engine_path: &str) -> String {
    format!(
        "# >>> forgum screen >>>\n\
         # Generated by forgum-engine screen install\n\
         # Add to .screenrc:\n\
         # {engine} --background --daemon\n\
         # <<< forgum screen <<<\n",
        engine = engine_path
    )
}

fn generate_bash_hook(engine: &str) -> String {
    format!(
        r#"# >>> forgum (bash) >>>
# Generated by forgum-engine init bash — do not edit by hand
__FORGUM_ENGINE="{engine}"
__FORGUM_CONFIG="${{FORGUM_CONFIG:-$HOME/.config/Forgum/config.json}}"
__FORGUM_RUNTIME="${{XDG_RUNTIME_DIR:-/tmp/forgum-$UID}}/forgum"
mkdir -p "$__FORGUM_RUNTIME"

forgum() {{
  local text="$*"
  if [ -z "$text" ]; then
    text="$("$__FORGUM_ENGINE" fortune 2>/dev/null)"
  fi
  "$__FORGUM_ENGINE" render \
    --config "$__FORGUM_CONFIG" \
    --text "$text" \
    --background --duration 0 "$@"
}}

__forgum_precmd() {{
  local state="$__FORGUM_RUNTIME/daemon.json"
  if [ -f "$state" ]; then
    local pid; pid=$(awk -F'"' '/pid/{{print $4}}' "$state" 2>/dev/null)
    if [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
      local rows; rows=$(awk -F'"' '/ob_y1/{{print $4}}' "$state" 2>/dev/null || echo 0)
      local cols=${{COLUMNS:-80}}
      printf '\x1b7'
      local y=1; while [ "$y" -le "$rows" ]; do printf '\x1b[%d;1H%*s' "$y" "$cols" ''; y=$((y+1)); done
      printf '\x1b8\x1b[0m'
      rm -f "$state"
    fi
  fi
}}
PROMPT_COMMAND="__forgum_precmd${{PROMPT_COMMAND:+; $PROMPT_COMMAND}}"
# <<< forgum <<<
"#
    )
}

fn generate_zsh_hook(engine: &str) -> String {
    format!(
        r#"# >>> forgum (zsh) >>>
# Generated by forgum-engine init zsh — do not edit by hand
__FORGUM_ENGINE="{engine}"
__FORGUM_CONFIG="${{FORGUM_CONFIG:-$HOME/.config/Forgum/config.json}}"
__FORGUM_RUNTIME="${{XDG_RUNTIME_DIR:-/tmp/forgum-$UID}}/forgum"
mkdir -p "$__FORGUM_RUNTIME"

forgum() {{
  local text="$*"
  if [ -z "$text" ]; then
    text="$("$__FORGUM_ENGINE" fortune 2>/dev/null)"
  fi
  "$__FORGUM_ENGINE" render \
    --config "$__FORGUM_CONFIG" \
    --text "$text" \
    --background --duration 0 "$@"
}}

__forgum_precmd() {{
  local state="$__FORGUM_RUNTIME/daemon.json"
  if [ -f "$state" ]; then
    local pid; pid=$(awk -F'"' '/pid/{{print $4}}' "$state" 2>/dev/null)
    if [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
      local rows; rows=$(awk -F'"' '/ob_y1/{{print $4}}' "$state" 2>/dev/null || echo 0)
      local cols=${{COLUMNS:-80}}
      printf '\x1b7'
      local y=1; while [ "$y" -le "$rows" ]; do printf '\x1b[%d;1H%*s' "$y" "$cols" ''; y=$((y+1)); done
      printf '\x1b8\x1b[0m'
      rm -f "$state"
    fi
  fi
}}
precmd_functions+=(__forgum_precmd)
# <<< forgum <<<
"#
    )
}

fn generate_fish_hook(engine: &str) -> String {
    format!(
        r#"# >>> forgum (fish) >>>
# Generated by forgum-engine init fish — do not edit by hand
set -g __forgum_engine "{engine}"
set -g __forgum_config "$FORGUM_CONFIG"; or set -g __forgum_config "$HOME/.config/Forgum/config.json"
set -g __forgum_runtime (set -q XDG_RUNTIME_DIR; and echo "$XDG_RUNTIME_DIR/forgum"; or echo "/tmp/forgum-"(id -u)"/forgum")
mkdir -p $__forgum_runtime

function forgum
    set text $argv
    if test (count $argv) -eq 0
        set text ($__forgum_engine fortune 2>/dev/null)
    end
    $__forgum_engine render --config $__forgum_config --text "$text" --background --duration 0 $argv
end

function __forgum_sweep --on-event fish_prompt
    set state $__forgum_runtime/daemon.json
    if test -f $state
        set pid (awk -F'"' '/pid/{{print $4}}' $state 2>/dev/null)
        if test -n "$pid"; and not kill -0 $pid 2>/dev/null
            set rows (awk -F'"' '/ob_y1/{{print $4}}' $state 2>/dev/null; or echo 0)
            set cols $COLUMNS
            printf '\x1b7'
            for y in (seq 1 $rows); printf '\x1b[%d;1H%*s' $y $cols ''; end
            printf '\x1b8\x1b[0m'
            rm -f $state
        end
    end
end
# <<< forgum <<<
"#
    )
}

fn generate_pwsh_hook(engine: &str) -> String {
    format!(
        r#"# >>> forgum (pwsh) >>>
# Generated by forgum-engine init pwsh — do not edit by hand
$__ForgumEngine = '{engine}'
$__ForgumConfig = if ($env:FORGUM_CONFIG) {{ $env:FORGUM_CONFIG }} else {{ Join-Path $env:APPDATA 'Forgum\config.json' }}

function forgum {{
    param([Parameter(ValueFromRemainingArguments)][string[]]$Args)
    $text = if ($Args) {{ ($Args -join ' ') }} else {{ & $__ForgumEngine fortune 2>$null }}
    & $__ForgumEngine render --config $__ForgumConfig --text $text --background --duration 0 @Args
}}

$global:__ForgumPromptBackup = $function:prompt
function global:prompt {{
    $state = Join-Path $env:TEMP 'Forgum\daemon.json'
    if (Test-Path $state) {{
        $info = Get-Content $state -Raw | ConvertFrom-Json
        if ($info.pid -and -not (Get-Process -Id $info.pid -EA SilentlyContinue)) {{
            [Console]::Write("`e7")
            1..$info.ob_y1 | ForEach-Object {{ [Console]::Write("`e[$($_);1H$(' ' * ($Host.UI.RawUI.WindowSize.Width)))") }}
            [Console]::Write("`e8`e[0m")
            Remove-Item $state -Force
        }}
    }}
    & $global:__ForgumPromptBackup
}}
# <<< forgum <<<
"#
    )
}

fn generate_cmd_hook(engine: &str) -> String {
    format!(
        r#"@echo off
rem >>> forgum (cmd) >>>
rem Generated by forgum-engine init cmd — do not edit by hand
rem
rem NOTE: cmd.exe has NO precmd hook model. We inject a `prompt` macro that
rem runs the dead-daemon sweeper on every prompt, and register a `forgum`
rem alias via doskey. The previous prompt is preserved by capturing it into
rem _FORGUM_OLD_PROMPT first. To persist across sessions, either source this
rem file from your auto-run script or set the registry AutoRun key:
rem   reg add "HKCU\Software\Microsoft\Command Processor" /v AutoRun /t REG_SZ /d "<this-file>"
rem (AutoRun persistence is user-opt-in; forgum never mutates the registry.)
set "_FORGUM_ENGINE={engine}"
if not defined _FORGUM_OLD_PROMPT set "_FORGUM_OLD_PROMPT=$P$G"
doskey forgum="{engine}" $*
prompt $_FORGUM_OLD_PROMPT$G & "%_FORGUM_ENGINE%" sweep
rem <<< forgum <<<
"#
    )
}

fn generate_powershell_hook(engine: &str) -> String {
    format!(
        r#"# >>> forgum (powershell) >>>
# Generated by forgum-engine init powershell — do not edit by hand
$__ForgumEngine = '{engine}'
$__ForgumConfig = if ($env:FORGUM_CONFIG) {{ $env:FORGUM_CONFIG }} else {{ Join-Path $env:APPDATA 'Forgum\config.json' }}

function forgum {{
    param([Parameter(ValueFromRemainingArguments)][string[]]$Args)
    $text = if ($Args) {{ ($Args -join ' ') }} else {{ & $__ForgumEngine fortune 2>$null }}
    & $__ForgumEngine render --config $__ForgumConfig --text $text --background --duration 0 @Args
}}

$global:__ForgumPromptBackup = $function:prompt
function global:prompt {{
    $state = Join-Path $env:TEMP 'Forgum\daemon.json'
    if (Test-Path $state) {{
        $info = Get-Content $state -Raw | ConvertFrom-Json
        if ($info.pid -and -not (Get-Process -Id $info.pid -EA SilentlyContinue)) {{
            [Console]::Write("`e7")
            1..$info.ob_y1 | ForEach-Object {{ [Console]::Write("`e[$($_);1H$(' ' * ($Host.UI.RawUI.WindowSize.Width)))") }}
            [Console]::Write("`e8`e[0m")
            Remove-Item $state -Force
        }}
    }}
    & $global:__ForgumPromptBackup
}}
# <<< forgum <<<
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shell_parse_valid() {
        assert_eq!(Shell::parse("bash"), Some(Shell::Bash));
        assert_eq!(Shell::parse("zsh"), Some(Shell::Zsh));
        assert_eq!(Shell::parse("fish"), Some(Shell::Fish));
        assert_eq!(Shell::parse("pwsh"), Some(Shell::Pwsh));
        assert_eq!(Shell::parse("powershell"), Some(Shell::PowerShell));
        assert_eq!(Shell::parse("cmd"), Some(Shell::Cmd));
    }

    #[test]
    fn shell_parse_invalid() {
        assert_eq!(Shell::parse("ksh"), None);
        assert_eq!(Shell::parse(""), None);
    }

    #[test]
    fn bash_hook_has_required_parts() {
        let hook = generate_hook(Shell::Bash, "/usr/local/bin/forgum-engine");
        assert!(hook.contains("forgum()"));
        assert!(hook.contains("__forgum_precmd"));
        assert!(hook.contains("PROMPT_COMMAND"));
        assert!(hook.contains("/usr/local/bin/forgum-engine"));
        assert!(hook.contains("--background"));
        assert!(hook.contains("--duration 0"));
    }

    #[test]
    fn zsh_hook_uses_precmd_functions() {
        let hook = generate_hook(Shell::Zsh, "/usr/local/bin/forgum-engine");
        assert!(hook.contains("precmd_functions"));
        assert!(hook.contains("forgum()"));
    }

    #[test]
    fn fish_hook_uses_function() {
        let hook = generate_hook(Shell::Fish, "/usr/local/bin/forgum-engine");
        assert!(hook.contains("function forgum"));
        assert!(hook.contains("function __forgum_sweep"));
        assert!(hook.contains("--on-event fish_prompt"));
    }

    #[test]
    fn pwsh_hook_has_prompt_wrapper() {
        let hook = generate_hook(Shell::Pwsh, "C:\\forgum-engine.exe");
        assert!(hook.contains("function forgum"));
        assert!(hook.contains("__ForgumPromptBackup"));
        assert!(hook.contains("function global:prompt"));
    }

    #[test]
    fn cmd_hook_has_required_parts() {
        let engine = "C:\\forgum-engine.exe";
        let hook = generate_cmd_hook(engine);
        assert!(hook.contains(">>> forgum"));
        assert!(hook.contains("<<< forgum"));
        assert!(hook.contains("prompt"));
        assert!(hook.contains("sweep"));
        assert!(hook.contains(engine));
        assert!(hook.contains("cmd"));
    }

    #[test]
    fn powershell_hook_has_prompt_wrapper() {
        let hook = generate_hook(Shell::PowerShell, "C:\\forgum-engine.exe");
        assert!(hook.contains("function forgum"));
        assert!(hook.contains("__ForgumPromptBackup"));
        assert!(hook.contains("function global:prompt"));
    }

    #[test]
    fn cmd_display_and_parse() {
        assert_eq!(Shell::Cmd.to_string(), "cmd");
        assert_eq!(Shell::PowerShell.to_string(), "powershell");
        assert_eq!(Shell::parse("CMD"), Some(Shell::Cmd));
    }

    #[test]
    fn all_hooks_contain_engine_path() {
        let path = "/opt/forgum/bin/forgum-engine";
        for shell in [
            Shell::Bash,
            Shell::Zsh,
            Shell::Fish,
            Shell::Pwsh,
            Shell::Cmd,
            Shell::PowerShell,
        ] {
            let hook = generate_hook(shell, path);
            assert!(hook.contains(path), "shell {shell} missing engine path");
        }
    }

    #[test]
    fn all_hooks_have_header_and_footer() {
        for shell in [
            Shell::Bash,
            Shell::Zsh,
            Shell::Fish,
            Shell::Pwsh,
            Shell::Cmd,
            Shell::PowerShell,
        ] {
            let hook = generate_hook(shell, "/usr/bin/forgum-engine");
            assert!(hook.contains(">>> forgum"), "shell {shell} missing header");
            assert!(hook.contains("<<< forgum"), "shell {shell} missing footer");
        }
    }

    #[test]
    fn zellij_config_has_required_parts() {
        let config = generate_zellij_config("/usr/local/bin/forgum-engine");
        assert!(config.contains(">>> forgum zellij >>>"));
        assert!(config.contains("<<< forgum zellij <<<"));
    }

    #[test]
    fn wezterm_config_has_required_parts() {
        let config = generate_wezterm_config("/usr/local/bin/forgum-engine");
        assert!(config.contains(">>> forgum wezterm >>>"));
        assert!(config.contains("<<< forgum wezterm <<<"));
        assert!(config.contains("/usr/local/bin/forgum-engine"));
    }

    #[test]
    fn screen_config_has_required_parts() {
        let config = generate_screen_config("/usr/local/bin/forgum-engine");
        assert!(config.contains(">>> forgum screen >>>"));
        assert!(config.contains("<<< forgum screen <<<"));
    }

    #[test]
    fn tmux_config_has_required_parts() {
        let config = generate_tmux_config("/usr/local/bin/forgum-engine");
        assert!(config.contains(">>> forgum tmux >>>"));
        assert!(config.contains("<<< forgum tmux <<<"));
        assert!(config.contains("status-right-length 100"));
        assert!(config.contains("status-interval 5"));
        assert!(config.contains("status-right"));
        assert!(config.contains("status-line --max-len 70"));
        assert!(config.contains("pane-focus-in"));
        assert!(config.contains("pane-focus-out"));
        assert!(config.contains("/usr/local/bin/forgum-engine"));
    }
}
