//! Integration test: shell hook generation for every `Shell` variant.

use forgum_engine::init::{generate_hook, generate_tmux_config, Shell};

const ENGINE: &str = "/usr/local/bin/forgum";

#[test]
fn shell_parse_all_variants() {
    assert_eq!(Shell::parse("bash"), Some(Shell::Bash));
    assert_eq!(Shell::parse("zsh"), Some(Shell::Zsh));
    assert_eq!(Shell::parse("fish"), Some(Shell::Fish));
    assert_eq!(Shell::parse("pwsh"), Some(Shell::Pwsh));
    assert_eq!(Shell::parse("powershell"), Some(Shell::PowerShell));
    assert_eq!(Shell::parse("cmd"), Some(Shell::Cmd));
    assert_eq!(Shell::parse("elvish"), Some(Shell::Elvish));
    assert_eq!(Shell::parse("nushell"), Some(Shell::Nushell));
    assert_eq!(Shell::parse("nu"), Some(Shell::Nushell));
    assert_eq!(Shell::parse("carapace"), Some(Shell::Carapace));
    assert_eq!(Shell::parse("xonsh"), Some(Shell::Xonsh));
    assert_eq!(Shell::parse("tcsh"), Some(Shell::Tcsh));
    assert_eq!(Shell::parse("csh"), Some(Shell::Tcsh));
    assert_eq!(Shell::parse("ksh"), Some(Shell::Ksh));
    assert_eq!(Shell::parse("mksh"), Some(Shell::Ksh));
    assert_eq!(Shell::parse("oksh"), Some(Shell::Ksh));
    assert_eq!(Shell::parse("pdksh"), Some(Shell::Ksh));
    assert_eq!(Shell::parse("ion"), Some(Shell::Ion));
    assert_eq!(Shell::parse("oil"), Some(Shell::Oil));
    assert_eq!(Shell::parse("osh"), Some(Shell::Oil));
    assert_eq!(Shell::parse("ysh"), Some(Shell::Oil));
    assert_eq!(Shell::parse("yash"), Some(Shell::Yash));
    assert_eq!(Shell::parse("nonsense"), None);
}

#[test]
fn every_shell_hook_is_nonempty_and_contains_engine_path() {
    for shell in [
        Shell::Bash,
        Shell::Zsh,
        Shell::Fish,
        Shell::Pwsh,
        Shell::Cmd,
        Shell::PowerShell,
        Shell::Nushell,
        Shell::Elvish,
        Shell::Carapace,
        Shell::Xonsh,
        Shell::Tcsh,
        Shell::Ksh,
        Shell::Ion,
        Shell::Oil,
        Shell::Yash,
    ] {
        let hook = generate_hook(shell, ENGINE);
        assert!(!hook.is_empty(), "hook for {shell} must not be empty");
        assert!(
            hook.contains(ENGINE),
            "hook for {shell} must embed the engine path"
        );
    }
}

#[test]
fn every_shell_hook_has_header_and_footer() {
    for shell in [
        Shell::Bash,
        Shell::Zsh,
        Shell::Fish,
        Shell::Pwsh,
        Shell::Cmd,
        Shell::PowerShell,
        Shell::Nushell,
        Shell::Elvish,
        Shell::Carapace,
        Shell::Xonsh,
        Shell::Tcsh,
        Shell::Ksh,
        Shell::Ion,
        Shell::Oil,
        Shell::Yash,
    ] {
        let hook = generate_hook(shell, ENGINE);
        assert!(hook.contains(">>> forgum"), "shell {shell} missing header");
        assert!(hook.contains("<<< forgum"), "shell {shell} missing footer");
    }
}

#[test]
fn every_shell_hook_has_consistent_delimiters() {
    for &shell in Shell::ALL {
        let hook = generate_hook(shell, ENGINE);
        if shell == Shell::Cmd {
            assert!(
                hook.contains("rem >>> forgum (cmd) >>>"),
                "cmd hook must contain 'rem >>> forgum (cmd) >>>'"
            );
            assert!(
                hook.contains("rem <<< forgum <<<"),
                "cmd hook must contain 'rem <<< forgum <<<'"
            );
        } else {
            let expected_header = format!("# >>> forgum ({shell}) >>>");
            assert!(
                hook.contains(&expected_header),
                "shell {shell} hook must contain '{expected_header}'"
            );
            assert!(
                hook.contains("# <<< forgum <<<"),
                "shell {shell} hook must contain '# <<< forgum <<<'"
            );
        }
    }
}

#[test]
fn every_shell_hook_has_standard_forgum_header_comment() {
    for &shell in Shell::ALL {
        let hook = generate_hook(shell, ENGINE);
        let expected = format!("Generated by forgum init {shell} — do not edit by hand");
        let header_line = hook
            .lines()
            .find(|l| l.contains("Generated by"))
            .unwrap_or_else(|| {
                panic!("shell {shell} missing 'Generated by' comment line in:\n{hook}")
            });
        assert!(
            header_line.contains(&expected),
            "shell {shell} header comment mismatch. Expected substring: '{expected}'. Got line: '{header_line}'"
        );
        assert!(
            !header_line.contains("forgum-engine"),
            "shell {shell} header comment must say 'forgum', not 'forgum-engine': '{header_line}'"
        );
    }
}

#[test]
fn every_shell_hook_is_cleanly_uninstalled_by_marker_delimiters() {
    for &shell in Shell::ALL {
        let hook = generate_hook(shell, ENGINE);
        // 1. Standalone removal
        let (cleaned_alone, removed_alone) =
            forgum_platform::remove_all_forgum_blocks(hook.clone());
        assert!(
            removed_alone,
            "shell {shell} standalone hook must be recognized by remove_all_forgum_blocks"
        );
        let remaining = cleaned_alone.trim();
        assert!(
            remaining.is_empty(),
            "shell {shell} standalone hook must be cleanly removed; leftover: {remaining}"
        );

        // 2. Embedded removal in user profile
        let user_rc =
            format!("# User RC Start\nexport FORGUM_TEST=1\n{hook}\nalias l='ls'\n# User RC End\n");
        let (cleaned_embedded, removed_embedded) =
            forgum_platform::remove_all_forgum_blocks(user_rc);
        assert!(
            removed_embedded,
            "embedded shell {shell} hook must be recognized and removed"
        );
        assert_eq!(
            cleaned_embedded,
            "# User RC Start\nexport FORGUM_TEST=1\nalias l='ls'\n# User RC End\n",
            "embedded shell {shell} hook must not alter surrounding user config"
        );
    }
}

#[test]
fn bash_hook_uses_prompt_command() {
    let hook = generate_hook(Shell::Bash, ENGINE);
    assert!(hook.contains("function forgum") || hook.contains("forgum()"));
    assert!(hook.contains("PROMPT_COMMAND"));
    assert!(hook.contains("--background"));
    assert!(hook.contains("--duration 0"));
}

#[test]
fn zsh_hook_uses_precmd_functions() {
    let hook = generate_hook(Shell::Zsh, ENGINE);
    assert!(hook.contains("precmd_functions"));
    assert!(hook.contains("forgum()"));
}

#[test]
fn fish_hook_uses_function_and_event() {
    let hook = generate_hook(Shell::Fish, ENGINE);
    assert!(hook.contains("function forgum"));
    assert!(hook.contains("function __forgum_sweep"));
    assert!(hook.contains("--on-event fish_prompt"));
}

#[test]
fn pwsh_hook_wraps_prompt() {
    let hook = generate_hook(Shell::Pwsh, ENGINE);
    assert!(hook.contains("function forgum"));
    assert!(hook.contains("__ForgumPromptBackup"));
    assert!(hook.contains("function global:prompt"));
}

#[test]
fn cmd_hook_contains_prompt_and_sweep() {
    let hook = generate_hook(Shell::Cmd, ENGINE);
    assert!(hook.contains(">>> forgum"));
    assert!(hook.contains("<<< forgum"));
    assert!(hook.contains("prompt"));
    assert!(hook.contains("sweep"));
    assert!(hook.contains(ENGINE));
    assert!(hook.contains("cmd"));
}

#[test]
fn powershell_hook_wraps_prompt() {
    let hook = generate_hook(Shell::PowerShell, ENGINE);
    assert!(hook.contains("function forgum"));
    assert!(hook.contains("__ForgumPromptBackup"));
}

#[test]
fn shell_display_and_config_path() {
    assert_eq!(Shell::Bash.to_string(), "bash");
    assert_eq!(Shell::Zsh.to_string(), "zsh");
    assert_eq!(Shell::Fish.to_string(), "fish");
    assert_eq!(Shell::Pwsh.to_string(), "pwsh");
    assert_eq!(Shell::Cmd.to_string(), "cmd");
    assert_eq!(Shell::PowerShell.to_string(), "powershell");
    assert!(Shell::Pwsh
        .default_config_path()
        .contains(".config/forgum/config.json"));
    assert!(Shell::Cmd
        .default_config_path()
        .contains(".config/forgum/config.json"));
    assert!(Shell::PowerShell
        .default_config_path()
        .contains(".config/forgum/config.json"));
}

#[test]
fn tmux_config_contains_expected_markers() {
    let cfg = generate_tmux_config(ENGINE);
    assert!(cfg.contains(">>> forgum tmux >>>"));
    assert!(cfg.contains("<<< forgum tmux <<<"));
    assert!(cfg.contains("status-interval 5"));
    assert!(cfg.contains("status-line --max-len 70"));
    assert!(cfg.contains("pane-focus-in"));
    assert!(cfg.contains(ENGINE));
}

#[test]
fn nushell_hook_wraps_def() {
    let hook = generate_hook(Shell::Nushell, ENGINE);
    assert!(hook.contains("def --wrapped forgum"));
    assert!(hook.contains("fortune"));
    assert!(hook.contains(ENGINE));
    assert!(hook.contains("# >>> forgum (nushell) >>>"));
    assert!(hook.contains("# <<< forgum <<<"));
}

#[test]
fn elvish_hook_wraps_fn() {
    let hook = generate_hook(Shell::Elvish, ENGINE);
    assert!(hook.contains("fn forgum {|@args|"));
    assert!(hook.contains("fortune"));
    assert!(hook.contains(ENGINE));
    assert!(hook.contains("# >>> forgum (elvish) >>>"));
    assert!(hook.contains("# <<< forgum <<<"));
}

#[test]
fn multiplexer_and_statusline_configs_cleanly_uninstalled() {
    use forgum_engine::init::{
        generate_byobu_config, generate_screen_config, generate_starship_config,
        generate_wezterm_config, generate_zellij_config,
    };

    let configs = [
        generate_tmux_config(ENGINE),
        generate_zellij_config(ENGINE),
        generate_wezterm_config(ENGINE),
        generate_screen_config(ENGINE),
        generate_starship_config(ENGINE),
        generate_byobu_config(ENGINE),
    ];

    for cfg in configs {
        let (cleaned, removed) = forgum_platform::remove_all_forgum_blocks(cfg.clone());
        assert!(
            removed,
            "config block must be recognized and removed by remove_all_forgum_blocks:\n{cfg}"
        );
        assert!(
            cleaned.trim().is_empty() || cleaned.trim() == "#!/bin/sh",
            "config block must leave no leftover lines, got:\n{cleaned}"
        );
    }
}

#[test]
fn soft_and_purge_shell_uninstall_preserves_user_profile() {
    use forgum_platform::shell::{remove_all_forgum_blocks, remove_delimited_block};

    let user_bashrc = r#"
# User Custom Aliases
export PATH="$HOME/bin:$PATH"
alias ll="ls -la"
alias gs="git status"

# >>> forgum (bash) >>>
# Generated by forgum init bash — do not edit by hand
__FORGUM_ENGINE="/usr/local/bin/forgum"
forgum() {
  "$__FORGUM_ENGINE" "$@"
}
# <<< forgum <<<

# >>> forgum completions (bash) >>>
# Generated by forgum completions bash
complete -F _forgum forgum
# <<< forgum completions <<<

# Prompt configuration
export PS1="\u@\h:\w\$ "
"#;

    // 1. Single delimited block removal (e.g. removing completions only)
    let (after_hook_removal, removed_hook) =
        remove_delimited_block(user_bashrc, "# >>> forgum (bash) >>>", "# <<< forgum <<<");
    assert!(removed_hook, "Target hook block must be removed");
    assert!(!after_hook_removal.contains("__FORGUM_ENGINE"));
    assert!(after_hook_removal.contains("alias ll=\"ls -la\""));
    assert!(after_hook_removal.contains("# >>> forgum completions (bash) >>>"));

    // 2. Full uninstallation: remove all forgum blocks cleanly
    let (cleaned, removed_all) = remove_all_forgum_blocks(user_bashrc.to_string());
    assert!(removed_all, "All forgum blocks must be removed");
    assert!(!cleaned.contains(">>> forgum"));
    assert!(!cleaned.contains("<<< forgum"));
    assert!(!cleaned.contains("__FORGUM_ENGINE"));
    assert!(!cleaned.contains("complete -F _forgum"));

    // User's original configuration must remain 100% intact
    assert!(cleaned.contains("export PATH=\"$HOME/bin:$PATH\""));
    assert!(cleaned.contains("alias ll=\"ls -la\""));
    assert!(cleaned.contains("alias gs=\"git status\""));
    assert!(cleaned.contains("export PS1=\"\\u@\\h:\\w\\$ \""));
}

#[test]
fn shell_sweepers_reset_scroll_margins_and_guard_split_launch() {
    // Bash
    let bash = generate_hook(Shell::Bash, ENGINE);
    assert!(
        bash.contains("printf '\\x1b[r'"),
        "bash sweeper must reset scroll margins with \\x1b[r"
    );
    assert!(
        bash.contains("if [ ! -f \"$state\" ]; then"),
        "bash split mode must guard against duplicate daemon launch"
    );

    // Zsh
    let zsh = generate_hook(Shell::Zsh, ENGINE);
    assert!(
        zsh.contains("printf '\\x1b[r'"),
        "zsh sweeper must reset scroll margins with \\x1b[r"
    );
    assert!(
        zsh.contains("if [ ! -f \"$state\" ]; then"),
        "zsh split mode must guard against duplicate daemon launch"
    );

    // Fish
    let fish = generate_hook(Shell::Fish, ENGINE);
    assert!(
        fish.contains("printf '\\x1b[r'"),
        "fish sweeper must reset scroll margins with \\x1b[r"
    );
    assert!(
        fish.contains("if not test -f $state"),
        "fish split mode must guard against duplicate daemon launch"
    );

    // PowerShell / Pwsh
    let pwsh = generate_hook(Shell::Pwsh, ENGINE);
    assert!(
        pwsh.contains("[Console]::Write(\"$esc[r\")"),
        "pwsh sweeper must reset scroll margins with $esc[r"
    );
    assert!(
        pwsh.contains("if (-not (Test-Path $state))"),
        "pwsh split mode must guard against duplicate daemon launch"
    );

    let ps = generate_hook(Shell::PowerShell, ENGINE);
    assert!(
        ps.contains("[Console]::Write(\"$esc[r\")"),
        "powershell sweeper must reset scroll margins with $esc[r"
    );
    assert!(
        ps.contains("if (-not (Test-Path $state))"),
        "powershell split mode must guard against duplicate daemon launch"
    );
}
